- CorsixTH/Lua/ui.lua
> SDL2: Fix cursor position in main menu on drag

- CONTRIBUTING.txt
- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/class.lua
- CorsixTH/Lua/config_finder.lua
- CorsixTH/Lua/debug_script.lua
- CorsixTH/Lua/dialogs/place_objects.lua
- CorsixTH/Lua/dialogs/resizables/main_menu.lua
- CorsixTH/Lua/entities/staff.lua
- CorsixTH/Lua/game_ui.lua
- CorsixTH/Lua/humanoid_actions/die.lua
- CorsixTH/Lua/objects/gates_to_hell.lua
- CorsixTH/Lua/rooms/operating_theatre.lua
- CorsixTH/Lua/rooms/scanner_room.lua
- CorsixTH/Lua/ui.lua
- CorsixTH/Lua/world.lua
- scripts/check_lua_classes.py
- scripts/check_trailing_whitespaces.py
> Fix (mostly trailing) white spaces, and attempt to repair the script.

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/confirm_dialog.lua
- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/dialogs/furnish_corridor.lua
- CorsixTH/Lua/dialogs/hire_staff.lua
- CorsixTH/Lua/dialogs/information.lua
- CorsixTH/Lua/window.lua
SDL 2 changed the name of this key from "enter" to "return" so
this commit updates references to this key's name.
> SDL 2: Renamed "enter" key character references to: "return"

- CONTRIBUTING.txt
Fix suggested by MarkL, see also
https://github.com/Alberth289346/CorsixTH/commit/4802e64322d4243c2241ab453f890484fd4ed311#commitcomment-9352189
> Fix suggested by MarkL

- .travis.yml
- CONTRIBUTING.txt
- CorsixTH/Luatest/.busted
- CorsixTH/Luatest/README.txt
- CorsixTH/Luatest/TH.lua
- CorsixTH/Luatest/class_test_base.lua
- CorsixTH/Luatest/non_strict.lua
- CorsixTH/Luatest/spec/class_spec.lua
- CorsixTH/Luatest/spec/entities/object_spec.lua
This is a proposal how we could start creating unit tests for the Lua part of the code base. What do you guys think?
If someone could try it out on Linux that would be great. :-)
> Added base for using a Unit test framework: Busted

- CorsixTH/Luatest/.busted
> Fixed path separator in Luatest/.busted file.

- CorsixTH/Lua/ui.lua
- CorsixTH/Src/th_movie.cpp
Addresses issue mentioned in the discussion of #450.
> Fix THMovie overlay spew

- CorsixTH/Lua/ui.lua
> Handle the case when we don't have windows on Esc.

- CorsixTH/Lua/ui.lua
Fix for pop-up error noticed in debug code.
> Fixed nil references in debugger error popup

- .travis.yml
Generalize the sourceforge MingW download addresses to increase the odds of getting the archives.
> Generalize the sourceforge MingW download addresses

- CorsixTH/Src/th_gfx_sdl.cpp
This creates a surface based on the rendertarget dimensions and a
standard RGB24 format (which SDL_SaveBMP should be able to use directly
without any conversions), rather than trying to retrieve the window
surface of our (potentially hardware-accelerated, which means it doesn't
have a backing surface) window.
Fixes CorsixTH/CorsixTH#739.
> Reimplement THRenderTarget::takeScreenshot.

- CorsixTH/Lua/dialogs/bottom_panel.lua
Fixes #742.  Thanks AgainstTheCurrent.
> Move math.floor down to draw command after step is multiplied.

- CorsixTH/Src/th_gfx.h
- CorsixTH/Src/th_lua_gfx.cpp
Adding some doxymentation, and removing a #define.
> Reduce render target creation params magic

- CorsixTH/changelog.txt
Initial version of 0.5 release notes.
> Updated changelog in preparation for 0.5

- CorsixTH/Lua/dialogs/fullscreen/fax.lua
- CorsixTH/Lua/dialogs/message.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/world.lua
Rather than exporting additional info knowledge, I opted for deriving that knowledge again once the choice number was known.
> Timeout choice of the fax didn't handle additionalInfo. Fixes #759

- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/entities/patient.lua
- CorsixTH/Lua/epidemic.lua
Fixes nil reference and removes open vaccination calls when a player leaves/epidemic has ended
> Fixes #748 - vaccination nil reference

- .travis.yml
Link to diff from SDL hg repository wasn't functioning
> Reference CorsixTH\deps for SDL2 patch

- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/world.lua
Also split hospital room cost and discovery state initialization away from room initialization.
> Disable diseases that need unavailable treatment rooms. Addresses #749.

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/audio.lua
- CorsixTH/Lua/dialogs/fullscreen.lua
- CorsixTH/Lua/movie_player.lua
- CorsixTH/Lua/ui.lua
Fixes #775 among other crashes relating to screen resolution and lua 5.3
> Fix numerous issues with odd screen resolutions and lua 5.3

- CorsixTH/Lua/dialogs/queue_dialog.lua
> Queue Dialog crash fix

- .travis.yml
The sourceforge download for these files frequently failed
> Use CorsixTH/deps for freetype in travisci

- LICENSE.txt
> Update LICENSE.txt with updated / missing licenses

- CorsixTH/Lua/languages/norwegian.lua
> Update norwegian.lua for v0.5

- CorsixTH/Lua/languages/french.lua
> Add menu_debug.connect_debugger in french.lua

- CorsixTH/Lua/languages/german.lua
First i wanted to update the `drug_improved_1` string, only
There was a `%1` used instead of a `%s`
But i updated some other stuff, too
> Some small updates for the German language file

- README.md
> Fix various grammar issues in README.md

- CorsixTH/Lua/dialogs/bottom_panel.lua
Fixes Lua 5.3 crash, see issue #877
> Round FPS before displaying

- README.md
mini navbar for easier navigation for new users
> Add project links to README.md

- CorsixTH/Lua/queue.lua
Nothing revolutionary, just a bunch of --! lines, and removal of one unused local variable.
> Doc: Add documentation for most Queue methods

- CorsixTH/Lua/entities/vip.lua
No reputation boost or money if you are not at least 'good' for the VIP. See also discussion at #835
I expect this to go in after 0.50, but who knows :)
> [RFC] VIP stops giving money and reputation to mediocre hospitals

- CorsixTH/Lua/languages/french.lua
This PR re-organises french.lua to match the layout of english.lua
> Re-Organise french.lua, Translation fixes & formatting/organisation fixes

- README.md
Update the icon in README.md to Release 0.50.
> Update latest github README.md release to 0.50

- CorsixTH/Lua/languages/french.lua
Double indexing for fields in a table does not work.
I fixed it enough to make it load again, whether all entries got preserved, I don't know.
Alternatively, patch by @wolfy1339 could be reverted.
> Fix: French language could not be loaded, due to indexing into non-existing intermediate tables.

- CorsixTH/Lua/languages/spanish.lua
Removing a superfluous line, updating the copyright year.
> Updating Spanish translation

- CorsixTH/Lua/dialogs/patient.lua
- CorsixTH/Lua/dialogs/watch.lua
Needs confirming it works, have tested it a little myself already.
> [RDY] Implemented missing timer click behaviour. Fixes #882.

- CorsixTH/Lua/languages/czech.lua
Update to the translation containing the latest changes.
> Czech translation update.

- CorsixTH/Src/th_lua_map.cpp
- CorsixTH/Src/th_map.h
Rewrote copying of "Passable if not blueprint" bit to "passable" bit, to make it more clear and free from assuming the passable bit is bit 0.
> Remove th_map #define macros

- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/world.lua
hospital.lua seems like a better place for hiring staff :p
> Move initialization of hospital staff to the hospital class.

- CorsixTH/Src/th_movie.cpp
- CorsixTH/Src/th_movie.h
Was passing destination height instead of source height, leading to segfaults
Fixes #939
> Fix parameters to sws_scale

- CorsixTH/Lua/ui.lua
> Render the main menu background correctly centered

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/epidemic.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/humanoid_actions/seek_reception.lua
- CorsixTH/Lua/objects/reception_desk.lua
- CorsixTH/Lua/world.lua
May need a little testing, in particular Hospital:onPlaceObject was quite modified
> [RDY] Various small steps in reducing code complexity

- CorsixTH/Src/th_lua.h
> Fix compile against lua 5.1

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/entities/humanoid.lua
- CorsixTH/Lua/entities/machine.lua
- CorsixTH/Lua/entities/patient.lua
- CorsixTH/Lua/entities/staff.lua
- CorsixTH/Lua/entity.lua
- CorsixTH/Lua/humanoid_actions/seek_toilets.lua
- CorsixTH/Lua/room.lua
- CorsixTH/Lua/rooms/toilets.lua
- CorsixTH/Lua/world.lua
there is loads more cb queues, not sure if it should be added here
> Broadcast new rooms to entities instead of keeping a callback administration.

- CorsixTH/Lua/objects/plant.lua
Plants needed some love (and water)
> Plant refactorings

- CorsixTH/Lua/dialogs/resizables/map_editor.lua
Added different floor types leading to different combinations of passable, buildable, and hospital flags.
Added door objects
Remaining issue is a weird shadow sprite that gets added somewhere.
I also have a number of sanity checks for parcels (more can/should be added), but it needs a way to tell the user what is wrong.
A message is probably possible, but how to indicate what tile(s) is/are involved?
Can also be added later if you like. It sounds like a nice job for a starting lua programmer.
> Map editor cell flags and door objects

- AnimView/rnc.cpp
Hi,
This made the Debian FTP Masters angry :sweat: 
Hopefully the .zip archive does include a licens :smile:
> fix copyright header of AnimView/rnc.cpp

- CorsixTH/Lua/api_version.lua
- CorsixTH/Lua/game_ui.lua
- CorsixTH/Lua/ui.lua
- CorsixTH/Lua/window.lua
- CorsixTH/Src/sdl_core.cpp
> [RDY] Fix #745 and enhance numpad / keypad support

- CorsixTH/Src/sdl_audio.cpp
- CorsixTH/Src/sdl_core.cpp
- CorsixTH/Src/th_lua_gfx.cpp
- CorsixTH/Src/th_lua_internal.h
- CorsixTH/Src/th_lua_sound.cpp
Replace stricmp uses with strcmp for own data comparison, or with own ignorecase_cmp
> [RDY] Drop stricmp

- CorsixTH/Lua/languages/czech.lua
Adding newest string concerning map editor
> Czech localization update

- CorsixTH/Lua/dialogs/fullscreen/bank_manager.lua
> Always print integer numbers in the bank manager window. Fixes issue 974

- CorsixTH/Lua/config_finder.lua
- WindowsInstaller/config_template.txt
These are up to date, and I've added a note in the wiki for future language contributors to update these files.
> Add newer languages to config_finder and config_template

- CorsixTH/Lua/languages/norwegian.lua
Shuffled the map editor 'pages' strings a bit in sane order, fixed some indent problems, and killed some trailing white space. Otherwise, it's all Grimdocs' work.
> Norwegian update by Grimdoc, fixes #1000

- appveyor.yml
Change Visual Studio version to Visual Studio 2015, and include Campaigns.
> [RDY] AppVeyor 0.60 updates

- LICENSE.txt
Some effort was made to capture the names of contributors. I did not include
contributors in the list who did not include their full name for their commit.
I also used a very crude process of selecting those who did include their full
name based loosely on commit count. I encourage anyone missing from the list
to update the file with the appropriate details or contact me with your full
name and the name that appears on the author line of your commits.
> [RDY] Updated LICENCE.txt for 2016 and expand author list

- CorsixTH/Lua/entities/patient.lua
- CorsixTH/Lua/objects/bin.lua
- CorsixTH/Lua/objects/plant.lua
See #71 feature request. phillipp took it on, but that didn't materialize,apparently.
Technically, it needs a savegame bump, I can add one if you think it's needed, but we just had 2.
> [RDY] Patient littering

- CorsixTH/Src/th_movie.cpp
Replaces functions that are deprecated in ffmpeg 3.0. Compatibility is preserved with all previous FFmpeg and libav versions we support. These issues were mentioned in #1042
> [RDY] FFmpeg 3 deprecation fixes

- README.md
I believe there should be a comma there because it reads better
> Add missing comma in README.md

- CorsixTH/Lua/hospital.lua
> Do not kill cured emergency patients after emergency

- CorsixTH/Lua/languages/norwegian.lua
@Grimdoc  Lots of strings get removed, is this what you want?
> [rfc] Updates for Norwegian, by Grimdoc. Fixes #1075

- CorsixTH/Lua/dialogs/fullscreen/fax.lua
- CorsixTH/Lua/dialogs/patient.lua
- CorsixTH/Lua/entities/patient.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/humanoid_actions/seek_room.lua
- CorsixTH/Lua/objects/helicopter.lua
- CorsixTH/Lua/rooms/gp.lua
Moving hospital administration bits out of the patient. I think there is more, but this seems like a good first step.
Code is mostly copy/paste, but the various self/patient/hospital replacements are easy to mess up.
I'd be fine with postponing after 0.60
> [RDY] Refactor patient

- CorsixTH/Lua/dialogs/edit_room.lua
> [RDY] Show waiting cursor during clear area phase

- CorsixTH/CMakeLists.txt
> Include Campaigns directory in CMake build

- CorsixTH/Lua/rooms/gp.lua
Thanks Brainsample
Copied from #1106
> Fix mood when staff leaves GP

- CorsixTH/Lua/api_version.lua
- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/dialogs/place_objects.lua
- CorsixTH/Lua/dialogs/place_staff.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/humanoid_actions/die.lua
- CorsixTH/Lua/humanoid_actions/seek_reception.lua
- CorsixTH/Lua/map.lua
- CorsixTH/Lua/world.lua
- CorsixTH/Src/th_lua_map.cpp
- CorsixTH/Src/th_map.cpp
Corrects an issue with multiplayer maps where one player would be able to
build on another player's hospital. Also fixes a bug in the map editor
causing flags to be lost if they were not assigned a parcel before being
saved.
This fixes #1044 and obsoletes #1082 though it is a more complicated patch.
I have tested the cases I could think of, but I may have missed something.
> [RDY] Load flags regardless of parcel, and ensure player match.

- CorsixTH/Lua/languages/spanish.lua
Adding new strings, editing old ones, updating some old ones with what's
currently written on the English texts.
Replaces #1120 
Thanks @IlDucci
> [RDY] Updating Spanish translation

- CorsixTH/Lua/world.lua
Reception desk did not remove litter
> Remove litter from non-passable tiles too

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/audio.lua
- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/dialogs/place_objects.lua
- CorsixTH/Lua/dialogs/resizables/map_editor.lua
- CorsixTH/Lua/dialogs/tree_ctrl.lua
- CorsixTH/Lua/entities/grim_reaper.lua
- CorsixTH/Lua/entities/humanoid.lua
- CorsixTH/Lua/entity.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/humanoid_actions/vip_go_to_next_room.lua
- CorsixTH/Lua/map.lua
- CorsixTH/Lua/movie_player.lua
- CorsixTH/Lua/objects/bin.lua
- CorsixTH/Lua/persistance.lua
- CorsixTH/Lua/room.lua
- CorsixTH/Lua/world.lua
Remove the semi colons, and TAB characters, and fix indenting of two lines.
> [also rdy] Style fixes

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/place_objects.lua
- CorsixTH/Lua/entities/patient.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/languages/english.lua
- CorsixTH/Lua/objects/rathole.lua
- CorsixTH/Lua/room.lua
- CorsixTH/Lua/world.lua
- CorsixTH/Src/th_lua_map.cpp
- CorsixTH/Src/th_map.h
Let there be holes in the walls
> [rdy] Add homes for rat families in dirty hospitals

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
- CorsixTH/Lua/dialogs/patient.lua
- CorsixTH/Lua/epidemic.lua
Taking some of the bigger rewrites out of the lua check patch
> [rdy] Rewrite functions

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/game_ui.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/world.lua
This pull request addresses is a substantial reworking of Earthquakes, though it doesn't include a planned refactor of Earthquake related code into a new class.
It addresses issues: #1128 #550 and #296 and adds the warning quakes from the original game which cued the player that they need to repair any damaged machines which should solve a lot of users issues with earthquakes.
> [RDY] Earthquakes

- CorsixTH/Src/sdl_audio.cpp
When LUA_USE_APICHECK is enabled we would crash loading background music.
This is because we are trying to run the callback function on an old lua
state.
The callback always runs on the main thread.
Fixes #709
> [RDY] Fix async loading of background music

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/game_ui.lua
- CorsixTH/Lua/movie_player.lua
- CorsixTH/Lua/ui.lua
- CorsixTH/Src/sdl_core.cpp
- CorsixTH/Src/th_gfx_sdl.cpp
- CorsixTH/Src/th_lua_movie.cpp
- CorsixTH/Src/th_movie.cpp
- CorsixTH/Src/th_movie.h
This change makes the window resizeable which allows e.g. simply maximizing the window if you don't want to go into full screen mode. I've (lightly) tested this on Debian, I'd be interested to see if others think this is a good idea.
> [RDY] Allow resizing the main window

- CorsixTH/Lua/dialogs/resizables/menu_list_dialog.lua
- CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua
- CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua
- CorsixTH/Lua/dialogs/resizables/new_game.lua
- CorsixTH/Lua/dialogs/resizables/options.lua
- CorsixTH/Lua/dialogs/resizables/update.lua
- CorsixTH/Lua/dialogs/staff_dialog.lua
- CorsixTH/Lua/dialogs/staff_rise.lua
- CorsixTH/Lua/dialogs/tree_ctrl.lua
- CorsixTH/Lua/entities/grim_reaper.lua
- CorsixTH/Lua/entities/humanoid.lua
- CorsixTH/Lua/entities/machine.lua
The repair_loop_callback change in entities/machine.lua is a no-op, as
it was already false due to the "setProlongedUsage(false)" used at the
repair_action variable.
> Fix Lua code and variables of remaining windows, and a few entities.

- CorsixTH/Lua/entities/object.lua
- CorsixTH/Lua/entities/patient.lua
- CorsixTH/Lua/entities/staff.lua
- CorsixTH/Lua/entities/vip.lua
- CorsixTH/Lua/entity.lua
- CorsixTH/Lua/entity_map.lua
- CorsixTH/Lua/epidemic.lua
- CorsixTH/Lua/filesystem.lua
- CorsixTH/Lua/game_ui.lua
- CorsixTH/Lua/graphics.lua
- CorsixTH/Lua/hospital.lua
Also two bug fixes detected by Luacheck.
> Improve entities, graphics, filesystem, epidemic, and hospital

- CorsixTH/Lua/audio.lua
- CorsixTH/Lua/dialogs/build_room.lua
- CorsixTH/Lua/entity.lua
- CorsixTH/Lua/humanoid_actions/queue.lua
- CorsixTH/Lua/humanoid_actions/seek_reception.lua
- CorsixTH/Lua/humanoid_actions/seek_room.lua
- CorsixTH/Lua/humanoid_actions/vip_go_to_next_room.lua
- CorsixTH/Lua/movie_player.lua
- CorsixTH/Lua/queue.lua
- CorsixTH/Lua/research_department.lua
- CorsixTH/Lua/room.lua
- CorsixTH/Lua/rooms/operating_theatre.lua
- CorsixTH/Lua/string_extensions.lua
- CorsixTH/Lua/world.lua
- CorsixTH/Luatest/non_strict.lua
Not entirely done, but patch was large enough already
> [rdy as it ever will be] More fixes and improvements

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/fullscreen/hospital_policy.lua
> [rdy] Order of the sliders could make the 'guess_cure' slider unusable.

- CorsixTH/Lua/entities/patient.lua
> [rdy] Prevent displayed diagnosis progress from going over 100%

- CorsixTH/Lua/dialogs/fullscreen/graphs.lua
> Graph switched year too early, causing month 0

- CorsixTH/Lua/languages/norwegian.lua
Translation updates for Norwegian by Grimdoc Issue #1212
> [RDY] Norwegian translation updates

- CorsixTH/Lua/languages/polish.lua
Adds missing polish strings to:
Corsix main menu
Map Editor
Top menu
'Folders' menu
'Customize' menu
> [RDY] Missing polish translations

- CorsixTH/Lua/entity_map.lua
- CorsixTH/Src/lua.hpp
- CorsixTH/Src/th_lua_map.cpp
#630 for entity map
Plus just the 2 changes I picked up with a static analysis - lua compat lessthan and dupe getPlayerHeliportTile call
> [RDY] Entity map and cpp fixes

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/game_ui.lua
Correction for #1299 
You can download the artifact for that PR, but I'll warn up front - we provide absolutely no guarantee that save games based on a pull request will continue to work. In fact they very likely won't. The PR should be merged into an rc2 if there is one.
> Fix multigesture afterLoad

- CorsixTH/Lua/languages/french.lua
> [RDY] French Translation

- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/dialogs/place_staff.lua
- CorsixTH/Lua/entities/humanoid.lua
- CorsixTH/Lua/entities/patient.lua
- CorsixTH/Lua/entities/staff.lua
- CorsixTH/Lua/epidemic.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/humanoid_actions/die.lua
- CorsixTH/Lua/humanoid_actions/idle.lua
- CorsixTH/Lua/humanoid_actions/meander.lua
- CorsixTH/Lua/humanoid_actions/multi_use_object.lua
- CorsixTH/Lua/humanoid_actions/queue.lua
- CorsixTH/Lua/humanoid_actions/seek_room.lua
- CorsixTH/Lua/humanoid_actions/staff_reception.lua
- CorsixTH/Lua/humanoid_actions/use_object.lua
- CorsixTH/Lua/humanoid_actions/use_screen.lua
- CorsixTH/Lua/humanoid_actions/walk.lua
- CorsixTH/Lua/objects/reception_desk.lua
- CorsixTH/Lua/room.lua
- CorsixTH/Lua/rooms/decontamination.lua
- CorsixTH/Lua/rooms/dna_fixer.lua
- CorsixTH/Lua/rooms/electrolysis.lua
- CorsixTH/Lua/rooms/hair_restoration.lua
- CorsixTH/Lua/rooms/operating_theatre.lua
- CorsixTH/Lua/rooms/scanner_room.lua
- CorsixTH/Lua/rooms/toilets.lua
- CorsixTH/Lua/rooms/x_ray_room.lua
- CorsixTH/Luatest/class_test_base.lua
- CorsixTH/Luatest/spec/entities/humanoid_spec.lua
> [RDY]1334: Adds a no action check

- CorsixTH/Src/th_map.cpp
- CorsixTH/Src/th_map.h
Was using unsigned type for node difference, should be ptrdiff_t
Fixes #1338
> [RDY] Fix temperature diffusion

- CorsixTH/Src/iso_fs.cpp
- CorsixTH/Src/th_gfx.h
- CorsixTH/Src/th_gfx_font.cpp
- CorsixTH/Src/th_gfx_font.h
- CorsixTH/Src/th_gfx_sdl.cpp
- CorsixTH/Src/th_gfx_sdl.h
- CorsixTH/Src/th_lua.cpp
- CorsixTH/Src/th_lua_anims.cpp
- CorsixTH/Src/th_lua_gfx.cpp
- CorsixTH/Src/th_lua_internal.h
- CorsixTH/Src/th_lua_lfs_ext.cpp
- CorsixTH/Src/th_lua_map.cpp
- CorsixTH/Src/th_lua_movie.cpp
- CorsixTH/Src/th_lua_sound.cpp
- CorsixTH/Src/th_lua_strings.cpp
- CorsixTH/Src/th_lua_ui.cpp
- CorsixTH/Src/th_map.cpp
- CorsixTH/Src/th_map.h
- CorsixTH/Src/th_pathfind.cpp
- CorsixTH/Src/th_pathfind.h
I reviewed all enum usage in CorsixTH and converted to `enum class` and/or added type specifiers as appropriate for improved type safety, and ease of analysis.
> [RDY] Enum modernization

- CorsixTH/Lua/app.lua
The file sizes are the same on demo files from different sources.
> [RDY} Check for corrupt demo game files

- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/dialogs/place_objects.lua
- CorsixTH/Lua/entities/machine.lua
- CorsixTH/Lua/entities/object.lua
- CorsixTH/Luatest/spec/entities/machine_spec.lua
> [RDY]67 moving clears usage

- .luacheckrc
- CorsixTH/Lua/entities/humanoid.lua
- CorsixTH/Lua/entities/staff.lua
- CorsixTH/Luatest/TH.lua
- CorsixTH/Luatest/class_test_base.lua
- CorsixTH/Luatest/spec/entities/humanoid_spec.lua
- CorsixTH/Luatest/spec/entities/staff_spec.lua
> [RDY] Adds tostring on humanoid

- CorsixTH/Lua/languages/spanish.lua
https://github.com/CorsixTH/CorsixTH/issues/1251
The final message shown on game completion has been condensed a bit to fit onto the final screen. It probably can't be made much shorter removing some key information.
> Issue #1251 - Final message too long in Spanish

- common/rnc.cpp
The endpos was misinterpreted in rnc.cpp. This didn't result in any read
errors in valgrind, presumably because a null byte was added to the end
of the input stream; however AnimView which allocated exactly the read
file to the input buffer showed the error.
One step towards fixing #1258
> [RDY] Fix invalid reads in RNC

- CorsixTH/Src/th_movie.cpp
Regression from rename patches.
> [RDY] Fix audio in movies

- CorsixTH/Src/sdl_audio.cpp
This is the last memory leak I encounter when running to the main menu and closing the program that appears to be fixable in our code.
There are quite a few resulting from SDL_Init, originating in X11, but that appears to be a problem with those libraries.
> [RDY] Clean memory related to allocating music thread

- .travis.yml
- CorsixTH/Lua/languages/norwegian.lua
- CorsixTH/Src/lua_rnc.cpp
- CorsixTH/Src/th_gfx_sdl.h
- CorsixTH/Src/th_map.cpp
- CorsixTH/Src/th_map.h
- SpriteEncoder/decode.py
- scripts/check_language_files_not_BOM.py
- scripts/check_lua_classes.py
- scripts/check_trailing_whitespaces.py
I know this project is primarily Lua, but there's some Python code too, so I ran flake8 on it. flake8 is a Python linter/style checker, and can be a bit nitpicky at times, but I think these changes is an improvement. Feel free to only pick specific commits if you wish.
> [RDY] Shape up scripts/*.py and SpriteEncoder/decode.py

- CorsixTH/Lua/dialogs/place_objects.lua
- CorsixTH/Lua/entities/machine.lua
Addresses #624/#1329 - reposition/reorientation of a machine recalculates the handyman position.
> [RDY] Recalculate handyman position on machines when editing a room

- CorsixTH/Lua/world.lua
Psychiatric Room instead of just Psychiatric
> [RDY] Faxes should refer to room.long_name

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/rooms/research.lua
> [RDY] Autospy can be discovered multiple times - morale related chances

- CorsixTH/Lua/hospital.lua
As in issue #488
Also corrected time for fax refusal was using 24 ticks per day. Used the Date.hoursPerDay and also adjusted number of days to align a little better with TH
> [RDY] Add drug specific message to emergency fax

- CorsixTH/Lua/rooms/operating_theatre.lua
- CorsixTH/Lua/rooms/research.lua
- CorsixTH/Lua/rooms/ward.lua
#757, #1489, #1490
All three of these issues are related to the one function not accounting for staff leaving the room correctly.
> [RDY] Account for leaving staff in getStaffMember for rooms with multiple staff

- CorsixTH/Lua/entities/humanoids/staff/doctor.lua
- CorsixTH/Lua/entities/humanoids/staff/handyman.lua
- CorsixTH/Lua/entities/humanoids/staff/receptionist.lua
- CorsixTH/Lua/hospital.lua
> [RDY] Handyman:unassignTask before calling Staff.onPlaceInCorridor

- CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
- LICENSE.txt
Include the contributions from late 2018 through now in the
license file, and appropriately credit legeit for the hotkey
dialog.
@leiget could you verify you approve of how I've assigned your copyright?
> [RDY] Update license file

- changelog.txt
Let me know if I missed anything notable, or made any typos.
> [RDY] Update changelog with changes between 0.62 and now

- CorsixTH/Lua/humanoid_actions/die.lua
> [RDY] Check for lava hole use tile in room

- CorsixTH/Lua/dialogs/confirm_dialog.lua
- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua
- CorsixTH/Lua/dialogs/fullscreen/graphs.lua
- CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
- CorsixTH/Lua/dialogs/furnish_corridor.lua
- CorsixTH/Lua/dialogs/hire_staff.lua
- CorsixTH/Lua/dialogs/information.lua
- CorsixTH/Lua/dialogs/patient.lua
- CorsixTH/Lua/dialogs/place_objects.lua
- CorsixTH/Lua/dialogs/staff_rise.lua
self:registerKeyHandlers was calling the function on the
subclass. Explicitly register on the current class.
Fixes the major issues in #1529 
I haven't yet tested the old save.
> [RDY] Fix edit room hotkeys

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/map.lua
Addressing #1558 with map flags on original TH map
> Correct cell flags for original map

- CorsixTH/Lua/entities/humanoids/patient.lua
Hopefully thisis a suitable refactor as mentioned in #1453
Addresses my comment in #1561 with saved_must_happen not existing, and therefore must_happen not being correctly set.
Patients holding reservations on doors (#1081), reserve_on_resume needs to be copied, as this was not copied to the requeued walk action, the interrupt handler, would not unreserve the door, when interrupting walk action. This is brought about for drinks machine (and would be for falling) as action.keep_reserved is set to true, which bypasses the door unreserve logic.
Then as it wasn't copied, if they were interrupted again, the door would remain reserved.
> [RDY] Fix patient reserving doors

- CorsixTH/Src/th_pathfind.cpp
- CorsixTH/Src/th_pathfind.h
Use new visited flag for tracking nodes not to queue
> [RDY] Idle pathfind regression fix

- CorsixTH/Lua/languages/simplified_chinese.lua
- CorsixTH/Lua/languages/traditional_chinese.lua
Updated and reviewed all strings according to English
> Update Chinese translations

- Dockerfile.build
Tell me if it's useful to you. Thanks!
> Dockerfile added for building corsixth

- LICENSE.txt
- changelog.txt
We should be doing this as we go, but since no one does ....
> Update changelog and LICENSE file

- CorsixTH/Lua/config_finder.lua
- CorsixTH/Lua/room.lua
- CorsixTH/Lua/world.lua
- WindowsInstaller/config_template.txt
> [RDY] Add configurable option for room information dialogs

- CorsixTH/Lua/dialogs/jukebox.lua
> [RFC] UIJukebox prevents save due to persistance error if open at time of save

- CorsixTH/Lua/dialogs/resizables/file_browser.lua
Fixes #518
Are the variable names ok?
> Fix load savegame menu tooltip placements

- README.md
Add the discord link to the homepage readme.md file
> Introduce discord URL

- CorsixTH/Lua/languages/english.lua
Noticed some of my edits were missing their parents. These have been adjusted.
- Adds ``diseases.`` to the diseases edits
- Adds ``room_descriptions.`` to the room edits
> [RDY] Fixes to English.lua

- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/entities/humanoids/patient.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/humanoid_actions/seek_room.lua
- CorsixTH/Lua/rooms/gp.lua
- CorsixTH/Lua/rooms/operating_theatre.lua
- CorsixTH/Lua/rooms/pharmacy.lua
- CorsixTH/Lua/rooms/psych.lua
- CorsixTH/Lua/rooms/research.lua
- CorsixTH/Lua/rooms/training.lua
- CorsixTH/Lua/rooms/ward.lua
- CorsixTH/Lua/world.lua
Both functions used `false` for `0`, else a number. Unified it to using numbers only.
> Use 0 to return lack of room or staff rather than false

- CorsixTH/Lua/dialogs/bottom_panel.lua
Don't rely on savegame version as per @thecycoone comment in #1193 . To be fixed properly at another point
> [RDY] Update hotfix for moneybar

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
- CorsixTH/Lua/hospital.lua
Introduce a way to unconditionally change the reputation (addresses #1623), and clean up a little.
> [rdy] Refactor reputation change

- CorsixTH/Lua/hospital.lua
*Fixes Price distortion todos
- Modifies price distortion based on difficulty level, as suggested in comments.
> [rdy] Modify price distortion on selected difficulty.

- CorsixTH/Lua/config_finder.lua
- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/dialogs/resizables/customise.lua
- CorsixTH/Lua/game_ui.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/languages/english.lua
- CorsixTH/Lua/objects/litter.lua
- CorsixTH/Lua/room.lua
*Fixes #991*
*Fixes #969*
- Adds option to customize dialog to turn on the option to remove destroyed rooms
- Costs twice as much minus some 'scrap' recovery to remove the room.
- Destroyed rooms now reduce hospital value appropriately
> [RDY] Adds option to remove destroyed rooms for a fee

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/entities/humanoids/patient.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
*Reorganizes and cleans up the cured/death code.
> [rdy] Refactor cured died

- CorsixTH/Lua/objects/plant.lua
- Requires the handymen to respect walls. Best seen on L12.
> Handyman can only water plants from inside the hospital

- CorsixTH/Src/th_map.cpp
*Fixes #1742
- We can have only one radiator at a tile, so the code can be simplified.
- While at it, also renamed a few variables and made computations a bit more clear.
> Cleanup temperature update code.

- CorsixTH/Lua/dialogs/resizables/directory_browser.lua
- CorsixTH/Lua/filesystem.lua
- CorsixTH/Src/th_lua_iso.cpp
- Generalises iso to disk images, currently .iso and .dmg.
> [RDY] Allow dmg files as disk images for TH data

- CorsixTH/Lua/dialogs/fullscreen/town_map.lua
- CorsixTH/Lua/game_ui.lua
- CorsixTH/Src/th_map.cpp
- CorsixTH/Src/th_movie.cpp
Also fixes a clang-tidy warning about a variable that is set and never
used.
> [RDY] Use map size rather than hard coded 128 throughout

- .github/workflows/Linux.yml
- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Src/xmi2mid.h
- DoxyGen/animview.doxygen.in
- DoxyGen/corsixth_engine.doxygen.in
- DoxyGen/leveledit.doxygen.in
- DoxyGen/new_footer.html
- LDocGen/templates/page.htlua
- README.md
**Describe what the proposed changes do**
- Removes the date and doxygen version in docs. It means updates to the docs are actual content updates only.
- A few more codespell changes
- Move to Github Actions. There's several ways to do this, eg making more use of other actions for cmake.
> [RDY] Actions - Linux and tests

- CorsixTH/Lua/app.lua
- Ensure the mouse is usable after a crash.
> Free the mouse on crash.

- LevelEdit/README.txt
- LevelEdit/src/com/corsixth/leveledit/Emergency.java
- LevelEdit/src/com/corsixth/leveledit/Gui.java
- LevelEdit/src/com/corsixth/leveledit/StartStaff.java
Level editor crashed on the command line when following the README instructions.
- Use generics where needed.
- Allow startup without icon files.
- Update the README file.
> [rdy] Leveledit fixes

- .github/workflows/Linux.yml
- CorsixTH/CMakeLists.txt
- libs/rnc/CMakeLists.txt
*Fixes #1780*
Use older cmake syntax for add_library in RncLib for compatibility with advertised version.
> [RDY] Fix CMake 3.5 support and verify with CI

- CorsixTH/Lua/entities/machine.lua
Another missed constructor.
- Machine base class is also affected by the objects taking a hospital.
may fix #1782
> [rdy] Adapt Machine constructor to taking a hospital parmameter

- .github/workflows/Linux.yml
- Fixes the current random failures that try to download old versions.
> Add apt get update to Actions linux

- CorsixTH/CMakeLists.txt
- CorsixTH/Lua/api_version.lua
- CorsixTH/Lua/app.lua
- CorsixTH/Lua/graphics.lua
- CorsixTH/Src/config.h.in
- CorsixTH/Src/th_lua.cpp
- Detect the OS - Windows/macOS/Unix. In the future this could look for Android, Wii, whatever needs custom UI?
- Use this to select a default unicode font on macos.
> [RDY] Add default macos font file path

- .github/workflows/Linux.yml
- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/rooms/psych.lua
- Download cmake 3.5 better
- Less duplication in the different jobs
- Adds a test for unwanted tabs, ignoring the language files
Output https://github.com/tobylane/CorsixTH/actions/runs/578805335
> Actions - fix cmake

- AnimView/frmMain.cpp
The scope of the variable 'found' can be reduced.
The scope of the variable 'cont' can be reduced.
Fixes #
**
Reducing the scope of variables, in my opinion, will make the code more readable.
**
*Fixes #*
-
-
-
> The scope of the variable's can be reduced.

- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/entities/humanoids/patient.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
- CorsixTH/Lua/humanoid_actions/seek_room.lua
- CorsixTH/Lua/rooms/operating_theatre.lua
- CorsixTH/Lua/rooms/pharmacy.lua
- CorsixTH/Lua/rooms/psych.lua
- CorsixTH/Lua/rooms/research.lua
- CorsixTH/Lua/rooms/training.lua
- CorsixTH/Lua/rooms/ward.lua
- CorsixTH/Lua/world.lua
- Copies the use of max count from hospital:countPatients into countStaffOfCategory and countRoomOfType
- Use the shortcut everywhere only a minimum staff/room requirement is called for
@Alberth289346 requested this in IRC recently.
> [RDY] Speed up some staff and rooms counts

- check-for-updates
- Add the same check-for-updates file from corsixth.com to corsixth.github.io/CorsixTH.
> Add check-for-updates to github.io

- CorsixTH/Lua/dialogs/place_staff.lua
*Fixes #526*
Previous feedback #1739 
- Rewrite placing staff
- Permit receptionists being put on any tile of a desk
> [RDY] Receptionists can be placed on unstaffed reception desks

- CorsixTH/Lua/entities/humanoid.lua
- CorsixTH/Lua/entities/humanoids/staff.lua
- CorsixTH/Lua/room.lua
- CorsixTH/Lua/rooms/operating_theatre.lua
- CorsixTH/Lua/rooms/research.lua
- CorsixTH/Lua/rooms/ward.lua
- Merge the specific (and slightly different) getStaffMembers from the rooms that extend it into the original in room.
- Use service quality rather than skill or tiredness alone.
> [RDY] Use service quality in picking staff member from multi occupancy rooms

- AnimView/frmMain.cpp
- AnimView/frmSprites.cpp
- AnimView/th.h
Mainly switches from separate layout arguments and ord bitflags to wxSizerFlags, which are clearer, particularly with respect to borders.
Also make some narrowing / sign conversions explicit.
> AnimView tidying

- CorsixTH/Lua/humanoid_actions/die.lua
Die action calculates the use positions of the gates_to_hell using the wrong orientation for the offsets, they should align for the only passable tiles.
Spawn of a gates_to_hell can change the passable flags upon placement/removal since the footprint tile might be in a room. Can walk through a toilet up against a wall or prevent placing an object if the room is being constructed.
> [RDY] Align gates_to_hell use tiles with footprint orientation

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/world.lua
- Use the previous hospitals' policies in the next one when changing level
I always set the policies to the same, regardless of the level. It makes sense to have them reused..
> [RDY] Carry hospital policies to the next hospital

- CorsixTH/Lua/languages/english.lua
The fax message overruns won't overlap with the reply options. Fixes #1663. Changes in bold. Translators should be pointed to the original wording?
Before
> letter[9][2] = "You have proved yourself to be the best hospital administrator in medicine's long and chequered history. Such a momentous achievement cannot go unrewarded, so we would like to offer you the post of Supreme Chief of All Hospitals. **This is an honorary job,** and comes with a salary of $%d. You will be given a tickertape parade, and people will show their appreciation wherever you go.//"
letter[10][2] = "Congratulations on successfully running every hospital we assigned you to. Such a superb performance qualifies you for the freedom of all the world's cities. You are to be given a pension of $%d, **plus a limousine**, …
> [RDY] Shortern the win fax messages to fit in the fax screen

- CMake/CopyVcpkgLua.cmake
- CMake/VcpkgDeps.cmake
- appveyor.yml
- scripts/build_vcpkg_deps.ps1
brotli                                 1.0.9#1
bzip2                                  1.0.8#1
catch2                                 2.13.1#1
ffmpeg                                 4.3.2#12
freetype                               2.10.4
libflac                                1.3.3#5
libmodplug                             0.8.9.0#7
libogg                                 1.3.4#3
libpng                                 1.6.37#14
libvorbis                              1.3.7#1
lpeg                                   1.0.2-1
lua                                    5.4.3#1
luafilesystem                          1.8.0-1
luasec                                 1.0.1
luasocket                              2020-09-14
mpg123                                 1.26.5
openssl …
> [RDY] Bump vcpkg deps and add luasec

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/persistance.lua
*Fixes #1879*
- Write the save game in binary mode, as it was before 1800.
> Write savegames in binary mode

- changelog.txt
Add release notes to changelog, initial drafting. No date input yet.
Feel free to cherrypick/add/adapt as seem fit.
> Add 0.65 release notes

- CorsixTH/Lua/cheats.lua
- CorsixTH/Lua/dialogs/resizables/cheats_dialog.lua
- CorsixTH/Lua/world.lua
Remove wingame's own pausing to not interfere with mustPause()
*Fixes #1897*
> [RDY] Allow win fax to exist

- README.md
*Closes #1884*
- Adds the game's working status to the readme as suggested.
- I tried to show a little humour again (it usually backfires though)
I don't think I wrote it in US English so point out any writing differences.
> [RDY] Working status of game

- .github/workflows/Linux.yml
Fix github action pipeline ... again
> Fix target option for pipeline

- CorsixTH/com.corsixth.corsixth.metainfo.xml
- changelog.txt
> V065 release notes

- README.md
- IRC is dead (for now). Long live Matrix?
> Add Matrix Room to Readme

- check-for-updates
- Copy the legacy check-for-updates file to the new one
http://www.corsixth.com/check-for-updates
> Update check-for-updates file for 0.65

- CorsixTH/Src/th_movie.cpp
*Fixes #1956*
https://wiki.libsdl.org/SDL_AudioSpec#remarks suggests that SDL2 can return 1, 2, 4, or 6 channels.
We're using https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC15 where the documentation says it only returns 1 or 2, but I think it's lying.
> th_movie: Attempt to resample for surround sound

- CorsixTH/Lua/world.lua
- Check the hospital before drawing the dollar.
> Only display dollar sign on local hospital patients

- CorsixTH/Src/th_gfx_sdl.cpp
- Creates scoped_color_mod in th_gfx_sdl.cc to temporarily set an SDL_SetTextureColorMod
- Uses this for the glowing effect to avoid needing to explicitly undo the effect after the draw call.
> Use scoped class to reset SDL_SetTextureColorMod for glowing effect.

- CorsixTH/Src/th_map.cpp
*Fixes dead patients partially overlapped by floor*
- Restores the two pass map rendering with floor tiles first.
- Keeps floor shadows in first pass in order to not regress #1929
Before:
After:
> Restore the two pass map drawing.

- CorsixTH/Lua/entities/machine.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
- Move the announcing function to PlayerHospital
- Add the handymen check per the comment
> Machine repair changes

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
- CorsixTH/Lua/entities/humanoids/patient.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/humanoid_actions/die.lua
- CorsixTH/Lua/research_department.lua
- CorsixTH/Lua/window.lua
- CorsixTH/Lua/world.lua
- Remove or update old comments that don't describe current code
- Remove the opengl section as it can't be true
> Remove old comments, opengl section

- CorsixTH/Src/th_gfx.h
- CorsixTH/Src/th_gfx_sdl.h
- Adds missing documentation of animation effect parameters.
> Document effect and effect_ticks parameters for patient effects.

- CorsixTH/Src/th_movie.cpp
> Fix compile without ffmpeg

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/map.lua
- CorsixTH/com.corsixth.corsixth.metainfo.xml
- changelog.txt
*Fixes release branch of #2004*
- Apply the correct config params for 0.65 release for the All Cures Trophy.
> [RDY] Backport Trophy Fix (0.65)

- CorsixTH/Lua/graphics.lua
Look for a file at`unicode_font`location or the OS specific presets, or warn none of the above were found.
> Improve font file load

- CorsixTH/Lua/entities/humanoids/vip.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
- CorsixTH/Lua/world.lua
- Move vip:announce and the block that calls it to player hospital
> Announce VIP arrival in local hospital only

- CorsixTH/com.corsixth.corsixth.metainfo.xml
- Update screenshot URLs in metainfo to the new images
**Do not merge until corsixth.com points to the new website**
> Update screenshot URLs in metainfo

- .github/workflows/update-website.yml
- Add a workflow for updating the website on a new release
For this to work, a personal access token with the `public_repo` scope is necessary and must be stored as a secret as `WEBSITE_REPO_TOKEN`, [see the details here](https://github.com/marketplace/actions/repository-dispatch#token).
> Add workflow for updating the website

- CorsixTH/Lua/dialogs/bottom_panel.lua
- CorsixTH/Lua/dialogs/fullscreen/research_policy.lua
Reimplements @MarkL1961 's PR #122 as it is still a functional solution.
However, it may need some tweaking as this isn't 100% my area.
Fixes #90
> [RDY] Correct UIResearch Behaviour on demo[2]

- LICENSE.txt
- Adds @alexandre-lavoie to the license, fixes name of @rmnvgr and a few date changes.
> Renew forgotten licenseees

- CorsixTH/CppTest/CMakeLists.txt
- CorsixTH/CppTest/test_th_strings.cpp
- CorsixTH/Src/th_gfx_font.cpp
- CorsixTH/Src/th_strings.h
> Fix // newline handling in freetype font

- CorsixTH/Lua/languages/russian.lua
Translations provided by @Matvey1705
*Closes #2058*
- Also includes tidying
Needs checking I've not made a weird syntax typo somewhere
> [RFC] Update Russian

- CorsixTH/Lua/hospitals/player_hospital.lua
*Fixes #2061*
- Moves advisor checks for loans to end of Day 1 of the month, after all wages etc are paid.
- Fixes a missing `PlayerHospital` entry
> Improve loan advice

- CorsixTH/CMakeLists.txt
- CorsixTH/Lua/config_finder.lua
- CorsixTH/Lua/dialogs/resizables/new_game.lua
- WindowsInstaller/config_template.txt
- scripts/generate_windows_config.lua
- Clarify the comment about the TH folder
- Add direct zoom and campaign header to windows template. Was the campaign part deliberately missing?
- Remove the paragraph about folders as they're above.
> Config changes, generation for Windows Installer

- CorsixTH/Lua/entities/humanoids/patient.lua
*Fixes #2014 
As suggested by @TheCycoONE , add checks for a hospital, for safety that includes unused parcels as well.
Not sure the latter is necessary.
> Improve pee and vomit conditions.

- CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
> Add scroll keys back to hotkey panel

- CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
Now updates buttons immediately when resetting hotkeys
Fixes #2105
> Fix regression in resetting hotkeys

- CorsixTH/Lua/hospital.lua
*Fixes #2098*
- Assign correct disease to emergency fax
> [RDY] Assign correct disease to emergency fax

- CorsixTH/Lua/entities/humanoids/patient.lua
Reverts CorsixTH/CorsixTH#2117
> Revert "[WIP] Fix dynamic info updates during epidemics"

- CorsixTH/Lua/languages/german.lua
Fixes #2054 
Currently a draft; it contains some comments that have to be removed.
> Update German translation

- CorsixTH/Lua/entities/humanoids/patient.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/languages/english.lua
- CorsixTH/Lua/rooms/gp.lua
- CorsixTH/Lua/rooms/operating_theatre.lua
- CorsixTH/Lua/rooms/pharmacy.lua
- CorsixTH/Lua/rooms/psych.lua
- CorsixTH/Lua/rooms/research.lua
- CorsixTH/Lua/rooms/training.lua
- CorsixTH/Lua/rooms/ward.lua
- CorsixTH/Lua/world.lua
- Add advice about adding to a full training room
- Remaining advice about the local hospital is made player only
> Local hospital advice 2

- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
- CorsixTH/Lua/humanoid_actions/seek_room.lua
- Move faxes relating to emergencies, VIPs and missing rooms to PlayerHospital
- Apply minor consistent style
> [RDY] Move faxes to player hospital

- CorsixTH/Lua/dialogs/fullscreen/graphs.lua
*Fixes # None*
- gap between grid and vertical ticks
- align ticks and labels
- 4 year graph keeps first tick at 0 in the first 4 years
- tracks game month to update when open during a month
- navigate month -> year -> 4 yr instead of month -> 4 yr -> yr
> [RDY] Charts dialog updates on new month and changes scale in correct order

- CorsixTH/Src/main.cpp
- libs/whereami/whereami.c
*Fixes #2057*
- Flip the comparison that caused the problem. Thanks Cyco!
- Update whereami. I'm not qualified to judge this, I note that OpenBSD support is now included https://github.com/gpakosz/whereami/commits/master
> Portable app/whereami fix

- CorsixTH/Lua/hospital.lua
- Correct a spelling error in Hospital:findReceptionDesks which prevents patient spawning
> Fix comparison in finding reception desks

- CorsixTH/Lua/entities/humanoids/staff.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
- CorsixTH/Lua/humanoid_actions/seek_room.lua
- Only remove faxes (ui) of local patients/staff.
> Only remove fax messages relating to local humanoids

- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/entities/humanoids/staff/doctor.lua
- CorsixTH/Lua/entities/humanoids/vip.lua
- CorsixTH/Lua/entities/machine.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
- CorsixTH/Lua/research_department.lua
- Separate the VIP end fax into a PlayerHospital function
- Make more advice local hospital only
- Make machines use the local research progress
> Local hospital advice 3

- README.md
- changelog.txt
- Changelog commit for 0.66
- Amends readme
> 0.66 Changelog

- LICENSE.txt
Update the license file.
Adding the new users that I didn't get names from to this PR so they can suggest different attribution if desired.
Ping:
@RetroGamerFan 
@TotalCaesar659 
@Tomracer 
@Manuel-K
> License 2022

- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/world.lua
*Fixes #2173*
- Remove the extra ".hospital" from my recent change.
> Fix advice call in boiler repair

- CorsixTH/Lua/entities/humanoids/patient.lua
This PR does not effectively fix anything current, but may prevent some cases in previous issues where a fed up patient leaving mid-consult/treatment could cause a bad state.
I also think it is more humanistic to take the treatment if you're already in the room (even if you felt fed up).
- Checks if a patient is in their cure room before deciding to leave
- Formatting for some comments
- Removal of a completed TODO
- `TODO clean up this block, nonmagical numbers` not implemented, left as is.
> Avert fed up state if in cure room

- changelog.txt
- Finalises updates to the changelog for release.
> Update changelog for 0.66 (final)

- CorsixTH/Lua/entities/humanoids/patient.lua
> Fix typos from 2189

- CorsixTH/Lua/audio.lua
- CorsixTH/Lua/config_finder.lua
- CorsixTH/Lua/dialogs/confirm_dialog.lua
- CorsixTH/Lua/dialogs/menu.lua
- CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua
- CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua
- CorsixTH/Lua/entities/humanoids/patient.lua
- CorsixTH/Lua/entities/humanoids/staff/doctor.lua
- CorsixTH/Lua/entities/humanoids/vip.lua
- CorsixTH/Lua/filesystem.lua
- CorsixTH/Lua/graphics.lua
- CorsixTH/Lua/map.lua
- CorsixTH/Lua/sprite_viewer.lua
- CorsixTH/Lua/string_extensions.lua
- CorsixTH/Lua/strings.lua
- CorsixTH/Lua/world.lua
Fixing style issues.
For people that love PEG, please fix `string_extensions.lua`. (EDIT: Reason: Operator priority between parameter-less function application and other operators is not defined. Also, argument processing of such functions is not consistent. Therefore I don't know what the code means.)
Perhaps alternatively, use native string matching. It exists in lua 5.1 .
> Add missing parentheses, fix 2 style problems.

- .luacheckrc
- CorsixTH/Lua/app.lua
Add Triangular distribution function.
> Add Triangular disitrbution function.

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/date.lua
- CorsixTH/Lua/dialogs/bottom_panel.lua
- CorsixTH/Lua/dialogs/edit_room.lua
- CorsixTH/Lua/world.lua
Move some data and code out of world.
> Cleanup world

- CorsixTH/Lua/humanoid_actions/seek_room.lua
Just a starting note -- I am not good with the action queue, so likely this change is a little cautious or not optimal?
- Fixes the issue where the GP chose a specific diagnosis room for the patient, then the action queue threw that out the window.
- Seek room action now obeys the GP's requested diagnosis room for the patient, if that room is available
- Some additional comments added
> Obey GP's Diagnosis Room Choice

- CorsixTH/Levels/example.level
- Changes `example.level` from MIT license to CC BY 4.0 license
- As per discord/matrix conservation and email chain with Lego/@thecycoone
I'll close this if @Lego3 needs to personally make this change.
> Update example level license

- CorsixTH/Lua/humanoid_actions/meander.lua
* Fixes an indentation problem found by @lewri 
- Makes code more readable.
> Fix meander-code indentation (found by Lewri)

- CorsixTH/Lua/research_department.lua
*Fixes #230* (or at least should assist in it, but from my testing it seems like there may have been other changes over the years)
It's worth pointing out that we only select a new drug for improvement if we reduce the drug's cost. ~~This is probably wrong and happy to fix it if needed now (or will put in another PR)~~. Now added
- Reverts to an original-like drug improvement cycle as per @mugmuggy's findings (see 230)
- Doesn't try to fix anything that leads up to the `improveDrug` function.
- Uses proper minimum drug cost from level files
- Fixes chance of negative drug costs
Some things to note, not fixed here:
- Once all drug effectivenesses hit 100%, no more improvements can be made (this includes cost reductions)
- Changes to machine …
> Refactor improveDrug

- CorsixTH/Lua/diseases/serious_radiation.lua
*Fixes #2258*
- Disables Serious Radiation from being a contagious disease
- This means it cannot be the cause of a new epidemic
- And other contagious diseases cannot be passed onto patients with Serious Radiation.
> Serious radiation should not be a contagious disease

- CorsixTH/Lua/languages/english.lua
*Fixes #2250*
- Removes the references to now the obscure IRC, Mailing List and Forums.
- Replaces references above with information about contacting via Discord, Sub-Reddit or Matrix.
> PR - Removal of IRC, Mailing List and Forum references. Addition of Discord, Reddit and Matrix references.

- CorsixTH/Lua/languages/simplified_chinese.lua
- CorsixTH/Lua/languages/traditional_chinese.lua
- LICENSE.txt
- add new texts
- add fax.vip_visit_result compatibility mapping
- revise old texts
> update language files - simplified and traditional Chineses

- CorsixTH/Lua/humanoid_actions/multi_use_object.lua
- CorsixTH/Lua/humanoid_actions/use_object.lua
Refactor humanoid use-object tile-speed into a separate function and cleanup.
Complete patch is a move with modifications, not quite readable. Patch however takes many small steps so reading those may be preferred.
> Refactor use object tilespeed

- CorsixTH/Lua/dialogs/resizables/main_menu.lua
- CorsixTH/Lua/dialogs/resizables/options.lua
- CorsixTH/Lua/languages/czech.lua
- CorsixTH/Lua/languages/english.lua
*Fixes #2274*
- Adds toggle
- Adds alert when updates disabled on main menu
> Check for updates menu option

- CorsixTH/Lua/world.lua
- Moves the spawn rate modifier to become a bonus rather than just a static pool.
- Adds todo note about how updateSpawnDates() is to be adjusted ( #1986 )
- This modifier will likely need to change location when spawn changes include the AIHospital proper.
> Properly apply Roujin's challenge

- CorsixTH/Lua/objects/reception_desk.lua
- Attempts to make the tick function easier to read at the cost of increased length.
> Refactor ReceptionDesk:tick()

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/world.lua
*Fixes #*
- Append date to top of gamelog output
- This may be more useful in future, if we ever wanted to 'append' new gamelog entries to the file rather than overwriting it (though this could lead to bloat)
> Add date to gamelog

- .github/ISSUE_TEMPLATE/feature_request.yml
Noticed an error to the release page in the feature request template
> Fix releases link in feature request template

- CorsixTH/Src/th_movie.cpp
- CorsixTH/Src/th_movie.h
> Use ffmpeg 5.1 new channel layout api

- README.md
Add the badge for the new test
> Add GHA Windows status badge

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/config_finder.lua
- WindowsInstaller/config_template.txt
Pull of commits from #2273 due to broken tree.
Segment of #2209 (aka the easy bit)
- Initialises the campaigns directory on launch and adds it as a config line.
- Encompasses part of the prepwork for CommunityContent.
> Init Campaigns Directory (fixed)

- CorsixTH/Lua/room.lua
*Fixes #2325*
- Adds a safeguard for the `staffWaitToggle` call in `commandEnteringPatient`
NB: I could well merge the new private function into `_StaffWaitToggle` but is may creep the scope of the function. Then again we do like functions exiting early.
> Safeguard staffWaitToggle for entering patients

- CorsixTH/Lua/humanoid_actions/seek_reception.lua
- CorsixTH/Lua/humanoid_actions/spawn.lua
> Cleanup seek reception

- LICENSE.txt
Refresh license with any relevant commits.
> Bump License

- CorsixTH/Lua/world.lua
Remove suppression of warning added in previous PR #2346
> Remove luacheck warning 582

- changelog.txt
New changelog. There's a TODO for packager notes I need Cyco to advise on ; and what #2191 lets someone do (if anything).
> 0.67 Changelog

- CorsixTH/Lua/app.lua
*Fixes #2338*
- Ensures EA App installs are detected by the game
- I haven't removed the Origin folder for backwards compatibility with older sources
> [rdy] Add EA App TH Directory

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
- CorsixTH/Lua/dialogs/fullscreen/bank_manager.lua
- CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua
- CorsixTH/Lua/dialogs/fullscreen/fax.lua
- CorsixTH/Lua/dialogs/fullscreen/graphs.lua
- CorsixTH/Lua/dialogs/fullscreen/hospital_policy.lua
- CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
- CorsixTH/Lua/dialogs/fullscreen/research_policy.lua
- CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
- CorsixTH/Lua/dialogs/fullscreen/town_map.lua
- CorsixTH/Lua/graphics.lua
- CorsixTH/Lua/ui.lua
loadRaw was not saving the palette transparency flag leading to some mismatches depending on load order.
> Fixes at least some cases of #2308

- changelog.txt
Updates changelog for final release
Feel free to hold this back until we are almost ready to release
> Add final changelog amendments

- check-for-updates
*Fixes the 'check-for-updates' file.
- Update the check file for CorsixTH 0.67-
> Update 'check-for-updates' for CorsixTH 0.67

- CorsixTH/Lua/world.lua
- Removes the generally undesired repeat until loop
- Adds doc
I'm not convinced the "nearest" declaration is actually needed really except for clarity to where function calls are.
> Refactor World:findRoomNear

- CorsixTH/Lua/api_version.lua
- CorsixTH/Lua/filesystem.lua
- CorsixTH/Lua/movie_player.lua
- CorsixTH/Src/iso_fs.cpp
- CorsixTH/Src/iso_fs.h
- CorsixTH/Src/th_lua_iso.cpp
If you are playing with an ISO hosp directory you can now have in game movies!
> Movies in ISOs

- .github/workflows/Linux.yml
- CorsixTH/Lua/entities/humanoids/patient.lua
- CorsixTH/Lua/languages/spanish.lua
*Fixes #*
- Replace the two tabs with spaces
- Fix the check for tabs, include language files
> Fix tabs and tabs check

- CorsixTH/Lua/epidemic.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
*Fixes #2434*
- Add the sound of marking a patient for vaccination.
> Add vaccinate sound for epidemics

- .github/workflows/Linux.yml
- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/languages/danish.lua
- CorsixTH/Lua/languages/finnish.lua
- CorsixTH/Lua/languages/norwegian.lua
- CorsixTH/Lua/languages/simplified_chinese.lua
- CorsixTH/Lua/languages/traditional_chinese.lua
- CorsixTH/Lua/persistance.lua
- CorsixTH/Lua/utility.lua
- CorsixTH/Src/th_map.h
- LICENSE.txt
- README.md
- changelog.txt
- libs/rnc/rnc.cpp
*Fixes #*
- Add the spelling corrections from the latest codespell version
- Update codespell
- Add a temporary block on this check failing the run
The RNC licence ends with the word software, after that it's a standard comment we can edit.
> Codespell changes, update codespell

- DoxyGen/animview.doxygen.in
- DoxyGen/corsixth_engine.doxygen.in
- DoxyGen/leveledit.doxygen.in
Fix the warning texts in Appveyor
> Fix doxygen warnings

- .github/workflows/Linux.yml
- WindowsInstaller/config_template.txt
*Fixes #2451*
- Update tools
- Fix the check for tabs
- Spellcheck changes. To avoid needing to rebase all current PRs, it won't fail the run. I will remove this later
- Clang format's errors won't stop clang tidy from running
- Add a check that the windows config file is up to date
The new output is https://github.com/tobylane/CorsixTH/actions/runs/6840811854/job/18600472930#step:10:34
> Actions for Linux updates

- CorsixTH/Src/th_gfx_sdl.cpp
*Fixes #*
- Sets the minimum window size in SDL, to prevent resizing the window smaller than the lua limit.
> Set minimum window size

- CMake/VcpkgDeps.cmake
- CMakeLists.txt
- The vcpkg cmake script uses the correct Animview variable
- A comment uses the Animview name
> Fix references to AnimView

- CorsixTH/Lua/dialogs/resizables/options.lua
- CorsixTH/Lua/languages/english.lua
*Fixes #2462*
- Put half of the options in a second column
- Make the window wider, adjust the title and back button
- Add button for jukebox
> Make two columns of options in the options dialog

- CorsixTH/CorsixTH.lua
- Remove the ipairs function as lua ipairs was never deprecated (corsix's blog says it was in a beta)
- Rewrite the lua version check, including mentioning 5.4
- Combine the two parts of start debugging. Was this separate for a reason?
> Tidy root CorsixTH.lua

- CorsixTH/Src/th_map.cpp
The adjacency matrix calculation, which is responsible for working out which plots are should be available for purchasing, looks to be off by an index due to the way the pointer is incremented prior to performing the test. This results in undefined behaviour when testing the edge of the map tiles. It's probably never been noticed because there's many tiles per parcel.
I've rewritten this to use some of the existing methods to get map tiles rather than pointer magic, which might be a tad slower but as this code is infrequently run, I think the trade-off for readability is worth it.
I've tested this change with all the original campaign levels, and they seem to be purchasable in the order I'd expect.
> [RFC] Fix array indexing out of bounds in parcel adjacency calculation

- CorsixTH/Lua/app.lua
*Fixes #2011*
- Add a semver function to compare three segment version numbers in the check for updates.
> Add semantic version comparison for updates

- CorsixTH/Src/th_movie.cpp
- CorsixTH/Src/th_movie.h
> Disable audio in movies when there are no channels

- CorsixTH/Lua/api_version.lua
- CorsixTH/Lua/app.lua
- CorsixTH/Lua/world.lua
- CorsixTH/Src/lua_sdl.h
*Fixes #1494*
- Add the new tick rates mugmuggy researched in #1494 
- Bump api and savegame versions, restore previous speed
> Adjust game speed and ticks

- CorsixTH/Lua/cheats.lua
- CorsixTH/Lua/dialogs/resizables/cheats_dialog.lua
- CorsixTH/Lua/hospital.lua
- CorsixTH/Lua/hospitals/player_hospital.lua
- CorsixTH/Lua/languages/english.lua
**New cheats**
- Toggle earthquakes in the world
- Toggle epidemics in the hospital
- Set death counts to zero
- Set reputation to the maximum
> Add cheats to ingame menu

- CorsixTH/Lua/ui.lua
> Fix pink briefing in old saves

- CorsixTH/Lua/cheats.lua
- CorsixTH/Lua/languages/english.lua
*Fixes #2515*
- Revert the function name changes of [d81b32](https://github.com/CorsixTH/CorsixTH/pull/1997/commits/d81b32c69b4a6332ee071398674d6445eb9b1a37).
> Undo cheat function rename

- CorsixTH/Lua/app.lua
> Add missed loadLevel function param reorder

- CorsixTH/Lua/dialogs/menu.lua
- Players can clear field, without leaving map editor and opening the map editor again
- Added options to map editor
- Players can overlay on map like v0.30 map editor (flags, parcel, positions) in options
_Edit: Added by tobylane:_
- _Refector common parts of the menu_
- _Add music controls to the map editor_
> Map editor menu improvement and refactoring

- CorsixTH/Lua/humanoid_actions/use_object.lua
- CorsixTH/Lua/map.lua
- The empty if branches are reversed. This is ignored by luacheck, it's an optional change. Map.lua is easier to read without whitespace changes - https://github.com/CorsixTH/CorsixTH/pull/2337/files?w=1
> Rewrite empty if branches

- CorsixTH/Lua/languages/italian.lua
- LICENSE.txt
- Updates to the Italian translation, submitted by @Inkub0 in #2547.
> Italian translation update

- CorsixTH/Lua/dialogs/menu.lua
*Fixes #2549*
- Check for audio when adding audio menu items.
> Fix check for audio in menus

- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/cheats.lua
- CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
- CorsixTH/Lua/dialogs/patient.lua
- CorsixTH/Lua/dialogs/staff_dialog.lua
- CorsixTH/Lua/entities/humanoid.lua
- CorsixTH/Lua/entities/humanoids/patient.lua
- CorsixTH/Lua/entities/humanoids/staff.lua
- CorsixTH/Lua/entities/humanoids/staff/doctor.lua
- CorsixTH/Lua/entities/humanoids/staff/handyman.lua
- CorsixTH/Lua/entities/humanoids/vip.lua
- CorsixTH/Lua/humanoid_actions/use_staffroom.lua
- CorsixTH/Lua/rooms/electrolysis.lua
- CorsixTH/Lua/rooms/gp.lua
- ~~Staff fatigue can be nil, [see mugmuggy's comment](https://github.com/CorsixTH/CorsixTH/issues/1924#issuecomment-860139913). Check the staff member has fatigue before accessing it, or use zero in its place.~~
- Add a function to get a humanoid's attribute, or the given default value, or 0.
> Add a function to get humanoid attribute values

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/entities/humanoids/staff.lua
- CorsixTH/Lua/room.lua
- The calculation for happiness from windows and space was done per staff per day, now it is done on room finish and once after load.
> Refactor staff happiness calculation

- CorsixTH/Lua/languages/italian.lua
**update of Italian translation**
> Update italian translation

- .github/workflows/Linux.yml
- Upgrade the checkout step that has a deprecated warning
> Upgrade linux actions checkout

- CorsixTH/Lua/config_finder.lua
- WindowsInstaller/config_template.txt
Fixes #2456
(I think this is one I planned to add if nobody else picked it up before next release but could be wrong)
- Add warning to the config setting
> Add warning for graphics config setting

- CorsixTH/Lua/app.lua
- Adds game directory location for new GOG Galaxy downloads of TH
> Add GOG Galaxy support

- CorsixTH/Lua/languages/dutch.lua
- Removed two deleted keys
- Added missing translations
> Include missing Dutch translation keys

- CorsixTH/Lua/dialogs/resizables/map_editor.lua
- Add the hotkeys the game has to the map editor.
> Add map editor hotkeys

- CorsixTH/Lua/languages/russian.lua
- Fixes some mistakes
- Translates strings that were added in newer commits
> Updating russian strings

- LICENSE.txt
Refresh copyright list
I also inserted spaces between the commas but I can revert that if copyright years aren't meant to be spaced.
> Copyrights 2024

- CorsixTH/Lua/languages/italian.lua
updated Italian translation, correct spelling
> updated Italian translation, correct spelling

- .github/ISSUE_TEMPLATE/bug_report.yml
For merging after pushing Beta 1
> Add next version experiments

- CorsixTH/Lua/dialogs/resizables/options.lua
- Fixes language tooltip position in options
> Language tooltip position fix

- CorsixTH/Lua/app.lua
- CorsixTH/com.corsixth.corsixth.metainfo.xml
- CorsixTH/corsix-th.6
- LICENSE.txt
- WindowsInstaller/Win32Script.nsi
- changelog.txt
Awaiting decision on if this will be Beta 2 or RC 1 (and a suitable period of test time)
> Prep for next prerelease

- check-for-updates
Publish release to update file. Adjust the changelog text if needed.
> Publish release to update file

- CorsixTH/Lua/entities/humanoids/patient.lua
> Fix stuff not being able to be picked up while falling actions is active

- CorsixTH/Lua/languages/dutch.lua
*Fixes #*
Out of date dutch string
> Updated change save_to_temp translation for the dutch language

- CorsixTH/Lua/room.lua
*Fixes #2663* (Lua error on room delete when machine window open)
-
- On enter room edit mode If we have the window for this room machine open, then close it.
-
> #2663 Fix for 'Lua error on room delete when machine window open'

- CorsixTH/Lua/dialogs/fullscreen/town_map.lua
-  If free build is enabled, town map displays 0$ heating bills and 0$ parcel cost.
> Free build improvements in town map

- CorsixTH/Lua/dialogs/furnish_corridor.lua
- Increases buy object limit from 99 to 100, to match original TH behavior
> Increase buy object limit

- CorsixTH/Lua/dialogs/furnish_corridor.lua
This reverts commit 183d3edb4fdf059ccac910414d9cd91e7bd2763e.
> Revert "Increase object limit"

- CorsixTH/Lua/entities/machine.lua
- CorsixTH/Lua/objects/door.lua
- CorsixTH/Lua/room.lua
*Fixes #2622*
-
- Fixed bug when Machine strength and room stats reset on room edit.
-
> #2622 fix bug: room stats reset on room edit

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/staff_dialog.lua
- CorsixTH/Lua/entities/humanoids/staff.lua
*Fixes #2632 #2651*
- PickupAction can be setNextAction only once.
> Prevent staff grab spamming

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
- CorsixTH/Lua/endconditions.lua
- These improvements are preparation for adding new criteria, and won't have any impact yet. The additional commits in my [addcriteria](https://github.com/CorsixTH/CorsixTH/compare/master...tobylane:CorsixTH:addcriteria) branch use the first, third and fifth commits here.
> End condtions and progress report dialog improvements

- CorsixTH/Lua/endconditions.lua
*Fixes the main part of #2670*
- End game check for balance includes the loan value.
> Fix end condition check for hospital balance

- CorsixTH/Lua/languages/french.lua
*Fixes some french cheats' text being too long for the cheats window.*
Submitted on behalf of @Sanndow
> Shorten French cheat strings

- CorsixTH/Lua/config_finder.lua
- CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
- CorsixTH/Lua/game_ui.lua
- CorsixTH/Lua/languages/english.lua
*Fixes #2720*
- Add a toggle transparent walls hotkey with the default as shift x.
> Add hotkey for toggle wall transparency

- CorsixTH/Src/th_gfx_sdl.cpp
*Fixes #2744
(or at least improves it :p )
`(R + G + B) / 3` is a silly way to compute color intensity. This patch improves that by doing a more proper calculation.
Result:
* `master` sprite font: 
* `master` ttf font: 
* `patch` ttf font: 
As the used ttf font is less heavy, it still looks different, but the colour seems much better.
> Compute proper intensity of the text sprite pixels for constructing a TTF text colour.

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/fullscreen/fax.lua
- CorsixTH/Lua/dialogs/menu.lua
- CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua
- CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua
- CorsixTH/Lua/dialogs/resizables/new_game.lua
- CorsixTH/Lua/world.lua
*Fixes #2627*
-
- Only single fix for this:
- `'free_build_mode' should not apply to any of the campaign maps.`
- without refactoring and extracting 'free_build_mode' from config.txt
- which will be good to implement, but for now only bugfix.
-
> #2627 fix: 'free_build_mode' param affecting campaign maps.

- CorsixTH/Lua/world.lua
Avoid waiting for next game hour to adjust to speed changes.
Fixes #2758
> Instant speed changes

- CorsixTH/Lua/world.lua
- Changes repeat loop to a while loop
In general I think the `return` definition might be wrong in the function overall but not confident.
> Replace calculateSpawnTiles repeat loop

- CorsixTH/Lua/dialogs/fullscreen/town_map.lua
> free_build heating fix

- CorsixTH/Lua/endconditions.lua
The current progress report dialog's chart column height calculation.is better, this is now used in judging which lose criteria to include in the chart.
The change looks a bit better when ignoring whitespace, https://github.com/CorsixTH/CorsixTH/compare/master...tobylane:CorsixTH:chartprogress?w=1
> Measure goal progress better in the progress report

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/languages/english.lua
*Fixes #2798*
- Add the missing string from 2798
- Fix campaign restarts where the full paths aren't known
- Improve docs on app loadlevel
> Fix restarting saves from custom campaigns

- CorsixTH/Lua/dialogs/bottom_panel.lua
- CorsixTH/Lua/dialogs/machine_dialog.lua
> Show dynamic info for machine menu

- CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
- CorsixTH/Lua/hospital.lua
*Implements #2230*
Annual report fixes:
- Reseting `_ty` ("this year") each year.
- For medical-related awards and trophies check is the any actually patient cured.
> Don't give away awards so easily

- CorsixTH/Lua/entities/humanoids/staff.lua
- CorsixTH/Lua/entities/humanoids/staff/doctor.lua
- CorsixTH/Lua/humanoid_actions/pickup.lua
*Expected that will be fixed and are no longer reproducible: #1249, #1933*
Part of the Operating Theatre META #2809 (task **x101**)
-
- On a pickup surgeon from the operating room, remove his surgical gown.
> On pickup surgeon remove surgical gown

- CorsixTH/Lua/app.lua
- CorsixTH/Lua/dialogs/fullscreen/fax.lua
- CorsixTH/Lua/languages/english.lua
- CorsixTH/Lua/world.lua
*Fixes #2821 and a bug Argamx reported in discord*
- Fix custom game restarts. Handles TH map files, moved CTH levels and maps, gives a detailed error message if it still can't find files.
> Fix campaign restart 2

- CorsixTH/Lua/rooms/operating_theatre.lua
*Fixes #1244*
Part of the Operating Theatre META #2809 (task **x104**)
-
- removed 'Resume operation if already ongoing' functionality.
> Operation Theatre. Remove resume surgery operation

- CorsixTH/Lua/entities/humanoid.lua
- CorsixTH/Lua/humanoid_action.lua
- CorsixTH/Lua/humanoid_actions/use_object.lua
- CorsixTH/Lua/rooms/operating_theatre.lua
*Fixes #2664*
Part of the Operating Theatre META #2809 (task **x102**)
-
- Prevent pickup surgeon during surgery operation.
> Operation Theatre. Prevent pickup surgeon during surgery operation

- CorsixTH/Lua/objects/cabinet.lua
Addresses #2794 
- Fix marker for when dr uses cabinet
> Fix cabinet staff marker

- CorsixTH/Lua/rooms/operating_theatre.lua
> Fix pick up surgeon skips hand washing

- CorsixTH/Lua/graphics.lua
*Fixes #2848*
- Moves the `math.floor` operation until pixel positions are calculated
- Small refactor to accommodate repeated set of marker in frame
- Added a minimal assertion check with a hopefully helpful error message.
[screen-recording(10).webm](https://github.com/user-attachments/assets/e6c195a2-3351-4fd7-8266-435a77fba53c)
> Fix Linear Interpolation for markers

- CorsixTH/Lua/objects/comfortable_chair.lua
Reduced comfy chair glitches!
Test saves also run.
Addresses #2794
> Fix moods of the comfortable chair.

- CorsixTH/Lua/dialogs/place_staff.lua
In CTH If you click Esc while placing a new employee, the hiring will cancel but you still will hear the placement sound.
In original TH there is no any sound in this case.
This PR removes placement sound in CTH for this case.
> Dont play drop sound on cancel hire

- .github/workflows/Windows.yml
- Use regular Actions caching, as the caching in lukka/run-cmake is broken. When that is fixed, this commit could be reverted.
> Fix Windows Actions caching

- CorsixTH/Src/config.h.in
- CorsixTH/Src/th_lua_map.cpp
- CorsixTH/Src/th_lua_ui.cpp
- CorsixTH/Src/th_map.cpp
- CorsixTH/Src/th_map.h
- Improve name of two 'block' map class variables.
- Eliminate magic constant block array indices.
- Further smaller improvements.
> Refactor th map cpp

- CorsixTH/Lua/dialogs/place_staff.lua
Fixes #2881
Regression introduced in #2877
> Fix place staff regression

- CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua
- CorsixTH/Lua/world.lua
*Fixes #2600*
- Fix the map editor check for path finding, credit to Lewri
- Fix the path used for loading maps
> Fix map editor load and save

- CorsixTH/Lua/world.lua
- Show the correct level praise in the win fax. A regression from my campaign folders pr.
> Load correct level end praise

- CorsixTH/com.corsixth.corsixth.metainfo.xml
- changelog.txt
<del>TODO: Still add the changelog to the metainfo file</del>
TODO: @TheCycoONE to add additional packager notes
> 0.69.0 Beta 1 changelog

- CorsixTH/Src/th_gfx.cpp
- Allow a random choice of one of two sounds to be played with a frame of an animation.
- Add sounds to frames of various vomit animations.
> Allow one or two sounds to be played with an animation frame

- LICENSE.txt
Add pizzadepollo, a Non-Github based contributor for translations.
> Add missed contributor

- CorsixTH/com.corsixth.corsixth.metainfo.xml
- changelog.txt
> 0.69.0 Beta 2 changelog

- CorsixTH/com.corsixth.corsixth.metainfo.xml
- LICENSE.txt
- changelog.txt
> Refresh 0.69.0 rc1 changelog

- .github/workflows/WindowsInstaller.yml
- This reverts commit c46b5095fd335607b7c74b84dae083b27879b53d.
> Revert "Download Noto font and include in Windows installer"

- CorsixTH/Lua/app.lua
**Merge only after release is published**
- Allocate the 10 savegame version reserve for patches.
> Savegame bump post-release

- CorsixTH/Src/th_map.cpp
- CorsixTH/Src/th_map.h
Refactor the current rendering code.
The complete patch seems non-readable, but each commit should be doable.
> Refactor rendering

- .github/workflows/Linux.yml
- CMakePresets.json
- First CI job is lua 5.1 installed by apt-get, then code tests and docs
- Second CI job is lua 5.4 installed by vcpkg, then clang tests
- Add the minimum to cmake presets to make this possible
Outputs https://github.com/tobylane/CorsixTH/actions/runs/16246232477/job/45870041719 and https://github.com/tobylane/CorsixTH/actions/runs/16246232477/job/45870041687
> Linux Actions - add vcpkg

- CorsixTH/Lua/entities/humanoids/staff.lua
*Fixes #2954*
- Before extracting elements from an array by index, a check has been added to ensure that there are enough elements.
> Hotfix room crash on placing staff

- CorsixTH/Src/persist_lua.cpp
This is a small one; just fixes the encapsulation, improves the comments, and I hope makes it slightly more readable.
> Minor cleanup load_multi_buffer

- CorsixTH/Lua/dialogs/place_staff.lua
> Regressed crash on cancel grab after room exploded fix

- CorsixTH/Lua/calls_dispatcher.lua
- CorsixTH/Lua/entities/machine.lua
*Fixes #2949 *
- Fixes an issue where the repair machine icon will not show despite clicking the "Page Handyman" button
> Fix bug where the repair machine icon would not show

- CorsixTH/Lua/languages/french.lua
Added missing French translations for the machine menu.
*Fixes #*
Added missing French translations for the machine menu.
-
-
-
> Update french.lua -- Add French translations for the machine menu

- CorsixTH/Lua/api_version.lua
- CorsixTH/Src/th_gfx.h
- CorsixTH/Src/th_gfx_sdl.cpp
- CorsixTH/Src/th_gfx_sdl.h
- CorsixTH/Src/th_lua_gfx.cpp
Some refactoring I did while working on the movie text. The rest of my PR isn't useful anymore but I figured it was worth saving these changes.
> render_target RAII
