CorsixTH/CorsixTH

CorsixTH/Lua/app.lua
While updating the "update checker latest version" on our web page I noticed that there was a small error in the code. This part is usually only run if someone is trying to do a middle-man attack, which is probably why we haven't noticed the error before.
=> Fixed small spelling mistake in the update checker

AnimView/frmSprites.cpp, AnimView/frmSprites.h
AnimViewer sprite display missed a vertical scrollbar, which made viewing the contents of bigger sprite files somewhat challenging.
Together with sadger, I hacked a scrollbar sub-window into the application.
It's not the most beautiful piece of work, as it decides on the scrollbar size while drawing. However, it does the job, would seems sufficient for now.
=> Add vertical scrollbar to the Animviewer sprite display.

WindowsInstaller/Win32Script.nsi
With SDL2 we should move to one executable imo. Then we would update the installer like this.
=> Updated Windows installer to only take into account one executable

CorsixTH/Src/th_movie.cpp
Without this change, clang emits these compile time warnings with `-Wall` turned on.
```
/home/pwaller/.local/src/CorsixTH/CorsixTH/Src/th_movie.cpp:305:5: warning: field 'iCount' will be initialized after field 'm_pFirstPacket' [-Wreorder]
iCount(0),
^
/home/pwaller/.local/src/CorsixTH/CorsixTH/Src/th_movie.cpp:409:5: warning: field 'm_pVideoThread' will be initialized after field 'm_pAudioPacket' [-Wreorder]
m_pVideoThread(NULL),
^
2 warnings generated.
```
=> Fix field ordering warnings from clang

CorsixTH/Src/sdl_core.cpp
When using my own SDL2 build, it was failing and CorsixTH did not show the
reason why.
=> Show SDL_Init failure reason

CorsixTH/Src/th_sound.cpp
This function's loop for parsing a WAV file would crash CorsixTH by
getting stuck in an infinite loop because this loop has no end condition
and none of its break statements were executed.
Each language TH supports has its own sound effects stored in
SOUND-X.dat. This error would occur for LAVA004.WAV (182) in:
*SOUND-1.dat (CD distribution)
*SOUND-5.dat (gog.com TH distribution)
I've simply inserted a break statement after this loop's variable
assignment statement for the last duration calculation variable it
parses.
I've tested this with the SOUND-5.dat from the gog.com distribution but
I've not tested this with the SOUND-1.dat from @Sigzegv 's TH CD.
=> Fixed th_sound:getSoundDuration(index) crash error:#588

CorsixTH/Lua/dialogs/staff_rise.lua
Fixes #605. Old saves did not include that font.
=> Load black_font if it doesn't exist in staff_rise.lua

CorsixTH/Src/th_gfx_sdl.cpp
Alternative solution to #629, fixes #646
=> Special handling of empty SDL clip regions

.travis.yml
This pull request updates the FFMpeg version used at the Travis building system to a much newer version.
=> Travis: update FFMpeg to 2.5.2

.travis.yml
Sadly the makefiles for luafilesytem and lpeg didn't consider cross compiling with mingw so I had to do the compiling myself.  luasockets did have mingw support in it's makefile so I took advantage of it (which is helpful because it has a much more involved compile process).
=> Add lpeg.dll, lfs.dll and all luasocket files to travis builds

CorsixTH/Src/th_gfx_sdl.cpp
The `m_pZoomTexture` was being used as a render target even though
it was uninitialized. This sometimes worked out, depending on your
platform, and other times not.
The fix is to initialize the zoom buffer to transparent and then use
SDL_BLENDMODE_BLEND when it is time to flush the zoom buffer.
Fixes #370
I've played the game briefly and this resolves all of the graphical glitching-making-it-unplayable issues I know of right now.
The only potential downside is that due to the alpha blending, some of the cursors may not look quite pixel perfect. Noticably the red square used to highlight tiles doesn't have quite the right perceived colour (compare it with the red build blueprint):
compared with the usual unzoomed:
.. but this is preferable to the graphics completely breaking :)
--
After …
=> Fix #370 (zoom glitches on some platforms)

.gitignore, CorsixTH/CorsixTH.lua, CorsixTH/Lua/app.lua, CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/debug_script.lua, CorsixTH/Lua/dialogs/menu.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/run_debugger.lua, CorsixTH/Lua/ui.lua, CorsixTH/Lua/utility.lua, README.txt
For issue: #346
To support this CorsixTH simply needs to have "debugger.lua" and a
"dofile('debugger')()" call to it.
This is a 3rd party Lua script and therefore won't be distributed
with CorsixTH, so developers will have to download it into their
Lua directory when setting up a computer for CorsixTH Lua DBGp
debugging.
I've made a new function for the call "dofile('debugger')()":
App:connectDebugger().
I've created a new main menu button to call connectDebugger() which
will only be in the main menu when config.debug = true. I've also
added a connectDebugger() command to the debug menu.
https://wiki.eclipse.org/LDT/User_Area/User_Guides/User_Guide_1.2#Attach_session
=> Added support for Lua DBGp Debugging such as Eclipse debugging

CorsixTH/Lua/graphics.lua
Currently, the program examines the custom graphics folder, even if they are disabled in the config file 'use_new_graphics = false'. Patch skips that code. (Patch with skipping white space changes below)
```diff
diff --git a/CorsixTH/Lua/graphics.lua b/CorsixTH/Lua/graphics.lua
index ec13972..bead419 100644
--- a/CorsixTH/Lua/graphics.lua
+++ b/CorsixTH/Lua/graphics.lua
@@ -95,10 +95,11 @@ function Graphics:Graphics(app)
self:loadFontFile()
+  local graphics_folder = nil
+  if self.app.config.use_new_graphics then
-- Check if the config specifies a place to look for graphics in.
-- Otherwise check in the default "Graphics" folder.
-
-  local graphics_folder = self.app.config.new_graphics_folder or ourpath .. "Graphics"
+    graphics_folder = self.app.config.new_graphics_folder or ourpath …
```
=> Feature: Skip examining the custom graphics folder if custom graphics are disabled.

CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/dialogs/place_objects.lua, CorsixTH/Lua/dialogs/place_staff.lua, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h, CorsixTH/Src/th_lua_anims.cpp, CorsixTH/Src/th_lua_internal.h
Fixes recolouring crashes in 32bpp due to trying to do palette recolouring (which makes no sense in 32bpp).
Added new recolour flags for greyscale conversion (non-placable objects), and red/blue colour swapping (bluprints turning red). The latter doesn't really work well, and needs further work, but it needs proper graphics first.
=> Disable recolouring if the image has no palette to prevent a crash

README.md
Good Old Games changed it's name to GOG.com back in 2012: http://www.rockpapershotgun.com/2012/03/27/good-old-games-gone-relaunches-as-gog-com/
=> Update README.md (GOG.com name change)

CMake/CMakeFFmpegLibavMacros.cmake, CMake/FindFFmpeg.cmake, CMake/FindLibAV.cmake
This is necessary for CMake to find FFmpeg/Libav in a cloned CorsixTH/deps repo on GNU/Linux. As a bonus, it now uses the same method to find includes/libraries on all platforms.
I have only tested this on GNU/Linux. I haven't touched any of the Windows stuff so that should work normally, and it will probably work on OSX too. Could definitely use some testing on various platforms though.
=> Do not use pkg-config to find FFmpeg/Libav on Unix

CorsixTH/Lua/epidemic.lua
Part fix for issue #674. Causes patients who are evacuating to get dressed if necessary and leave the room before evacuating the hospital.
=> Make patients dress and leave room before being evacuated

.gitignore
This allows using cmake to set up multiple build folders without showing
up in the git status using folder structures like:
```
/build-luajit
/build-libav
```
or
```
/builds/luajit
/builds/libav
```
=> Ignore all folders in the root with names starting with build

CorsixTH/Lua/app.lua, CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/game_ui.lua
Solves #724 
~~Warning, since the old shift scroll speed setting was called scroll_speed and this is now the unshifted scroll speed, existing players will have their regular scroll speed increased to twice normal.  Adjust your config.~~
=> Add shift_scroll_speed and make scroll_speed apply to unshifted scrolling

CorsixTH/Src/th_movie.cpp, CorsixTH/Src/th_movie.h
The race condition would sometimes cause a segfault or 0xc0000005 error when
closing a movie with audio (such as the intro) early.
=> Fix race condition decoding audio while movie is terminating

CorsixTH/Lua/audio.lua
The original game played music tracks in the order they appeared in MIDI.TXT. Perhaps this was arbitrary, but perhaps it was intended - either way, when the next track isn't the one I expect it's very jarring!
Prior to this change, MIDI.TXT was loaded, titles extracted, then the playlist was sorted on the titles. This is no less arbitrary than the original order. This change removes the sorting step.
I suppose longer-term, the better thing to do would be to have a setting for 'shuffle play', but this is enough to keep me happy for now and I doubt it will inconvenience anyone!
=> Play music tracks in order they appear in MIDI.TXT

CorsixTH/Src/th_pathfind.cpp, CorsixTH/Src/th_pathfind.h
Move the #define magic of the 4 path finders to 4 derived classes, cleaning up compile warnings along the way. Focus was on making the code readable, and remove the compiler warnings.
Intentionally left the patch as many small changes (except for 1 or 2), so it's at least somewhat trackable what I did, until it is decided this is what is wanted.
Some things remain to be handled somewhen in the future, as far as I can see
- _openHeapPromote method in BasePathing::pathingTryNode looks wrong. The path finder could be broken here. It does get called as well.
- The 'return 0;' in MakeGuess reduces A* to Dijkstra algorithm, a much slower algorithm. By reversing the search direction, it may be possible to make it an A* search
- C++ has a priority queue nowadays in std::
Throwing out path finding …
=> Cleanup pathfinder

CorsixTH/Lua/languages/german.lua
This PR will update the German translation. Things done:
- Translate all missing strings (which were added into 0.40 and possibly later, too)
- Use “Sie” instead of “du” everywhere (was inconsistent)
- Copy-editing (many minor typo and grammar fixes)
=> Update German translation

CorsixTH/Lua/app.lua, CorsixTH/Lua/audio.lua
replacing all "wt" modes to "w" mode, as that's what the manual claims to support.
=> Fix: "t" mode suffix in io.open breaks Lua 5.2

CorsixTH/Src/main.cpp
The warning enourages Lua 5.2+ users to switch to LuaJIT which is not compaitble
with the latest Lua language changes. We have decided to follow official Lua
instead.
=> Remove LuaJIT warning

CorsixTH/Lua/calls_dispatcher.lua, CorsixTH/Lua/dialogs/machine_dialog.lua, CorsixTH/Lua/dialogs/staff_dialog.lua, CorsixTH/Lua/entities/patient.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/objects/plant.lua
Several indenting fixes, found by having several consecutive "end" straight under each other, which can't be right.
In hospital.lua, hunks 1 and 3 fix whitespace.
hunk 2 deduplicates a call to findHandymanTaskSubtable, no point in querying the same subtable twice. It's probably a copy/paste error, as the surrounding functions also have the "subtable = ..." call.
=> Indentation fixes, deduplicating findHandymanTaskSubtable call.

WindowsInstaller/Win32Script.nsi
MapEdit doesn't work in 0.50, and LevelEdit has not received the attention it
needs to be recommended.
=> Remove LevelEdit and MapEdit from Windows Installer

WindowsInstaller/Win32Script.nsi
CorsixTH_SDL.exe no longer exists, CorsxiTH.exe should be run instead.
=> Update program run by the installer at end of install

CorsixTH/Lua/world.lua
If you want a warning today about deleted diseases, this is the simplest solution.
=> Report a warning about removal of a disease.

CorsixTH/Lua/world.lua
Do not print the 'removed disease due to missing room' warning when the disease is already invalid
=> Avoid warning about disabling invalid diseases

CorsixTH/Lua/run_debugger.lua
This file check looked for debugger using io methods, which are not suitable
for determining if the file is in the lua path. This causes the check to fail
when the setup is perfectly fine under numerous scenarios, and on some
platforms prevents running the debugger at all. The dofile will fail with a
missing file error anyway, though it would be clearer if we could replace it.
=> Remove bad debugger.lua file check

CorsixTH/Lua/window.lua
This handles the case of backspace and delete changes not being reflected on
the screen until you entered more text. Fixes #750
=> Update textbox label if keypress changes text

CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
Before there are any patients the average values of warmth, happiness, and
temperature are NaN which crashes the dialog. This accounts for NaN in the
dialog and displays the value right in the center.
=> Fix status report crash with no patients

CorsixTH/Lua/dialogs/resizables/menu_list_dialog.lua, CorsixTH/Lua/window.lua
Normalize alignment specifiers to left, center, right
Account for cursor position when center aligned. Fixes #773
=> Fix cursor position on center textboxes

CMakeLists.txt
LuaJIT is no longer the recommend lua runtime for 0.50 so it should not be
the default.
=> Default WITH_LUAJIT to OFF

CorsixTH/Lua/app.lua
Maybe it is useful to add the Lua version to the window caption if CorsixTH supports several Lua versions like it does now
tested with Luajit 2.0.3, Lua 5.1 and Lua 5.2
=> Add Lua version to window caption

CorsixTH/Src/th_gfx_font.cpp, CorsixTH/Src/th_gfx_font.h, CorsixTH/Src/th_gfx_sdl.cpp
Fixes #785. Also removes unnecessary _setNullTexture function, and sets the
texture to NULL in _freeTexture as is conventional in C++.
=> Fix font cache segfault with unicode fonts when no canvas is given

CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua
That prevents a change of the selected disease in the open drug casebook window when a new disease is discovered.
See also issue #796
=> Fix: Instead of changing the disease name currently pointed to, select the current disease again.

CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/dialogs/place_objects.lua, CorsixTH/Lua/humanoid_actions/sweep_floor.lua, CorsixTH/Lua/world.lua
Fixes #708 (and a few others probably).
The issue shouldn't happen at all, since people cannot drop litter or vomit inside a room.
However, until issue #147 is fixed, litter can be added just before blue-printing a room. When the user then edits the room, the litter is assumed to be part of the room contents, and the program crashes.
=> Fix: Avoid crash by removing litter from rooms getting edited

CorsixTH/Lua/window.lua
Crash can be seen in the file picker dialogs, if you expand the tree until a scroll bar appears.
=> Fix Lua 5.3 crash showing panel scrollbars

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/file_browser.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_game.lua, CorsixTH/Lua/dialogs/resizables/main_menu.lua
Makes the file dialog return the full path when making a choice.
Load and Save code needed to be adjusted to accomodate the change.
This PR fixes the remaining issues with #785
=> Fix file path for font dialog on Linux

CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/map.lua
Fixes some edge cases where the cursor was outside of the map causing crashes.
Fixes #384, #556 and #714
=> Enforce map bounds in ScreenToWorld

CorsixTH/Src/th_gfx_sdl.cpp
Should better handle scenario that leads to #805 and tell us why SDL_SetRenderTarget is failing.
=> Reset scale and print error when zoom fails

CorsixTH/Lua/app.lua
In case anyone uses a resolution that's not divisible by 2, this fixes a crash at launch.
=> Fix crash on start with odd resolution

CorsixTH/Lua/game_ui.lua
Don't know if this should go in 0.50.
I found issue #561, which doesn't give much information, but I interpreted it as having a window on a cured patient open while he walks home. Sure enough, when he walks off the map, his px/py coordinates become floats which the C++ function doesn't want, and the drawing code crashes.
I traced the code to game_ui, where a "limit to diamond" function performs floating point arithmetic to compute the x/y position in that case. The fix was then a simple 'floor' around the returned coordinates.
I didn't change the other returns, as no computations are being done on the coordinates in those cases.
=> Fix crash when window of cured patient is opened while he walks off the map

CorsixTH/Lua/app.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua, CorsixTH/Lua/world.lua
#133: Patients who ceased to exist after using the autopsy machine could still be referenced in the humanoids_enroute table for a treatment room they required when this researched treatment room was created while a patient requiring it was using an autopsy machine. This would queue an action for them to go to the created room after using the autopsy machine, adding them to its humanoids_enroute table.
This reference to a deceased patient in a room's humanoids_enroute table would cause a lua error to occur when the room was edited because the room's deactivate function would reference the patient's hospital field which was nil because the autoposy machine had made it nil.
=> Fixed Lua Error #133

CorsixTH/Lua/room.lua, CorsixTH/Lua/world.lua
This fixes the immediate crashes caused by building a room in an unreachable
area as per issue #819 
It should be noted that this is a very small step towards supporting unreachable areas. If you actually put any staff in this area the game will still quickly crash.
=> Don't crash for unreachable room

CorsixTH/Src/th_gfx_sdl.cpp
Fixes #805 
The first commit fixes the scaling issue where the bottom panel is positioned wrong and the menu size changes.
The second commit fixes a gap that occurs between tiles at the default zoom level when using full screen at non-native resolution by always using the zoom texture for rendering.
=> Fix zoom on full screen with non-native resolution

CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h
In SDL2 2.0.3 and lower versions the y coordinates for the ClipRect is
inverted. This commit detects and handles that case.
Fixes #846
=> Workaround SDL2 bug with ClipRect coordinates

CorsixTH/Lua/languages/dutch.lua
Spanjard from the CorsixTH Forum provided these translations.
I provided him the missing strings from the debug-strings-diff-nederlands.txt file and insert them into the dutch.lua file. I did some checks if the strings are used ingame correctly, but not for all. 
I only do the pull request as requested by Spanjard.
=> Add missing strings to dutch.lua by Spanjard (Forum)

CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
Fixes #830 
I don't think it's right that %d ever formats to include a decimal, but I haven't been able to produce a simplified test case to report upstream to lua. This workaround solves the problem.
=> Fix extraneous .0 in progress tooltips under lua 5.3

CorsixTH/Lua/room.lua
Instead of trying to fail stealing the same patient forever, just skip to a patient earlier in the queue.
This branch is pretty non-readable, see https://github.com/Alberth289346/CorsixTH/tree/fix860_2 for more readable smaller steps.
=> Fix: Don't loop infinitely on trying to steal an unstealable patient. Fixes #860

CONTRIBUTING.txt
GitHub for Mac and GitHub for Windows were merged together to make GitHub Desktop
=> Fix: it's now github desktop [ci skip]

CorsixTH/Lua/app.lua
Added audio:playSoundEffects() in App:loadLevel() to disable / enable sound effects like it is done in LoadGame() for savegames
=> [RDY] Fix #800 don't play sound effects in new scenarios if play_sounds is disabled

CorsixTH/Lua/languages/original_strings.lua
This should fix #862 a mismatch of some German strings compared to the English stings of the full game language files. This does not affect the demo game language files.
=> Fix #862 mismatch of some German and English strings with full game

CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/world.lua
A little code rewriting to kill the need to recurse to the same function for reverting to the previous value.
=> Codechange: Remove recursion from setZoom.

CorsixTH/Lua/dialogs/edit_room.lua
Had a look at the origin TH, today and recognized that there is a different cursor used when a room is in blueprint mode. Want to see it in CorsixTH, too :)
In TH the cursor changes back to the default cursor when mouseover the dialog or the menu bar at the top of the screen, not sure if that is needed in CorsixTH, too.
Tested several scenarios starting at 'wall phase' up to 'objects phase' and backwards. Building a new room and editing another room.
=> Use the 'resize_room' cursor when editing a room like TH does

appveyor.yml
Appveyor users Windows virutal machines and MSVC for continuous integration
My intention is that Windows builds can be made in MSVC like the releases are, and TravisCI can in the future be used for Linux builds, which it is better suited for.
=> [RDY] Add script for appveyor build system

CorsixTH/Src/th_map.cpp
Tried the savegame in the first comment, one from #659, and the save from #902 and they all work now.
They walk a tile in the air just outside the map now. Don't know if that is intended, but it does make them disappear completely from the window that follows them no matter in which direction they walk off-map.
=> Block using a map node that is at the end of the iteration. Fixes #124

.travis.yml
Travis is moving to new container system with faster start times. You can read about it here: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
As a restriction we can't run sudo.
Additionally we are moving towards C++11, which is not while supported by Travis' built in g++-4.6. This pull request abandons the mingw builds (Windows builds are now handled natively by appveyor) and moves to native g++-5.
=> [RDY] Use travis containers and g++ 5 in TravisCI

CorsixTH/Lua/dialogs/jukebox.lua
The jukebox passed the font as a 3rd argument to sizeOf. This was an error that
just started causing problems as d21995e introduced an actual 3rd argument for
max width. Thanks smoke_fumus.
=> [RDY] Fix jukebox crash

CorsixTH/Src/th_map_overlays.cpp, CorsixTH/Src/th_map_overlays.h
String stream operations are safer since they avoid the possibly of buffer overflows.
=> [RDY] Avoid sprintf using C++ string streams instead.

CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
On the Staff Management page, the scroll dot to the left indicating how far through the pages of staff you are was stuck at the top. 
This PR fixes that.
=> Staff management scroll dot

CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
- If staff fired leading to the current page being empty, scroll up a page
- Recalculate whether the scroll dot should be visible after hiring/firing staff
=> Staff management screen scrolling fixes.

CorsixTH/Lua/dialogs/machine_dialog.lua
It is a little bit annoying when i call a handyman to repair a machine and the machine will be repaired several times. e.g. when the handyman was called automatically or several times via the callHandyman button, before.
=> prevent several handyman repair calls for a machine

CorsixTH/Src/lua_sdl.h, CorsixTH/Src/main.cpp, CorsixTH/Src/sdl_audio.cpp, CorsixTH/Src/sdl_core.cpp, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_lua.cpp, CorsixTH/Src/th_lua.h, CorsixTH/SrcUnshared/main.cpp
This pr replaces the cases where function pointers are cast to void*, which is explicitly undefined in the C++ spec. It also names an anonymous struct. Anonymous structs are illegal in C++ 11/14.
These are all the standards compliance issues MSVC informed me about when attempting to compile with /Za. Unfortunately we won't be able to target /Za because standard windows headers rely on non-compliant behavior.
Fixes #929
=> Fix issues with C++ standards complience

CorsixTH/Src/th.cpp, CorsixTH/Src/th.h, CorsixTH/Src/th_lua.cpp
Move loading of THStringList to the constructor. Use exceptions for failures.
Improve the internal representation in THStringList. Notably avoids the naked new and delete statements.
=> Use RAII techniques with THStringList

CorsixTH/Lua/dialogs/place_objects.lua, CorsixTH/Lua/entities/machine.lua, CorsixTH/Lua/entity.lua
Machines will now smoke when they are need of repair.
Shows 1-3 plumes of smoke depending on how badly it needs repairing.
3 plumes: use again & it will blow up
2 plumes: 1 use left
1 plume: 2 uses left
Smoke will still be displayed whilst the machine is in use, and whilst the repair icon is showing, disappearing once the machine is repaired or blows up.
Ideally, different animations should be displayed for each machine (& maybe orientation?). The smoke animations seem to occupy the range 3424-3472. 
As working out which smoke animation goes with which machine could end up being quite laborious I've just used 3424 for every machine, but if I (or anyone else) have the time to work out which animation goes with which machine, it will be straight forward to change this to use an id specified …
=> [RDY] Machines smoke when needing repair

CorsixTH/Src/th_lua_movie.cpp, CorsixTH/Src/th_movie.cpp, CorsixTH/Src/th_movie.h
*Updated*
Avoids the use of GL shared contexts which are buggy on some hardware. This PR also moves the scaling of movies to SDL where it may be done in hardware, and improves the documentation of thmovie.h. A few smaller housekeeping items were taken care of as well.
=> [RDY] Do not use shared opengl context for movies

CorsixTH/Src/persist_lua.cpp, CorsixTH/Src/rnc.cpp, CorsixTH/Src/sdl_core.cpp, CorsixTH/Src/th_lua.h
luaL_newlibtable expected a C array to set the size of the table based on the
number of elements, but since luaT_register is a function that array is being
auto cast to a pointer where the size wasn't available. By using vectors instead
we preserve the size.
=> [RDY] Fix luaT_register

CorsixTH/Src/sdl_audio.cpp, CorsixTH/Src/th_movie.cpp, CorsixTH/Src/th_movie.h
Fixes compile errors when either sdl mixer, or movies are disabled in cmake
=> [RDY] Fix compile errors when some features are off

CorsixTH/Lua/dialogs/build_room.lua, CorsixTH/Lua/dialogs/place_objects.lua
As issue #924 says, you cannot build a room in free build mode, since the gui still checks for sufficient balance, and suggests to take a loan instead of allowing to build.
This patch makes the gui display 0 costs for the rooms, and disables the gui cost check entirely in free build mode.
=> Fix free build rooms

CMakeLists.txt, CorsixTH/Src/config.h.in, CorsixTH/Src/iso_fs.cpp, CorsixTH/Src/persist_lua.cpp, CorsixTH/Src/persist_lua.h
Calls to alloc have been replaced with C++ vectors. malloc.h is not available
on some OSX machines as per #961
=> Replace all usage of non-standard malloc.h / alloc.h

.travis.yml
The current script uses ~~lua 5.1 and~~ no sshpass, this adds ~~lua 5.3 (manual build as it's not in any ubuntu repo that travis containers has access to) and~~ sshpass.
Lua commit taken out.
=> Sshpass for Travis CI 

CMake/FindLua.cmake
This update adds additional search directories valid for homebrew installed versions of Lua on OS X platforms.
Also included are two additional failure errors for more specific messaging about what fails to be found.
=> Fix Lua CMake To Find Lua On OS X systems

CMakeLists.txt
As msmollin found in #959 these lines aren't needed, the documentation says it's discovered appropriately at the right time.
=> Remove OS X cmake instructions

CorsixTH/Src/iso_fs.h, CorsixTH/Src/persist_lua.cpp, CorsixTH/Src/persist_lua.h, CorsixTH/Src/run_length_encoder.h, CorsixTH/Src/th.h, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_gfx_font.cpp, CorsixTH/Src/th_gfx_font.h, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h, CorsixTH/Src/th_map.h, CorsixTH/Src/th_map_overlays.cpp, CorsixTH/Src/th_map_overlays.h, CorsixTH/Src/th_movie.h, CorsixTH/Src/th_pathfind.h, CorsixTH/Src/th_sound.h, CorsixTH/Src/xmi2mid.cpp
- Reduce scope of members from protected to private as allowed by current usage
- Use override keyword, not virtual, to mark overridden virtual functions on
derived classes.
- Use default virtual destructors on base classes when there were no resources
to free on the base.
- Mark derived classes as final where it is obvious that they should not be
subclassed.
=> [RDY] Cleanup the C++ object oriented code

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.txt
GitHub recently introduced support for issue templates: https://github.com/blog/2111-issue-and-pull-request-templates
Try it out at: https://github.com/TheCycoONE/issue-template-test/issues/new
=> [RDY] Add github issue template

CorsixTH/Src/th_map.cpp
char_traits are not defined for unsigned int in the standard. Use a regular
ofstream (char) and reinterpret_cast the unsigned chars to chars.
This is a safe operation.
=> [RDY] Fix standards compliance saving map

CorsixTH/Lua/game_ui.lua
Boolean magic is too complicated for me :(
=> Prevent a crash when rotating an object at a tile where it cannot be placed

README.md
To show status of the latest Windows build. The two status images are very similar, but it seems to be Github tradition to not label them.
=> Add Appveyor badge to Readme

CorsixTH/CMakeLists.txt, CorsixTH/RequiredResources.txt
This adds the newer folders to the rsync list and changes the OS X target of the rsync to the MacOS folder where the CorsixTH executable is. It's done this way in the 0.40 release and I'm unsure why others haven't seen this problem (it's hidden if you move the app to the top folder of the repository). Only the Icon.icns is left in Resources because that sets the Finder icon, which may not be in control of CMake, my testing didn't make that clear.
=> [RDY] Update Rsync filter file and use

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/dialogs/patient.lua, CorsixTH/Lua/dialogs/queue_dialog.lua, CorsixTH/Lua/dialogs/resizables/cheats.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/inspector.lua, CorsixTH/Lua/entities/patient.lua, CorsixTH/Lua/entities/staff.lua, CorsixTH/Lua/entities/vip.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/humanoid_actions/die.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua, CorsixTH/Lua/humanoid_actions/spawn.lua, CorsixTH/Lua/humanoid_actions/use_object.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/languages/french.lua, CorsixTH/Lua/objects/reception_desk.lua, CorsixTH/Lua/room.lua, CorsixTH/Lua/rooms/gp.lua, CorsixTH/Lua/rooms/research.lua, CorsixTH/Lua/world.lua
A cleanup of the patch queue from #971
There are few changes from the code in #971 rebased onto the latest master.
The pull request does a few things:
1. It introduces a response to drug casebook prices, patients will go home without paying if prices are too high and reputation is affected.
2. Makes hospital reputation impact the number of patients spawned
3. Fixes the death rate for under diagnosed patients
4. Refactors patient treatment, of particular note patient.hospital is now never nil.
=> [RDY] Drug casebook price impact

WindowsInstaller/Win32Script.nsi
There are no longer any pngs in this folder so this line causes the install to
fail.
=> [RDY] Don't copy pngs in NSIS install script

CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/walls/external.lua
Previously, if you built something next to an expansion wall that wall would disappear and be replaces by the room's internal one. Also, if the expansion happened to have half of a window visible an extra piece of wall would appear out of nowhere when you finished the room. Prerequisite to fix #451.
=> [RDY] Fix building of rooms adjacent to parcel expansions

CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/world.lua
Original patch #225 aiming to fix #74 by MarkL, which seemed mostly ok, but the last fix was never done, instead the patch was closed.
Original comment:
````
To replace issue #81 and issue #121
This will allow the player to turn off the initial grace period in
config.txt.
Which is what I think issue #74 is about. Currently happiness does not
go down if it is too cold in the first year.
```
Updates done: Replaced boolean value by month count, moved grace period handling to the monthly hospital function, tuned down the happiness changes a bit (0.02 -> 0.015 factor).
=> [RDY] Remove initial warmth grace period, reduce impact of too cold/warm. Fixes #74.

CMake/FindLua.cmake
rebase PlayDeb patch on latest 0.60-beta1 release for use in official debian package: https://tracker.debian.org/pkg/corsix-th
Author: Christoph Korn <christoph.korn@getdeb.net>
Origin: https://github.com/ckorn/PlayDeb/commit/24d441933c042e44c16884eba1125406dcefcf74#diff-f68957b6e9561c95afdd68f41343ff97
Reviewed-by: Phil Morrell <debian@emorrp1.name>
Last-Update: 2016-04-17
=> support lua5.2 in FindLua.cmake for deb packaging

CorsixTH/Lua/map.lua, CorsixTH/Lua/world.lua, CorsixTH/Src/th_lua_map.cpp, CorsixTH/Src/th_map.cpp, CorsixTH/Src/th_map.h
One proposed solution to #451.
The actual buying of a plot needs to be done in C++ as it would be way too slow in Lua (I gave it a go). At the same time C++ doesn't know about wall types for different rooms etc, so the logic for which type of wall to add when a player buys a new plot must be done in Lua. Therefore this proposed solution makes the C++ "buying" code return which tiles inside you current hospital are adjacent to the plot you are buying, and then Lua checks whether some extra room wall needs to be placed at these now removed external expansion wall positions.
=> [RDY] Fix disappearing room walls next to new plots

CorsixTH/Lua/rooms/psych.lua
After curing, the humanoid class changes, in current master (I found out while trying to get crash logs in #1033). This fix uses the disease of the patient which is a bit more stable, apparently. It fixes the double payment, and also the double "go home" message.
Don't know where this change was introduced.
=> Use a more stable variable to denote cured Kings. Fixes #1033

CorsixTH/Lua/app.lua, CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_map.lua, CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua
Similar to the savegame directory, this commit adds a user level file. By
default this uses a new Levels directory in the same path as the config. When
picking a single scenario both the users level directory and the built in level
directory are checked.
Addresses #1045
=> [RDY] Adds a user level directory

CorsixTH/Src/th_movie.cpp
Fixes a flaw with the handling of libav in #1043
Needs verification from @bobcanthelpyou
=> [RFC] Restrict av_image_get_buffer_size to proper libav versions

CorsixTH/Lua/entities/object.lua, CorsixTH/Lua/entity.lua, CorsixTH/Lua/world.lua
This prevents missing objects when two or more objects share a tile while loading a savegame.
Before this patch, the second object to add would remove the first added
object, causing path finding failures when looking for the first object.
Many thanks go to TheCycoONE for his pathfinder bug hunting and finding
about the missing objects.
=> On loading a savegame, first remove all object-thobs, then add them again. Fixes #1063

CorsixTH/Lua/world.lua
If a level file only has visible diseases, and these are postponed until the future by the level file, the unfixed code would loop forever.
=> [rdy] Avoid infinite looping if there are no viable diseases for new patients. Fixes issue #732

appveyor.yml
The debug build cannot be distributed. This changes to a release configuration so that people can run our AppVeyor builds without having Visual Studio installed.
=> [RDY] Use release build for appveyor so it can be run without VS

CorsixTH/Lua/dialogs/resizables/map_editor.lua
Scale once for the entire drag area instead of once per tile. Greatly
improves performance.
Fixes #1084
=> [RDY] Fix performance issue with drag draw in mapper

CorsixTH/Lua/dialogs/staff_dialog.lua
- Closes #1055.
An issue I've ran into with implementing this: if I saved a game with a handyman's dialog window open that used the 'old', non-repeat buttons, and then loaded that game using my code changes to the buttons, the buttons are non-repeat ones until I close and reopen the dialog window.
@sadger suggested implementing some type of `afterLoad()` functionality, if we don't want this behavior to persist. Feel free to offer your suggestions/thoughts. :)
Thanks.
=> [RFC] Allow handyman priorities to be adjusted with 'click-and-hold'.

CorsixTH/Lua/dialogs/bottom_panel.lua
When allow_user_actions_while_paused is enabled we don't want to block the
bottom panel buttons with the pause overlay.
Thanks Brainsample.
Patch taken from #1102
=> Allow use of bottom panel during pause

.gitignore, AnimView/frmMain.cpp
Fixes AnimView so that it doesn't assert in wxWidgets 3.1 and higher due to overconstraining some of the layout. This PR also removes the giant VSPR-0.XML file from github. That file can be generated with AnimView and is not useful to store.
=> AnimView fixes and cleanup

CorsixTH/Lua/humanoid_actions/seek_room.lua
Remove the callbacks which would make the patient return to the diagnosis
room after it's built even though they were already diagnosed through
guess the cure.
Fixes #1108. Again thanks to Brainsample, who does all the work I keep taking credit for.
=> [RDY] Fix cure in diagnosis room

CMake/FindLua.cmake
This will make it easy to add future versions for all platforms:
* lua5x ??, presumably used by Visual Studio
* lua5.x used by debian-based linux distros
* lua-5.x ??, was there in 5.1
* liblua.5.x.dylib used by homebrew on OS X
=> Normalise lua version detection for cross-platform

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/humanoid_action.lua, CorsixTH/Lua/humanoid_actions/call_checkpoint.lua, CorsixTH/Lua/humanoid_actions/idle.lua, CorsixTH/Lua/humanoid_actions/idle_spawn.lua, CorsixTH/Lua/humanoid_actions/knock_door.lua, CorsixTH/Lua/humanoid_actions/multi_use_object.lua, CorsixTH/Lua/humanoid_actions/pickup.lua, CorsixTH/Lua/humanoid_actions/queue.lua, CorsixTH/Lua/humanoid_actions/seek_reception.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua, CorsixTH/Lua/humanoid_actions/spawn.lua, CorsixTH/Lua/humanoid_actions/staff_reception.lua, CorsixTH/Lua/humanoid_actions/sweep_floor.lua, CorsixTH/Lua/humanoid_actions/use_object.lua, CorsixTH/Lua/humanoid_actions/use_screen.lua, CorsixTH/Lua/humanoid_actions/vaccinate.lua, CorsixTH/Lua/humanoid_actions/walk.lua, CorsixTH/Lua/room.lua, CorsixTH/Lua/rooms/operating_theatre.lua
The primary purpose of this pr is to add type checking to the action queue and enforce consistent types for given properties to make errors easier to trace.
During the process I also found a typo which is corrected in the first commit.
=> [RDY] Action parameter checking

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/dialogs/place_objects.lua, CorsixTH/Lua/entities/patient.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/humanoid_actions/sweep_floor.lua, CorsixTH/Lua/objects/litter.lua, CorsixTH/Lua/room.lua, CorsixTH/Lua/world.lua
This should solve the room litter problem once and for all. It ignores litter as cause for non-buildability for rooms, clears litter from new rooms, and removes litter from rooms in old saves.
I am however not so happy with the buildable flag. It gets treated asif there is a single cause for the tile being non-buildable, but we have several possible causes. In case of litter, there is definitely the option to have more than 1 litter object at a tile, which means setting it to true unconditionally is just wrong.
Maybe the flag should have a cause , or it should be derivable from the tile contents (which would be major +1). Ideas?
Edit: https://github.com/CorsixTH/CorsixTH/pull/381#issuecomment-68917824  says we should never have more than one litter on a tile.
_Edit: Ignore the first 2 …
=> [rdy] Litter room fix

CorsixTH/Lua/humanoid_actions/use_screen.lua
use_screen can apply to either regular screens or surgeon_screens. I missed
surgeon_screen in my earlier patch.
=> [RDY] Fix assert for use_screen action

CorsixTH/Lua/humanoid_actions/spawn.lua
Clarifies the use of SpawnAction's offset and fixes the test for its value.
=> [RDY] Fix the spawn offset assert

.travis.yml
Switches from a loop in a subshell to using xargs, improving the find command to be more efficient and handling the possibility of spaces in file names. The command is also now agnostic to the current directory. exit logic is unnecessary now.
=> [RDY] Improve command for running luac in travis

CorsixTH/Src/th_movie.cpp
Commit f10ac388f22a8fecad9a987a229f002fa65cd266 changes the arguments
for THMovie:play and THMovie:refresh but forgot to update the version
used when movies are disabled.
Fixes #1143
=> Update dummy THMovie functions to new arguments

CorsixTH/CorsixTH.lua, CorsixTH/Lua/audio.lua
The Decoda IDE appears to be abandoned, with no commits in 2 years and no
releases in 3.
=> Remove Decoda debugger code paths

.travis.yml
This fixes Travis CI erroring out when trying to install luasec through
the wrong manifest with luarocks.
=> Add '--server' option to luasec install line for Travis CI.

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/graphs.lua
Don't print graph labels below the bottom of the graph, 2 pictures to show below.
The order of the entries in a clustered sequence looks unstable, but it's not a problem imho, as such labels all belong to the same position at the screen, so order has little meaning anyway
=> [rdy] Keep labels of the graph within their space, addresses #1008

CorsixTH/Lua/rooms/operating_theatre.lua
Unpersisted file local functions cannot be referenced by persisted functions.
By moving buildTableAction2 into OperatingTheatreRoom the persistence engine
handles saving it and restoring it into old environments automatically.
Fixes #1172 and #1179
=> Move buildTableAction2 into OperatingTheatreRoom

CorsixTH/Lua/world.lua
Related to issue #573 
This restores the original TH behaviour of having rooms with max queue size 0 be used once all available queues are above their max queue size.
Closed rooms still receive a penalty in findRoomNear so they should never be used before open rooms.
Not 100% sure how this will interact with the usage of findRoomNear in patient.lua, which doesn't use advanced mode.
=> Patients queue for rooms with max queue size 0

CorsixTH/Lua/world.lua
Fixes the immediate problem with the earthquake not loading properly in  #1199 
Unfortunately there are further problems with that save, which cause problems immediately afterwards when trying to crash the problem
=> RDY: Fix loading saves with pending earthquakes

CorsixTH/Lua/movie_player.lua
Gracefully exit methods in movie_player.lua if the movie player has not
been initialized.
Hide private methods from outside by making them local functions.
Fixes #1225
=> [RDY] Do not assume moviePlayer has been initialized

CorsixTH/Src/th_movie.cpp, CorsixTH/Src/th_movie.h
Conditionally replaces deprecated ffmpeg / libav functions and procedures with current equivalents. The most significant being the change to the avcodec_send_packet / avcodec_receive_frame decoding API that replaces the old avcodec_video_decode and avcodec_audio_decode functions.
=> [RDY] Support current FFMPEG / libAV APIs

CorsixTH/Src/th_movie.cpp, CorsixTH/Src/th_movie.h
Replace SDL threading with C++11 threading.
In making this change I already fixed one possible deadlock where the mutex was
not released in write if the picture didn't have a buffer.
=> [RDY] Use C++11 standard threading for th_movie.cpp

AnimView/th.cpp, CorsixTH/Src/persist_lua.cpp, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_map.cpp, CorsixTH/Src/th_map.h, CorsixTH/Src/th_pathfind.cpp, CorsixTH/Src/th_pathfind.h
Fixes all errors reported by cppcheck 1.80 using the default arguments. A few warnings remain in scanner.cpp.
Mostly this involved fixing edge case memory leaks, either by adding deletes or by moving away from using raw memory buffers entirely.
=> [RDY] Fix cppcheck errors

CorsixTH/Src/th_gfx_font.h, CorsixTH/Src/th_gfx_sdl.cpp
Fixes #1266 and #1263 and maybe a few others
The renderer was being destroyed every time `THRenderTarget::update` was called, due to a bug in the flag check logic. Destroying the renderer also invalidated all of the game textures, but we have no mechanism to discard them.
The only reason the renderer would be legitimately destroyed (a change to the vsync setting) isn't currently possible in game anyway, so this PR removes the capability and moves the creation of the renderer into `create` instead of `update`.
The first commit just removes some unnecessary casts that I found while investigating this problem.
=> [RDY] Don't destroy the renderer

CorsixTH/Src/th_pathfind.cpp
We were writing to an empty vector when poping the last element.
=> [RDY] Fix write to empty vector

.gitignore, CMake/CopyVcpkgLua.cmake, CMake/PrecompiledDeps.cmake, CMake/VcpkgDeps.cmake, CMakeLists.txt, CorsixTH/CMakeLists.txt, CorsixTH/CorsixTH.rc, appveyor.yml, scripts/build_vcpkg_deps.ps1
Compared to #1261 this PR:
* Handles SDL2 on multiple configuration targets when using built in vcpkg, by using the provided sdl2 cmake config.
* Doesn't modify FindSDL2.cmake (those modifications didn't work)
* Copies lua files from the `vcpkg/installed/**/share/lua/*` directory
* Checks out the correct commit when cloning vcpkg the first time
* Checks out a newer vcpkg commit, containing luasockets and newer sdl packages
* Fixes whitespace
* Modifies appveyor to take advantage of these changes
=> [RDY] CMake deps handling - continuation of pr #1261

CorsixTH/Lua/app.lua, CorsixTH/Lua/game_ui.lua, CorsixTH/Src/sdl_core.cpp
I have access to a convertable device that I have tested quickly at this stage addressing touch controls.
Both pinch zoom and move map which is working mostly okay with this code.
What I don't have is a device specifically like that mentioned in #593 which may have this behave entirely different or interfere generally with use so would be nice to get this tested elsewhere.
=> [RDY] Touch support for pinch zoom and move map

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/place_objects.lua, CorsixTH/Lua/entities/object.lua, CorsixTH/Lua/map.lua, CorsixTH/Lua/world.lua
A proposed resolution to #1105 and related issues where pathfinding breaks from placement of side objects.
afterLoad in map and world to call their required methods to fix pathfinding on old saves.
To prevent the issue occuring, added a check and calls to those same functions in Object:onDestroy after the super class method is called when any side objects are moved.
=> [RDY] Pathfinding broken by side objects

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/staff.lua, CorsixTH/Lua/humanoid_actions/sweep_floor.lua, CorsixTH/Lua/objects/litter.lua
Litter not 'tickable' as in to interrupt Handyman tasks when Litter:remove on build over.
I didn't update Litter:remove() to enforce the ticks = false, just left that to new litter only.
Removing the task in the action_sweep_floor_start is similar to Plant:restoreToFullHealth called from the end of action_use_object_start.
Hopefully addresses issues in #1155.
=> [RDY] Remove handyman task upon sweep action start

CorsixTH/Lua/humanoid_actions/die.lua
For #1285.
Still attempts the fall east/south randomly chosen, then should attempt the opposite. If neither then it should check west than north tiles to travel to so can fall east then south.
As patients/staff are wandering around some of these checks will fail still after walk actions, or immediately not be possible. So I have got a bit of a brute force search for tiles, and this can sometimes make the patients wander around a bit too much, especially in a single width corridor with patients passing through.
That brute force loop uses getAdjacentFreeTiles which has the issue in entity_map. Without that fix it will go in an infinite loop.
=> [RDY] Dying patient walk instructions can lead to recurring invalid walk instructions

CorsixTH/Lua/hospital.lua
Adds a check for patient.dead so Patient:die isn't called again as is happening in #1165
=> [RDY] Kill patients only once during emergencies

CorsixTH/Lua/dialogs/resizables/new_game.lua
Fixes the salary not increasing between levels. 
In `app.lua : 592` we only carry across the player state if the `world.campaign_info` variable is set. This isn't set correctly in `dialogs/resizables/newgame.lua : 199`  so the salary was not preserved.
Also I've removed a check that `TheApp.world` has been created, `loadLevel` should handle this and bail if something goes wrong on our behalf instead of us checking and ignoring.
Fixes #1275 
----
Ideally the UI dialogue should not be setting states on the app behalf. Instead it should be tweaked so `app.lua` has a method to start the original campaign (we already have a function for custom campaigns) which keeps this logic in a single location. However I wanted to get this change into the RC so left the re-factoring for a future date. …
=> [RDY] Fix campaign not preserving salary between levels

CorsixTH/Lua/languages/english.lua
It should read "Machines such as the Inflator" rather than "Machines such as the Inflation"
=> Fixing wording on one of the tips shown on startup.

.gitignore
Even though the recommended path to build the game is outside the source, when running make without specifying path the game still gets build to `CorsixTH/CorsixTH`. That's why I created this PR anyway:) Please see the issue for more info.
=> Issue 1321: Adds default build path to .gitignore

CorsixTH/Src/th_lua.cpp, CorsixTH/Src/th_lua_internal.h, CorsixTH/Src/th_lua_strings.cpp
Converts C style luaT_setclosure with varargs to a vararg template.
This adds (some) type safety and fixes:
```
/home/stephen/github/CorsixTH/CorsixTH/Src/th_lua.cpp:252:24: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
for(va_start(args, eMetatable1);
```
=> [RDY] Fix undefined behaviour in luaT_setclosure

CorsixTH/Lua/entities/vip.lua
Fixes #1115, counting only usable rooms for average queue size. Fixes the comment in that function about hospitals with no functioning rooms. The -100 rating is arbitrary but as no-one would expect a positive review of a hospital in that state does it seems fair?
=> [RFC] Fix VIP behaviour about hospitals with no functioning rooms

CorsixTH/Lua/objects/litter.lua
Provides a quick fix for handyman issue in #1329. I actually recall having this change in there previously, but can't recall testing this exact scenario, alas at somepoint I had removed it and forgot to put it back in.
Appears to be a more extensive issue of placing objects where a humanoid is already standing which was prevented in original.
=> [RDY] Prevent double remove on same litter object

CorsixTH/Lua/dialogs/place_objects.lua, CorsixTH/Luatest/spec/entities/machine_spec.lua
* This used to break moving new machine without state
Fixes #1369
=> [RDY] Removes default empty state to be set

CorsixTH/Src/config.h.in
I think this 64bit test is both more complete and much simpler than trying to enumerate an exhaustive list of platform and compiler 64bit defines?
=> [RDY] Simpler 64-bit test

AnimView/frmSprites.cpp
AnimView's Sprite Viewer did not allow selecting tab/dat/pal files if
they used uppercase naming in Linux.
=> [RDY] Enhancements for case sensitive filesystems

CorsixTH/Lua/humanoid_actions/meander.lua
Make meandering look more natural by avoiding sudden changes in direction.
#1376
=> More natural meandering

CorsixTH/Src/th_movie.cpp
av_register_all no longer needs to be called
best_effort_timestamp is now a property not a function
=> [RDY] FFMPEG 4.0 deprecation fixes

CorsixTH/Lua/dialogs/bottom_panel.lua, CorsixTH/Luatest/TH.lua, CorsixTH/Luatest/corsixth.lua, CorsixTH/Luatest/spec/dialogs/bottom_pannel_spec.lua
Resolves a crash if setDynamicInfo is given a table with a missing text
key. The source of the problem is now logged to gameLog without a crash.
Additional scaffholding was written to support verifying unit tests.
Fixes #1410
=> [RDY] Enforce dynamic_info text key

.luacheckrc, CorsixTH/Lua/entities/object.lua, CorsixTH/Lua/room.lua
Use next instead of pairs to test if a table is empty.
=> [RDY] Fix one iteration loop warnings

CorsixTH/Src/th_movie.cpp
We must not free a context when we did not allocate it. In old versions
thei video and audio contexts were borrowed not owned.
Fixes #1409
=> Fix double free regression in old ffmpeg

CorsixTH/Lua/dialogs/resizables/directory_browser.lua, CorsixTH/Lua/dialogs/tree_ctrl.lua
lfs opens a file when lfs.dir is called. The file is only closed when
the iterator hits the end of the directory list, or close is explicitly
called. This commit calls close in the necessary places.
Should fix #1460
=> [RDY] Fix leaking file descriptors

CorsixTH/Lua/humanoid_actions/walk.lua
Addresses #1425 where a room is built on the already calculated walk path, and the walk path is interrupted by a door.
=> [RDY] Reroute if door/wall has been built on walk path

CorsixTH/Lua/entities/patient.lua
Addresses #1439. Where a walk action is interrupted to a drinks machine resulting in an incorrect 'must_happen' walk after the drinks machine use.
=> [RDY] Interrupted walk should refer to original must_happen

LevelEdit/src/com/corsixth/leveledit/ReaderWriter.java
The level editor still uses %LevelFile when writing the .level file, it also ignores %MapFile, I haven't remove the old code to read %LevelFile, as it's useful for backwards compatibility
There's still some work to be done with the level editor, but it's a starting point
=> replace %LevelFile with %MapFile in the level editor

CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h, CorsixTH/Src/th_lua_gfx.cpp
Use exceptions and lua_error to show the cause of any error loading bitmaps
instead of simply false. This makes diagnosing errors much easier.
This patch was used to diagnose #1468 but does not fix the issue.
=> [RDY] Show errors when loading bitmaps

CorsixTH/CMakeLists.txt, CorsixTH/corsix-th.6
New man page inspired by the one included in Debian. This one is written in mdoc; which has the advantage of being a largely semantic markup producing consistent man pages.
I plan to sort the resource files dumped into /CorsixTH in the future; at present this seems like it belongs; which allows me to put it in the CorsixTH CMake file, and likewise add a man page for e.g. AnimView that is only installed when AnimView is included in the build.
I do plan to add the install to cmake as part of this PR. I will likely also add a files section similar to what Debian has.
=> [RDY] Add man page for corsix-th

CorsixTH/Lua/humanoid_actions/walk.lua
Using getObject with a table input to find either door type instead. Refers to #1425 still
=> [RDY] Litter placed before a door was placed was only found on thob checks

CorsixTH/Lua/entities/staff.lua, CorsixTH/Lua/room.lua
Addresses #1429.
One additional change here was to remove the humanoidDeath call from Staff:die() as staff deaths didn't count to death count in TH or affect reputation (room being destroyed did).
There is one outstanding issue which might contribute (or not) to some bugs, is that Room:crashRoom calls World:destroyEntity, which removes multiple entities. From my understanding that can result in skipped tick calls as calling table.remove from within an iteration from ipairs is bad.
=> [RDY] Crashed room despawn

CorsixTH/Src/th_movie.cpp
Fixes a segfault in environments where smacker support is disabled in ffmpg.
Bug #1315
=> [RDY] Handle when no supported video stream is found

CorsixTH/Lua/rooms/psych.lua
Addressing #1394
A kings complex patient in psych that is diagnosed and being treated, will generally, if interrupted, queue the walkTo/UseScreen actions upon navigating the door.
The 'couch' check prevents the duration ticking down when navigating the door.
Also limited the duration check to equality to only allow running it once, the walkTo to screen can still be interrupted once started.
Staff will also get a MeanderAction if patient no longer in the room as the book case use logic can leave the count above 0 and therefore the doctor stuck. This will allow the doctor to start over as if the patient was dealt with.
=> [RDY] Kings complex patient in psych

CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/humanoid_actions/queue.lua
Removing litter in a room found in #1401 though this shouldn't really be an issue in more recent builds and shouldn't be an issue once the reservation bug is fixed, which shouldn't lead to this invalid state.
#1012 I thought it would break something without more investigation, but the initial queue action start has the same changes (just there its on the IdleAction), and I haven't as yet found any side effects when running in other PRs that I've been testing.
The 3rd change is the countSittingStanding, where patients idle in a room counted negatively to the standing stats. I came across this one after an epidemic evac, when only about 6 patients were seated in a large hospital and about 24 were in rooms, but only about 4 were standing in the corridor and 12+ standing idle in rooms …
=> [RDY] Three one liner fixes

CorsixTH/Lua/ui.lua
Silences error about the missing handler. May be extended in the future.
Fixes #1464
=> [RDY] Add empty multigesture handler to ui.lua

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
The ordering of fields is broken when multiple hospitals have the same value and they aren't in index order. So my change insteads passes through the index of the hospital being processed, finds the index of that hospital in the sorted list and returns that directly instead of using the 'dup_' values to try and do this.
The current code will draw names over the top of another and can leave with gaps in the list when multiple hospitals have the same value.
Sort functions changed to always put the local player hospital first assuming its at index 1.
I also aligned the date of the first year with TH as the Date class has this as a 1 indexed value, and its already incremented at this point for the next year.
=> [RDY] Annual report changes from AI Hospitals PR

CorsixTH/Src/random.c
Found this when taking a look at random implementation. Only gets used in this form in one place - MoviePlayer:playLoseMovies where it could return 0 and index into lose_movies, returning nil.
=> [RDY] Fix math.random with one parameter call

AnimView/CMakeLists.txt, CMakeLists.txt, CorsixTH/CMakeLists.txt
Minor change to more conventional CMake for setting c++ standard version.
=> [RDY] Use CMake standard method of setting C++ std

CorsixTH/Lua/game_ui.lua
Speed Scrolling modifier was only included in the GameUI constructor, and not subsequenctly called from setupGlobalKeyHandlers, thus a save from a prior version will break (nil passed into pairs as shift_scroll_key_long not initialised) and if it is changed on a new one, it will remain using the old keys.
=> [RDY] Speed scroll not handled by GameUI:setupGlobalKeyHandlers 

CorsixTH/Lua/ui.lua
A number of small improvements around releasing the mouse, the most important of which fixes #1502
=> [RDY] Cursor fix

CorsixTH/Lua/entities/patient.lua, CorsixTH/Lua/epidemic.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/room.lua
Addressing #1436. I can't recall if an evacuation affected the statistics in the original for not treated, but have stopped the percentages being updated here.
The only negative is that goHome will get called twice, when a patient is 'dealtWithPatient' call is made in a callback after an action completes, the warning will be printed.
=> [RDY] Implement a goHome handler for evacuated patients

CorsixTH/Lua/rooms/operating_theatre.lua, CorsixTH/Lua/rooms/ward.lua
Didn't see push failed with the previous PR. hasLeavingAction required as staff member current action might not be is_leaving at the time of the getStaffMember call.
=> [RDY] getStaffMember update

CorsixTH/Lua/entities/patient.lua
Finally tracked down the invisible drinks machine (mentioned in #1206).
From memory checking watch, yawns and tapping foot were only done whilst waiting in queue or whilst waiting for a room to be built, I can't recall it very well.
As the patient had to be waiting for a room to be built in this instance, waiting for 30 or 50 days and also happen to be using the drinks machine at the same time, it happens rarely. I'm not sure if there is any value in the is_leaving, I assume that was put in some time back for some purpose but I've replicated it across to the yawn as well. Likewise even though the checkWatch/tapFoot calls were only ever done within the Patient:tickDay checks at the start, and therefore patient.waiting had to be ticking down, they would never be called for an idle state …
=> [RDY] Invisible drinks machine

CorsixTH/Lua/dialogs/queue_dialog.lua, CorsixTH/Lua/queue.lua
#368 indicates some problems with queue reordering. I wasn't able to get an instance of the handyman at the front preventing a move of an epidemic patient, but I did manage to get a queue that happened to have 2 epidemic patients in it, and the order would not change.
I also got the other more easily observed issue of the handyman in room popping into and out of the queue when re-ordering. The changes here, insert re-ordered patients relative to the start of the 'reportedHumanoids' of the queue rather than the entire queue addresses both issues. And this appears to fix both issues.
=> [RDY] Queue dialog patient reordering fixes

CorsixTH/Lua/dialogs/tree_ctrl.lua
When selecting a file in the tree control the mouse up event was not
marked as handled, causing it to propogate to underlying windows. In the
map editor this resulted in an error if an overlay was enabled because
the map would be replaced before the event would be handled.
FIxes #1387
=> [RDY] Mark mouse click handled in file tree ctrl

.luacheckrc, CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/dialogs/message.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/entities/humanoids/staff/doctor.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua
When looking at the autospy discovery issue I raised, I also noted inconsistencies with seek treatment room fax as mentioned in #453. Some of these are documented, some are differences from the original (not necessarily desired though), and there are probably more better ways to perform the same functions.
Patients seeking a treatment room fax doesn't 'exist' for the 'need_to_employ' message when room exists but not the required staff - #469 
Patients seeking a treatment - seek the room when unstaffed - related to above (this change compromises on the diagnostic rooms) and patients will not attempt to queue until a staff member exists in the hospital
Research button disabled when the treatment room is discovered when it should remain enabled (research and researcher exist)
Interrupted …
=> [RDY] Research fax options updating

.travis.yml, CMakeLists.txt
Trying to fix broken Travis builds
=> [RDY] Bump travis to Xenial

CorsixTH/Src/th_sound.cpp, CorsixTH/Src/xmi2mid.cpp
I compiled CorsixTH with g++ with ubsan (undefined behaviour sanitizer) enabled, and it flagged a couple errors.
These fixes are quick/minimal so that they can land before the 0.63 release.
=> [RDY] Fix undefined behaviour

CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
Minor cosmetic stuff.
Changes this
to
Just iffy on the 'Recall Position Keys' being there twice.
=> [RDY] Hotkey assign, recall window title update

CorsixTH/CMakeLists.txt
@emorrp1 / @tim77 I think this does the right thing.
My one concern is that now cmake install adds a desktop file, but not the required icons. Do you think this is ok for 0.63?
=> Add desktop and appdata in cmake install

CorsixTH/CMakeLists.txt
Use DATAROOTDIR instead of DATADIR for files that belong in the root
/usr/share instead of /usr/share/**/corsix-th.
This allows putting corsix-th under /usr/share/games.
=> [RDY] Use DATAROOTDIR for icons, metadata on *nix

CorsixTH/com.corsixth.CorsixTH.appdata.xml
Should be the application id which is the base name of the desktop file, not the file itself.
=> The id in the appdata is not the desktop file

AnimView/CMakeLists.txt, AnimView/app.cpp, AnimView/config.h.in, AnimView/frmMain.cpp, AnimView/frmMain.h, AnimView/frmSprites.cpp, AnimView/frmSprites.h, AnimView/th.cpp, AnimView/th.h
Fixes a couple cases of undefined behaviour; the use of unprefixed stdint types (via a new config.h); and semicolons after macros that triggered `-Wpedantic` warnings.
=> [RDY] AnimView compliance fixes

CorsixTH/CMakeLists.txt, CorsixTH/CppTest/CMakeLists.txt, CorsixTH/Src/CMakeLists.txt, CorsixTH/SrcUnshared/CMakeLists.txt
*Requires #1550 to be merged first*
Normally I avoid feature branches based on feature branches, but the previous one added a static library we will have merge conflicts with later.
Names all .cpp and .hpp files we use explicitly. This uses a separate file to keep the bloat out of the main CMake list, however I'm open for suggestions if anyone has a better way?
=> [RDY] Make CMake src files explicit

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/queue_dialog.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/vip.lua, CorsixTH/Lua/humanoid_actions/queue.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua, CorsixTH/Lua/humanoid_actions/seek_toilets.lua, CorsixTH/Lua/humanoid_actions/vip_go_to_next_room.lua, CorsixTH/Lua/humanoid_actions/walk.lua, CorsixTH/Lua/queue.lua, CorsixTH/Lua/room.lua, CorsixTH/Lua/rooms/training.lua
This is a change that resolves #1104, and the instance in #441, and #1487
I've used the queue.expected to replace the humanoids_enroute structure which was broken in a few places and included other related changes and fixes to address short falls which existed.
Some are small changes;
queue_dialog - don't direct them to a crash room, and call for staff if room unoccupied
queue (action) - tweaked the must_stand logic - don't need to search for a bench when leaving a room
seek_toilets - not updating the expected count when a patient is expected.
room - the condition around tryFindNearbyPatients
#441 is addressed by assuring the expected count is correctly reflected when redirecting patients from one room to another. Which is also the cause in #1104 of staff meandering in rooms, they are …
=> [RDY] Enroute to queue

CorsixTH/Lua/dialogs/adviser.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/epidemic.lua, CorsixTH/Lua/humanoid_actions/queue.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua, CorsixTH/Lua/room.lua
Contagious patients can't be treated if they are seeking room.
Adviser says with override was basically truncating the entire list down to the existing first message rather than leaving only the override one.
Broken seek is from #1556 I had identified this. Ward in that instance being the diagnostic room.
The setNextAction when the queue is destroyed would leave patients going from drinks machine to bench, as action_queue_on_change_position gets called from the callback process of action_queue_get_soda. Queue:rerouteAllPatients, wasn't a candidate to flag them as not is_in_queue as this had other artefacts.
Patients appearing to leave is to correct #1233 and related #500, #362, #858 and #650
Staff answering calls to another room, will appear as within the room they are in, and allow …
=> [RFC] Some assorted issues

CorsixTH/Lua/humanoid_actions/walk.lua, CorsixTH/Lua/room.lua
3 sort of related fixes here, covering #1087 for staff not unreserving doors as basically given by BrainSample but altered for the protection of tryAdvanceQueue
#791 /#1206 the 'insane patients', get up, go to door, pop loop can occur - tryAdvanceQueue guards against this occuring as canHumanoidEnter does additional checks.
Seems like a good idea to do the same for walk interrupt as well.
Room tryAdvanceQueue protects against when the queue is destroyed and the function still being called. #1462 and other instances where this occurs is because the swing doors are swinging and there is a callback after the stop.
The onHumanoidLeave captures when handyman enter a room, and the queue doesn't pop as the function returns after that whereas later scenarios in that function do call …
=> [RDY] Staff blocking doors

CorsixTH/Lua/dialogs/confirm_dialog.lua
Use the calculated height of the text area to determine the height to
use for the confirm dialog instead of estimating.
Replaces #1539 
Fixes #1536
=> [RDY] Fix the size of confirmation dialogs

CorsixTH/Src/sdl_audio.cpp
When building without audio, this prevents the error
> [ 19%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/sdl_audio.cpp.o
CorsixTH/CorsixTH/Src/sdl_audio.cpp:308:23: error: unknown type
name 'lua_State'
int luaopen_sdl_audio(lua_State* L) {
^
CorsixTH/CorsixTH/Src/sdl_audio.cpp:316:33: error: unknown type
name 'lua_State'
int l_load_music_async_callback(lua_State* L) { return 0; }
=> Move lua includes out of sdl2_mixer section of sdl_audio.cpp

CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_lua_anims.cpp, CorsixTH/Src/th_lua_gfx.cpp
Clang warns about this, are they genuine problems?
> [ 19%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_gfx_sdl.cpp.o
CorsixTH/CorsixTH/Src/th_gfx_sdl.cpp:1107:51: warning: 
comparison of unsigned expression < 0 is always false [-Wtautological-compare]
if (iWidth <= 0 || iHeight <= 0 || iPixelNumber < 0 ||
~~~~~~~~~~~~ ^ ~
1 warning generated.
[ 22%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua.cpp.o
[ 25%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_anims.cpp.o
CorsixTH/CorsixTH/Src/th_lua_anims.cpp:320:13: warning: 
comparison of unsigned expression < 0 is always false [-Wtautological-compare]
if (iAnim < 0 || iAnim >= pManager->get_animation_count())
~~~~~ ^ ~
1 warning generated.
[ 27%] Building CXX object …
=> Fix unsigned integer comparisons

CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/epidemic.lua, CorsixTH/Lua/humanoid_actions/walk.lua, CorsixTH/Lua/room.lua
Fixes the loop as mentioned in #1334
Also addresses what I believe is the two states that could result in the patients entering a room when they should be going home, by unregistering callbacks and not routing the patient between rooms if they are going_home.
Latest commit fixes logic error that occurs during earthquake room crashes, when door.queue is or room itself is not indexable
=> [RDY] Epidemic patient loop reversal

CorsixTH/Lua/languages/french.lua
The level 5 bug was actually when an intern was promoted to doctor. The current version still displays the original "Un des médecins est devenu %s" which caused a segfault in the original game.
Fixes a couple of typos, while we are there.
=> Fix french intern promotion string

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
Adds math.floor to values used in the Annual Report that would be given .0 at the end of their value.
Closes #1615
=> [RDY] Fix for #1615

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua, CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/humanoid_actions/staff_reception.lua
This will fix #1607.
Just changes so the hospitals get displayed in order of hospital index
Fix #1611 resetting announcer state
Fix #1622 persistance callback
=> [RDY] Annual Report sort function, announcer state reset on load and persistance callback for staff reception action

CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/epidemic.lua
Fixes #1619
Actions inside function Epidemic:markForVaccination(patient) were getting triggered outside of vaccination mode. Causes a graphic update for contagious patients without making a call for the nurse to vaccinate.
Function now checks if vaccination mode is on before executing. Tested and working.
=> [RDY] Prevent vaccination actions outside vaccination mode

CorsixTH/Lua/epidemic.lua, CorsixTH/Lua/languages/english.lua
Addition to #1620 that adds an improvement for when the nurse is assigned a patient to vaccinate.
Currently, the nurse has the dynamic info "Just wandering around" when going to vaccinate a patient.
This PR would change her dynamic info to "Vaccinating a patient" in that time frame.
Dyanmic info resets back to normal once vaccination is done.
=> [RDY] Suggestion - Give nurse dynamic info when vaccinating

CorsixTH/Lua/languages/english.lua
Updating CorsixTH's TH install dialogs to match that ISO files can now be used.
**One of the updates has caused a graphical glitch (see below), not sure how to fix**
Needs fixing before can be RDY
=> [RDY] 0.64 - Add ISO References

CorsixTH/Lua/world.lua
Fixes #1634 
Function will call the next earthquake in the level file if available, otherwise it will forcefully make one at random.
Previously this cheat would cause the game to partially break because the function didn't exist.
If it's too late to merge this, I can make another PR to remove the menu option for earthquakes instead.
=> [RDY] Add earthquake cheat function

LICENSE.txt
Fixes #1640 (Windows Installer does not display non-ascii characters properly)
The things we do for Microsoft 🤦
=> Add 'UTF-8 BOM' to LICENSE.txt

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/dropdown.lua, CorsixTH/Lua/dialogs/resizables/new_game.lua, CorsixTH/Lua/dialogs/resizables/options.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/strings.lua
The change in strings.lua affects https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/app.lua#L721 and https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/app.lua#L779 but I'm not sure what to do.
The longer text spills well outside the box, but it looked bad simply widening the background element. How do you want it to look?
=> [RDY] Add English names of languages beside the native name in options

CorsixTH/Lua/app.lua
Fixes #143
This adds the first line to this output when SDL2 is compiled without audio.
> SDL_Init failed: SDL not built with audio support
Notice: Audio system not loaded as CorsixTH compiled without it
=> Make SDL audio optional

CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/dialogs/menu.lua, CorsixTH/Lua/dialogs/place_objects.lua, CorsixTH/Lua/languages/english.lua, WindowsInstaller/config_template.txt
Addresses #826 (first meta issue) first step: "Implement debug flag to allow placing objects that would block off a portion of the map."
- Add a debug config setting "Allow blocking off areas"
- Use the flag to allow building rooms and placing objects even if they block off some area in the hospital or room.
=> Add a flag to allow builds that block off areas.

CorsixTH/Lua/entities/machine.lua, CorsixTH/Lua/entities/object.lua
Would resolve #994 
PR will implement a variable saved_by_extinguisher to each machine/object defaulted at 0.
When machine threshold falls <1, the variable is recalculated by math.random(0,1) to see if an extinguisher in the room will save the room (saved_by_extinguisher == 1 is a success). Variable is saved until the machine is next used (inc. earthquake tick), in which case it sets back to 0.
The addition of self.saved_by_extinguisher may not be needed in object.lua... it was added more as a safeguard.
As for machine_dialog.lua nothing needs to be changed. The health marker in the dialogue is not affected if the number of times a machine is used is higher than its strength.
=> [RDY] Enhancement - Extinguishers reduce chance of machines exploding

CorsixTH/Lua/dialogs/resizables/cheats.lua
- Moves the sound for when a cheat is used into the announcement queue as PriorityCritical. This means it will still play while the game is paused.
=> [RDY] Make cheat.wav announceable

CorsixTH/Lua/announcer.lua, CorsixTH/Lua/entities/humanoids/staff/receptionist.lua, CorsixTH/Luatest/spec/announcer_spec.lua
Closes CorsixTH#1671
Also fixes CorsixTH#1533
- Announcements where a receptionist is not at a desk no longer build up; except for critical announcements that will play regardless (such as cheating, epidemics, earthquakes, and emergencies)
- The announcement for a receptionist leaving will always play
- Announcements can no longer play when the game is paused. Exception again is critical announcements (for cheating; or if a critical announcement was due to play after the current announcement just as you paused).
=> [RDY] Adjustments to announcer

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/dialogs/message.lua, CorsixTH/Lua/dialogs/staff_rise.lua, CorsixTH/Lua/ui.lua, CorsixTH/Lua/window.lua
*Fixes #1625*
- Game will now stay paused when you switch between faxes
- Game also recognises if a staff_rise window is open (and vice versa) and stays paused then too
The function call `` TheApp.world:setSpeed("Pause") `` had to be moved in message.lua to after the new window was made, which was the reason why the game would unpause.
=> [RDY] Switching faxes keeps game paused

CorsixTH/Lua/ui.lua
New code was accidentally causing other dialogs to unpause the game. Didn't notice it when testing #1674 so my fault.
- Now makes sure our closing window is a mustPause() window before we unpause the game.
=> [RDY] Fix bug from #1674 PR

CorsixTH/Lua/graphics.lua
Forces the money bar to use the bitmap font for legibility reasons; until native language numbers are introduced (see #1193 discussion).
- Makes all languages use the bitmap font for moneybar for legibility's sake
- At some point we want to replace this with support for native language numbers (e.g. Korean) but for now this is better than the current improperly drawn moneybar numbers (added a TODO to reflect this)
=> Stopgap solution for #1193

CMakeLists.txt, CorsixTH/CMakeLists.txt, scripts/macos_luarocks
First commit adds the relevant folders of a local luarocks installation to the package.cpath var. The working directory of a process launched as an app is $HOME so no relative path will ever work.
Second commit adds a cmake option to turn on a post build rule, another always on post build rule and some comments edits. The first includes dylibs (dependancies) by copying them in and linking CorsixTH  to them and each other. It's assumed the user installed them by homebrew, others can be added when users emerge. The second script creates a local luarocks installation and patches Luasocket.
Output of osx_dylibs https://travis-ci.org/tobylane/CorsixTH/jobs/119871660#L1255 and osx_luarocks https://travis-ci.org/tobylane/CorsixTH/jobs/119871660#L978
=> [RDY] OS X: Package.cpath and luarocks

LICENSE.txt
* noticed Giordano translation attribution was missing from 2011
* new authors since v0.62:
comm -3 \
<(git shortlog -s v0.62 | awk '{$1="";print}' | sort -u) \
<(git shortlog -s v0.64 | awk '{$1="";print}' | sort -u)
* authors by year:
git shortlog -sne --since=2018-01-01 --before=2019-01-01 v0.62..v0.64
=> update copyright from git history

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/bottom_panel.lua
Change to the moneybar from #1679 needed a version bump to change on existing saves (as noted in https://github.com/CorsixTH/CorsixTH/issues/1193#issuecomment-671020159 )
=> [RDY] Additional requirement for #1679

CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/dialogs/place_objects.lua
mugmuggy said in https://github.com/CorsixTH/CorsixTH/pull/1667#pullrequestreview-464171942
that I shouldn't use `self.world.app` but use `self.ui.app` instead.
Both cases work locally, so I don't know what the preferred solution is, but here goes.
=> Use self.ui.app rather than self.world.app, apparently.

CorsixTH/Lua/announcer.lua, CorsixTH/Luatest/spec/announcer_spec.lua
An update to the announcer to throw unnecessary duplicate announcements already in the queue.
- Increases rate of decay on announcements to be more realistic
- Handles duplicate announcements by refreshing the created_date of the existing one
- Adds a luatest for duplicates
=> [RDY] Handle duplicate announcements

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua, CorsixTH/Lua/hospital.lua
Being rusty on Lua and CorsixTh conventions, apparently.
All initialization calls were broken due to not using a colon. While at it, I renamed the variable as well.
I looked if luacheck (luarocks/luacheck project at gtihub, as lewri found) had support for the colon check and/or for code style of the variables/function names, but it hasn't.
=> [rdy] Fix reputation patch

CorsixTH/Lua/dialogs/fullscreen/town_map.lua, CorsixTH/Lua/entities/humanoids/staff/receptionist.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/world.lua
Added a few hospital methods to make a cleaner distinction between hospital and world responsibilities, although the underlying administration is still not correct for multiplayer.
Also, towards having several hospitals at the same time, reduce confusion between `self` hospital and player hospital, and move a bit further away from having `world.hospitals[1]`. Code isn't even close to done yet though.
=> [rdy] Improved distinction between world and hospital, and between different hospitals.

CorsixTH/Lua/app.lua, CorsixTH/Lua/base_config.lua, CorsixTH/Lua/dialogs/fullscreen/annual_report.lua, CorsixTH/Lua/dialogs/staff_dialog.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/humanoid_actions/seek_reception.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/languages/original_strings.lua, CorsixTH/Lua/room.lua, CorsixTH/corsix-th.6
- Use the two remaining receptionist warnings, add a new string for the other similar event
- Award a trophy, award and bonus for successfully diagnosing and treating everyone
- Use the handyman hint for adjusting attributes, and have it come up once
- Count the windows and add staff happiness based on this. 0.001 is a starting number, it probably needs refining.
- Add staff happiness for larger rooms. This could be expanded, say use the ratio between the room requirements and the actual space as a basis for the factor, if that's realistic.
- --continue=1 will load Autosave1.sav, --continue=true (or any word) will load the youngest Autosav*.sav.
=> Add advisor messages about handymen and receptionists, staff happiness from windows and big rooms, all cured award

CorsixTH/Lua/dialogs/build_room.lua
*Fixes #513 #148*
- When a room is researched, if the build rooms dialog is open then reopen it
=> Reset Build Rooms dialog when new rooms are researched

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/town_map.lua, CorsixTH/Lua/dialogs/watch.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/map.lua, CorsixTH/Lua/world.lua
Fixes #490 
Closes #1345
- Implements the boiler breakdown as described in issue #490
- Code in #1345 did too much, so I implemented it again.
- Adds starting point for a vomit wave disaster, which we don't seem to have yet.
=> [rdy] Rework boiler disasters.

CorsixTH/Lua/ui.lua
*Fixes #1707*
- Makes it so launching a "mustPause" window does not cause blue taint.
=> [rdy] Fix blue taint issue

WindowsInstaller/LanguageStrings.nsh
*Fixes #1710* 's travis failure.
- Sends the language adjustment to the french installer string hopefully to travis this time.
Thanks @mioux for spotting
=> [rdy]French typo fix (resubmission)

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/directory_browser.lua
Somewhat solves #538 and the remainder of #144 by looking in these places for the ThemeHospital folder ~~but not HOSP or other variations. Should it?~~
Can some use of %APPDATA% on Windows help?
Should it have awareness of the demo, or assume players only have one set of data?
Example output:
> Gane data found at: /usr/local/share/games/corsix-th/ThemeHospital
> This will be written to the config file
=> [RDY] Look for game data if location is not set

CorsixTH/Lua/hospital.lua
When placing reception desk while being on pause (and in some other conditions, not sure which), non-existent in class Hospital field game_date causes an exception. The exception in its turn disconnects mouseup handler which makes the game unplayable.
=> Fix reception desk placement on pause

CorsixTH/Lua/announcer.lua, CorsixTH/Lua/world.lua, CorsixTH/Luatest/spec/announcer_spec.lua
*Fixes external use of `world.game_date`
- Replace the last few uses of `world.game_date` by `world:date()`.
- Document the meaning of `world.game_date`.
=> Always query the game date from world:date()

CorsixTH/Lua/app.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
*Fixes emptiness of player hospital
- Moved an advise function from `Hospital` to `PlayerHospital`, and cleaned it up.
In more detail:
- All the functions that merely selected and said an advice removed (called from 1 location and not long)
- A lot of flags were useless, as the advise is given at most once a month (selected by day), and the end of the month cleared the flag again.
- Renamed `checkFacilities` to `daily/monthlyAdvisePlayer`
- Bench checking didn't make much sense.
- It compared with the entire patient population, rather than directly comparing sitting and standing patients.
- It just checked at a some point without tracking the general status (found by Lewri).
- Number of benches is quite irrelevant, the deciding factor is whether …
=> [rdy] Move checkFacilities to PlayerHospital

.travis.yml
*Fixes #1731 
Use a tagged catch2 version instead of a development revision.
=> [rdy] Use catchorg/catch2 v2.13.2

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/town_map.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
*Fixes Move more advice and feedback to the player hospital.
- `cashLow` was previously merged into another function, but not deleted in the original code.
- `countPatients` ran every tick, and was only used just below for generating background noise, and in the townmap.
Now, it's run around 1% of the time for background noise, and has better performance for busy hospitals. Independently, it may also run from the townmap.
- Background noise code is now in player hospital
- Advice code about receptionsists or desks is now in player hospital
- Advice code about plants wrt handman is now in player hospital
- Gates to hell animation code is now in player hospital
Best reviewed one commit at a time.
=> [rdy] Move more advice to player hospital

CorsixTH/Lua/calls_dispatcher.lua, CorsixTH/Lua/entities/machine.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/world.lua, CorsixTH/Luatest/spec/entities/machine_spec.lua
*Fixes #1649*
- Handyman repair announcements now trigger if base strength was >6. Originally they only triggered if base strength was <4
- Also ensures earthquakes don't make the announcer get spammed.
I expect some tidying up needed on this. At the moment this was to get it out of my old test environment.
=> [RDY] Handymen announcements more often

CorsixTH/CMakeLists.txt
*Fixes #1728*
- Minor rearrangement of how CorsixTH_lib is created to avoid a bug, fixed in CMake 3.12, about creating libraries with no files (yet). With this change we can still support CMake 3.5.
=> Create CorsixTH's cmake library with contents

CorsixTH/Lua/dialogs/watch.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/objects/helicopter.lua
*Fixes # nothing in particular*
- Emergency timers are around 50 days, I just made it 52 for the even segmentation for the timer
- Helicopter arrives later, more consistent with the original and the patients spawn slightly further apart, half a day
- The ability for emergency patients to leave due to cost. - Corsix allows you to accept an emergency and increase the cost and patients just pay it. ~~Likewise this change locks the last accepted price in, thus all emergency patients pay the same. These are features of the original.~~ 
- sad_money priority bumped up so shows on refusing to pay emergency patients, but shouldn't on epidemy# ones when they leave (same priority)
- different to the original - if you kick or they refuse to pay - the timer …
=> [RDY] Emergency balance changes

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/hospitals/player_hospital.lua, CorsixTH/Lua/world.lua
Previous feedback in #1722 
- Change the timing of win faxes per the todo
- This then uses the second set of fax texts, which ask the player to reconsider staying at this hospital
=> [RDY] Win fax comes less often after it was declined

CorsixTH/Src/th.cpp, CorsixTH/Src/th.h, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_map.cpp, CorsixTH/Src/th_map.h
- Remove `link_list` inheritance of map_tile for storing entities
- Move `drawing_layer` value to `drawable` struct.
=> [rdy] cpp cleanup of animation data

CorsixTH/Lua/cheats.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/world.lua
Prevent emergencies being available to player if the relevant disease has not been discovered.
*Fixes #1156 Fixes #506*
- Checks if the game's generated emergency disease is discovered at the player hospital
- Where the disease isn't discovered, the emergency is discard
- If the player tried to make an emergency by cheating, they get a nice message instead if it failed.
=> [RDY] Prevent emergencies of undiscovered diseases

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/objects/plant.lua
It doesn't appear much as a departure but you get to visually see the need for watering and watering more often.
Whereas without the change, if you have a well staffed hospital, you might not see any transitions with 10 remaining days check.
I've scaled the happiness change, but note this only searches with a distance of 2, so probably largely unaffected in many rooms/corridors as it also only occurs once per day.
Transitions with the temperature change occur within 39-67 days, without the change, it was 49-75 (TH uses constant 50).
setNextState change just gives 5 states (animation frames), instead of 6 as its zero based.
=> [RDY] Plants have an affect

CorsixTH/Lua/hospital.lua
- Noticeably on level 5 they can be seen before closing the starting message. Previous feedback in #1722
=> [RDY] Place initial staff in a level randomly around the starting tile

CorsixTH/Lua/dialogs/confirm_dialog.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/window.lua
- Blue filter was going on top of the ConfirmDialog error messages when they actually should be a mustPause() window.
- humanoid no longer pauses the game on these messages -- all handled by Window.
=> [RDY] Stop blue filter on UIConfirmDialog

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/entities/object.lua, CorsixTH/Lua/objects/door.lua, CorsixTH/Lua/objects/doors/entrance_right_door.lua, CorsixTH/Lua/objects/helicopter.lua, CorsixTH/Lua/objects/litter.lua, CorsixTH/Lua/objects/plant.lua, CorsixTH/Lua/objects/rathole.lua, CorsixTH/Lua/objects/reception_desk.lua, CorsixTH/Lua/world.lua, CorsixTH/Luatest/spec/entities/machine_spec.lua, CorsixTH/Luatest/spec/entities/object_spec.lua
- Previously, objects just lived in 'world', and sometimes used `world:getLocalPlayerHospital()` or `ui.hospital` for hospital access.
- This patch gives all objects a hospital reference of their own.
- Currently, the used hospital is always `world:getLocalPlayerHospital()`
*Other changes*
- Door deadlock resolve code didn't output anything which may be useful, so added that.
- Object creation code used continue magic, which was eliminated.
=> [rdy] Objects belong to a hospital

CorsixTH/Lua/world.lua
- Free mode disables salary raise requests, but it was reset.
=> [rdy] Do not override free mode salary raise disabling.

CorsixTH/Lua/ui.lua
Fixes #1774
Guards against condition where a window opens but there is no world because we are in the main menu.
=> [RDY] Guard against world not existing when opening a window

CorsixTH/Lua/entities/object.lua, CorsixTH/Lua/objects/doors/swing_door_right.lua
*Fixes Swing doors crash:
```
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
CorsixTH/Lua/objects/doors/swing_door_right.lua:45: attempt to call a nil value (method 'getObject')
stack traceback:
CorsixTH/Lua/objects/doors/swing_door_right.lua:45: in local 'timer_function'
CorsixTH/Lua/entity.lua:216: in function <CorsixTH/Lua/entity.lua:193>
(...tail calls...)
CorsixTH/Lua/world.lua:1065: in method 'onTick'
CorsixTH/Lua/app.lua:1127: in function <CorsixTH/Lua/app.lua:1124>
(...tail calls...)
CorsixTH/Lua/app.lua:1027: in function <CorsixTH/Lua/app.lua:1022>
Error in timer handler:
```
=> Missed the swing door and a constructor in 23582e74

CorsixTH/Lua/languages/spanish.lua
Use more generic ``Español`` for Spanish rather than ``Castellano``.
After speaking with @LloydJara in the CorsixTH Discord it was determined that the original Spanish translation files were made generic to be understood by as many variations of the language as possible. As such, Castellano refers generally to "Spain Spanish" than a general Spanish.
=> [RDY] Change spanish language name

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/dialogs/menu.lua, CorsixTH/Lua/dialogs/resizables/new_game.lua
*Fixes #1534*
Previous feedback #1739 
- Play the advance level board movie after the level is loaded only when - a new game is played, a new level is started, or the level select in the debug menu is used. Avoids playing the movie on a level restart.
=> Skip the level board movie on level restart

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/customise.lua, CorsixTH/Lua/dialogs/resizables/options.lua
- Prevents the button up error when changing global audio setting without audio in the build.
=> [RDY] Disable changing audio or movie settings when compiled without audio

CorsixTH/Lua/dialogs/jukebox.lua
- Prevents a buttonup error when you try to loop an empty list of music.
=> [RDY] Handle a music directory without music files

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/load_game.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/persistance.lua, CorsixTH/Lua/world.lua
- Completing a TODO to prevent newer saves opening in older games.
- This change will only have a real effect post savegame 152.
- Also saves the savegame_release version to world so an old game knows where the newer save came from (for compatibility it uses Trunk as fallback/nil). 
- Allows saves to be opened in debug but shows a similar warning.
When debug is on: (NB: updated 29/12)
When debug is off: (NB: updated 29/12)
=> [RDY] Forbid loading new saves on old versions when outside debug

CorsixTH/Lua/ui.lua
*Fixes #525 *
- Deletes the existing screen movement when loading a world.
=> [RDY] Cancel any saved screen movement from edge scrolling

.github/workflows/Linux.yml
Possibly fix issue downloading latest cmake.
*Fixes #1802*
=> [RDY] Bump actions-setup-cmake to 1.6

CorsixTH/Lua/app.lua, CorsixTH/Lua/hospital.lua
Complementary PR to #1754 to allow for emergencies that slip through the net from old saves to be course-corrected.
For clarity, I tracked down the savegame version that 1754 sat on and adjusted the afterload's old number as necessary.
*Closes #1799*
- Afterload added for emergencies of undiscovered diseases in old saves that are active to prevent the casebook bug fixed by 1754
- In above case, the disease is automatically discovered to prevent crashing (too late to try and cancel the emergency now!)
=> [RDY] afterLoad for emergencies with undiscovered diseases

AnimView/frmMain.cpp, AnimView/frmSprites.cpp, AnimView/th.cpp, AnimView/th.h
*Fixes #1811*
Resolves undefined behavior by shifting unsigned longs.
clang-tidy suggested removing the unused assignment to pTmp, and fixing the name _merge (underscore names are reserved). I moved to using anonymous namespaces for file local code, per the c++ guidelines / style in CorsixTH
=> Animview overflow

CorsixTH/Lua/dialogs/menu.lua
*Previous feedback #1739, fixes #1311*
- Saves all menu bar setting changes when the dropdown menus go away (a second after the cursor goes off them)
=> [rdy] Save settings from ingame menu when menu closes

CorsixTH/Levels/avatar.level, CorsixTH/Levels/confined_v5.level, CorsixTH/Levels/demo.level, CorsixTH/Levels/example.level, CorsixTH/Levels/finisham.level, CorsixTH/Levels/st.peter's.level, CorsixTH/Lua/base_config.lua, CorsixTH/Lua/hospitals/ai_hospital.lua, CorsixTH/Lua/world.lua
*Previous feedback #1741*
- Use competitor names if set in the level config
- Minor edit to the level files to use the names already included
=> [RDY] Use competitor names from level configs

CorsixTH/Lua/hospital.lua
Previous feedback #1722 
- Picks three insurance companies, keeping the preference for early ones, from the full range in the language file.
=> [RDY] Select insurance companies from all available company names

CorsixTH/Lua/dialogs/resizables/lua_console.lua, CorsixTH/Lua/ui.lua
After executing a debug script the global _ must be cleared to avoid corruption in a save.
Better solution to #1836
There's questions why ``strict_declare global "ui"`` exists but I don't want to really go into touching that.
=> [rdy] Clean up global _

CorsixTH/Lua/app.lua, CorsixTH/Lua/world.lua
*Fixes #1839*
- nextEmergency code will now more decisively schedule the next emergency
- New functions separate the random emergency scheduling from controlled emergencies
- Should an emergency end up scheduled in the past, the code will attempt the next emergency
- A complementary afterLoad has been added to try and fix any previous saves where emergencies got "stuck" because they were scheduled in the past. There isn't a guarantee this will work and has a small risk of skipping an emergency.
Ideally I need to make a separate PR to handle ``cheatMonth()`` and ``cheatYear()`` as these can break emergencies (and other things).
=> [RDY] Rework Emergencies

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/update.lua
- Add the two github urls to the trusted domains. This fixes the updater
- Add a different open command for macOS, fixing it on that platform
- Add the requirement for the given download url to be https. This will break the ability to update, can you convert the url?
- When the user doesn't have luasec warn them
I'm not sure on the usefulness of the third and fourth commits. http://github.com is a redirect to https, so this only protects interference local to the user? If the package doesn't have luasec it's just an unhelpful nag? We may do better just asking packagers to add luasec if they've added luasockets to the dependencies.
=> [RDY] Fix updater

CorsixTH/Lua/dialogs/bottom_panel.lua, CorsixTH/Lua/dialogs/jukebox.lua
- User can't open the jukebox if audio is disabled
- Will close jukebox if it was left open in a save where audio was enabled
=> [RDY] Disable/close jukebox when audio is disabled

CorsixTH/Lua/hospitals/player_hospital.lua
Previous feedback #1739
- Uses two strings to warn the user of long queues. I chose to define long as 6+, and to check monthly. Do we know what TH97 does?
=> [RDY] Add advisor warnings for room queues

CorsixTH/Lua/world.lua
- Cheating to end of Month or end of Year will no longer break emergencies.
- Relies on #1843 to be merged
=> [RDY] Date Skipping won't break emergencies

CorsixTH/Lua/app.lua, CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/persistance.lua, CorsixTH/Lua/world.lua
*Fixes #470*
- On failing to write to the intended save game file it saves to a temp file and tells the user
=> [RDY]Save to OS temp directory if the intended file can't be written to

CorsixTH/Lua/app.lua, CorsixTH/Lua/base_config.lua, CorsixTH/Lua/hospital.lua
*Previous feedback #1722, #1741*
- Reputation and the overdraft interest differential can be set in levels
- Change interest and overdraft interest to a number over 10,000. Consistent with how it's set in levels.
=> [RDY] Use initial reputation and overdraft interest rate if set in level config

CorsixTH/Lua/dialogs/fullscreen/staff_management.lua, CorsixTH/Lua/dialogs/staff_dialog.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/entities/humanoids/staff/doctor.lua, CorsixTH/Lua/entities/humanoids/staff/handyman.lua, CorsixTH/Lua/entities/humanoids/staff/nurse.lua, CorsixTH/Lua/entities/humanoids/staff/receptionist.lua, CorsixTH/Lua/hospital.lua
*Fixes #1838*
- Use staff.profile to avoid inline class conversions, for Surgeons
- Reuse fulfillsCriterion function to support counting staff Category
fulfillsCriterion seemed to only really be used for flow of logic when a room was in scope in the calls dispatcher where a room is in scope or a room calling it within its methods so Receptionist seems safe to implement.
=> [RDY] Deal with staff attribute checks

CorsixTH/Lua/entities/humanoids/patient.lua
*Closes #1829*
- Service Quality now considered in treatment. As realistically the fatigue/skill etc or the doctor/nurse can affect effectiveness of a cure.
- Service Quality will only have a small impact cure_chance to not become unbalanced. Though now has a higher impact where cure_chance is lower, and less when higher.
Just a side note, inside staff_profile we actually set the midpoint as skill 0.55; should we copy that here too with service quality's midpoint?
=> [RDY] Service Quality affects treatment

CorsixTH/Lua/dialogs/bottom_panel.lua, CorsixTH/Lua/dialogs/message.lua, CorsixTH/Lua/ui.lua, CorsixTH/Lua/world.lua
*Fixes #1715*
<s>I haven't tested this with staff rise windows yet...</s> works fine. so if anyone is able to tell me something's wrong let me know. Hopefully I've added functions in the right place for once.
- Prevents fax and staff rise windows being opened on pause where editing is not allowed.
- Added a "wrong2" sound when player tries to click on a message icon when not allowed.
- If the game gets paused because of a fax, then you can still switch between faxes as before.
=> [RDY] Stop faxes being openable on pause

CorsixTH/Lua/app.lua
*Fixes #1857 *
In App:checkInstallFolder
- Use windows variables correctly, without the %
- Use HOMEPATH as Window's HOME
- Add two more paths for macOS based on the app's location, which will be useful when the app is portable
=> Fix Windows home path, add macOS app path to search for game data

AnimView/CMakeLists.txt, CMakeLists.txt, CorsixTH/CMakeLists.txt
*Fixes #1816 *
- Add the sanity check CorsixTH/CMakeLists.txt uses
- ~~Add BUILD_ANIMVIEW, which mirrors BUILD_ANIMVIEWER. This does mean if the user has one of the two values cached with ON, and set the other as OFF in the cmake command it will still build it. This only happens because the user deliberately changes what they use, and it'll show up as if they wrote ON. Solvable with checking caches, but I don't think it'll surprise anyone at build time.~~
- Rename build_animviewer to build_animview in CMake build options.
=> [RDY] Change BUILD_ANIMVIEWER to BUILD_ANIMVIEW and add sanity check in AnimView cmake

CorsixTH/Lua/humanoid_actions/queue.lua, CorsixTH/Lua/queue.lua
*Fixes #1645*
- Checking increment_reported_size prevents changes to the queue order when its already been determined from previous priority - staff leaving the room will not move in front of a patient also leaving the room
- Before checks extended to include the priority from the previous checks - if a staff member is entering a room and a staff member and patient are queued to exit, the entering staff member will not move ahead of the leaving patient.
The Vip and Inspector don't actually queue at the moment, they just arrive at the door tile. They do at reception though, but emergency patients probably shouldn't but could go to reception I guess on some rare cases, and staff don't use it either, but the logic should be ok in those cases.
=> [RDY] Maintain queue push-priority order

README.md
*Fixes #1416*
- Add a link to Flathub so that users can install the Flatpak from there.
- I also edited [the Getting Started wiki page](https://github.com/CorsixTH/CorsixTH/wiki/Getting-Started) with the same link.
=> Readme: Advertise the Flatpak

CorsixTH/com.corsixth.corsixth.metainfo.xml
Providing the old app ID prevents app stores from showing duplicate entries if some sources still use it.
=> Metainfo: Provide the old app ID

CorsixTH/SrcUnshared/main.cpp
This order is particularly important on wayland.
Fixes #1869
-
=> [RDY] Destroy SDL after destruction of lua owned objects

CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua
*Fixes #1668*
- Seek Room fixes the #1668 scenarios
- Game UI fixes a scenario that was mentioned in #1799 - where editing an operating theatre, patient on the walk to the room, mark room for edit, requeues a SeekRoom action. SeekRoom queues a meander. If the room doesn't become available for editing (waiting cursor still active) when the SeekRoom action restarts after the meander, and the edit is cancelled whilst still waiting for the room to clear, the notifyNewRoom callback doesn't get called. Patient goes into limbo until they perform some other action.
=> [RDY] Seek fixes

.github/workflows/Linux.yml, CorsixTH/Src/config.h.in
GitHub removed clang-9 as part of their last 3 version policy so we are forced to bump.
The documentation seemed mixed on support for 12. In my tests it wasn't available for clang-tidy so I've opted to go with 11 (which is their new default as well.)
=> [RDY] Bump clang version to keep up with GitHub

CorsixTH/Lua/app.lua
The macos directories were inserting nulls in the array which ipairs
would stop on without iterating through all options. Fixed by replacing
with empty strings. \\ directories in the search caused considerable
pause in windows and were invalid, so skip checking them. Add up to date
"GOG Games" folder which has been the default for awhile now.
This was a somewhat recent regression. Please test non-Windows OSs to ensure I didn't break anything (remove your config.txt and run, with/without a hospital directory that can be located.)
=> [RDY] Fix the search for Theme Hospital installs on Windows

CorsixTH/Src/th_movie.cpp, CorsixTH/Src/th_movie.h
*Fixes #1890*
- The only call to the now deprecated av_init_packet() was specific to an old path, so ifndef that out unless we are on very old FFMpeg versions
- The use of AVPacketList is still fairly critical and my attempts to replace it with modern collections tended to spiral. As a short term fix for the 0.65 release, implement our own struct with the same layout as AVPacketList as a drop in replacement.
=> [RDY] Avoid using recently depreacted FFMpeg functionality

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/bottom_panel.lua, CorsixTH/Lua/dialogs/confirm_dialog.lua, CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/dialogs/fullscreen/staff_management.lua, CorsixTH/Lua/dialogs/machine_dialog.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_game.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_map.lua, CorsixTH/Lua/dialogs/resizables/main_menu.lua, CorsixTH/Lua/dialogs/resizables/options.lua, CorsixTH/Lua/dialogs/staff_dialog.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/world.lua
Alternative to #1867
*Fixes #1865*
- Adds a parameter to UIConfirmDialog to declare if the window is due to an error or not
- If it is an error, a pause is forced
- Game will not unpause until error is dealt with
=> [RDY] Handle errors in confirm dialogs

CorsixTH/Src/th_gfx_font.cpp, CorsixTH/Src/th_gfx_sdl.cpp
First commit fixes #1902 - a crash on the directory dialog with some languages
Second commit significantly improves the rendering of vector fonts by enabling grayscale (subpixel) support.
=> Fix #1902 - invalid code points at end of string

CorsixTH/Lua/persistance.lua
- In IRC it was reported Autosave1 was loading in with blue tint. This PR changes the checks on when persistance should apply the taint on load.
=> [RDY] Improve blue tint handling at load

CorsixTH/Lua/app.lua
Search USERPROFILE as the closest equivalent to HOME. Search HOMEDRIVE..HOMEPATH if different from USERPROFILE.
Fixes #1916
=> [RDY] Always prefix HOMEPATH with HOMEDRIVE

CorsixTH/Lua/app.lua, CorsixTH/Lua/config_finder.lua, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h, CorsixTH/Src/th_lua_gfx.cpp
This allows removing the zoom texture allocations and removing an intermediate draw to that texture before drawing to the screen noticeably increasing the frame rate which may address issues such as #1420.
=> Implement zoom using scaled SDL_RenderCopy.

CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/entities/humanoids/staff/doctor.lua, CorsixTH/Lua/entities/humanoids/staff/receptionist.lua
*Fixes #1924*
Does not nil out the fatigue attribute of doctor's when they are fired. Avoid performing any actions on fired doctors.
=> Fix fired dr

CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
*Fixes #1927*
- Only considers active rooms when calculating the queuing situation.
I think this is because a crashed room's door queue is not always instantly wiped, as patients move to other rooms. It happened when my first operating theatre exploded but not the second.
=> Fix warn queue check considering inactive rooms

CorsixTH/Lua/audio.lua
*Fixes #1906*
- There are two return paths that assume these values should not change, if the sound file is not changed also.
=> [RDY] Fix audio on language change

CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/world.lua
This creates the hotkey with default 0 to reset the current zoom as listed on https://github.com/CorsixTH/CorsixTH/wiki/Programming-Ideas#graphical-scaling
=> Implement reset zoom hotkey.

CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/rooms/training.lua
- Allow handymen to move around at their regular speed in training rooms -- as per the original game.
=> [Rdy] Training room speed adjustment

CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h, CorsixTH/Src/th_lua.h, CorsixTH/Src/th_lua_gfx.cpp
- Introduces the `max_number_of_layers` constant (mostly cherry-picked from driverpt)
- Further reduces layer count magic numbers
- Removes Replaces the `link_list` base class, and replaces it with a `std::vector`
- Renames `line` to `line_sequence`, `line_operation` to `line_element`, `line_operation_type` to `line_command`
- Ensures persistence will always write the float data as `double`.
=> Add layer constant, refactor line class

CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_map.cpp
*Mostly fixes aliased rendering issues in #1930*
- Applies SDL_HINT_RENDER_SCALE_QUALITY nearest only to map textures
Note:
- We could now also make direct_zoom a runtime configurable parameter as long as we reset the global_scale_factor and zoom_texture accordingly.
**Screenshot:**
=> Only apply nearest scaling to map textures for direct_zoom.

CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h
*In combination with #1931 this fixes #1930*
- Initialize and use an intermediate screen sized buffer when in fullscreen.
Note that this still has the advantage over indirect zoom that the buffer will always be screen-sized, rather than growing larger as you zoom out so it should still should fix the original crash issue that direct_zoom fixed with hopefully full parity in render quality.
**Screenshot:**
=> Use intermediate screen-sized buffer for direct_zoom

CorsixTH/Src/th_map.cpp
*Fixes #1929*
This change draws each floor shadow immediately after the floor tile.
By drawing the floor shadows immediately after drawing the floor tile we ensure that no pixel is shaded by shadow twice, as if it would be it would first be covered by the adjacent floor tile if there will be overlap.
=> Draw floor shadows immediately after floor tiles

CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
- When holding down (default) x you can now buy plots, and their walls have transparency applied.
- Only warn about insufficient money for the local hospital trying to buy plots.
=> [RDY] Fix purchasing plots when walls are transparent

CorsixTH/Lua/utility.lua
- Document how to use the 'serialize' utility function.
- Enable cycle detection by default to avoid crashes on infinite
recursion while serializing.
=> 'serialize' enhancement: Do not crash on cycles.

CorsixTH/Lua/app.lua, CorsixTH/Lua/config_finder.lua
Sets the default value of direct_zoom to nil which is now interpreted as being enabled. direct_zoom provides a significant rendering performance improvement and a reduction in crashes on low end systems. It also supports zooming on systems which don't support target textures.
=> Turn direct_zoom on by default.

CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
- Only advise the local hospital of the price level impacts.
=> [RDY] Make computing price impact warnings local player specific

CorsixTH/Lua/utility.lua, CorsixTH/Src/th_gfx_sdl.cpp
*Fixes #1946 *
- Implements a rendering of the jellyitus effect by splitting the drawing of sprites up into multiple slices which are each offset horizontally by an animating sine wave.
=> Implement jelly rendering effect.

CorsixTH/Lua/dialogs/resizables/cheats_dialog.lua
*Fixes #1647*
- Moves the time we call ``setDefaultPosition`` on UICheats to account for dynamically added panels and buttons.
- This means that the window will always stay on screen when it recalls previous position.
=> [RDY] Stop cheat menu slide

CorsixTH/Lua/diseases/jellyitis.lua, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h
- Adds an effect offset per animation so that patient effects are not in sync.
- Only applies jellyitus for the first M out of every N frames.
=> Make jellyitus effect intermittent.

CorsixTH/Lua/hospitals/player_hospital.lua
- Fixes the inaccessible main part of PlayerHospital:checkReceptionAdvice. It was behind a check for a staffed desk and a check for no staffed desk.
=> Adjust the reception advice call

CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua, CorsixTH/Lua/research_department.lua
- Disease discovery fax and casebook updates are local player only.
=> Make disease discovery advice local player only

CorsixTH/Src/th_gfx_sdl.cpp
*Fixes #1953*
- When using SDL 2.0.10 or newer, uses SDL_FRect and SDL_RenderCopyF to improve scaling precision.
- When using SDL 2.0.9 or older, uses SDL_Rect and the enclosing integer SDL_Rect for compatibility.
=> Use SDL_RenderCopyF on SDL 2.0.10 and newer for better scaling

CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
- Add PlayerHospital:makeAnnouncement, a copy of giveAdvice adapted for announcements
- Fix plots being unbuyable when walls are transparent
- Add checks for local hospital before telling user
- Move no receptionist advice away from check for receptionists
=> Boiler breakdown advice is local player only

AnimView/frmSprites.cpp
*Fixes #1750*
- Use wildcards for file system case insensitivity in the Animview file select dialogs.
=> Fix case insensitive file selection in Animview

CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
- The adviser message for a staff member threatening to resign could occur without the staff member actually making a raise request
- Moves it below the "timidness" check so it will now only execute if they are successful.
=> [RDY] Move advisor check on raise request

.github/workflows/Linux.yml, CMakeLists.txt, CorsixTH/CMakeLists.txt, CorsixTH/Lua/api_version.lua, CorsixTH/Lua/app.lua, CorsixTH/Lua/world.lua, CorsixTH/Src/config.h.in, CorsixTH/Src/th_lua.cpp
*Previous feedback #1722*
- Move the game log from world to app
- Log all available info to the game log, fix #1633, example
> Compiled with api_version: 2679, arch_64: true, os: macos, audio: false, 
Renderer: SDL, metal
Lua 5.4 run with game version: Trunk, savegame version: 152, api version: 2679
=> Put system information at the start of gamelog.txt

CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h
- Creates a scoped target texture class to replace required explicit begin / finish and init / flush function calls.
- Uses this class for both the zoom buffer and intermediate draw buffer.
- Remove obsolete methods replaced by class constructor / destructor.
=> Create scoped class for temporary allocation and commit of textures.

CorsixTH/Lua/dialogs/resizables/dropdown.lua
*Fixes #553*
- When you click outside a dropdown it will now automatically dismiss.
=> Let dropdowns close when clicked outside of

DoxyGen/animview.doxygen.in, DoxyGen/corsixth_engine.doxygen.in, DoxyGen/leveledit.doxygen.in
- Revert a small portion of #1971 by putting the no dot line back in. Perhaps it won't be needed when doxy 1.9 is in Ubuntu LTS.
=> Re-add doxygen config line for no dot

CorsixTH/Src/th_gfx_sdl.cpp
*Fixes #2007 *
- Increases the drawn size of scaled sprites slightly in order to eliminate missing pixels between tiles.
Before:
After:
=> Overdraw scaled sprites slightly to ensure no gaps, fixes #2007.

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/humanoids/staff/receptionist.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua, CorsixTH/Lua/humanoid_actions/seek_reception.lua
- Eliminate 'self.receptionist_msg' (again).
- Move first-desk advice to the player hospital.
- Move queue advice with reception when having several desks and/or receptionists to player hospital.
=> Move 'receptionist_msg' removal to Hospital.

CorsixTH/Lua/dialogs/resizables/options.lua, CorsixTH/Lua/ui.lua
*Fixes #1955*
- When using the fullscreen hotkey, the fullscreen button will now update if the Options menu was option.
- The solution feels a little janky, but happy to accept other ideas.
=> [RDY] Fullscreen Hotkey updates options button

CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/entities/humanoids/staff/doctor.lua, CorsixTH/Lua/objects/plant.lua
- Promotions, thirsty plants and falling patients are advised of in local hospitals only. Patients falling is disabled (and should be) so that part isn't tested.
=> Local hospital advice

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/entities/humanoids/staff/doctor.lua, CorsixTH/Lua/entities/humanoids/staff/handyman.lua, CorsixTH/Lua/entities/humanoids/staff/nurse.lua, CorsixTH/Lua/entities/humanoids/staff/receptionist.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua, CorsixTH/Lua/room.lua
Move to player hospital:
- Advice for staff entering a room they can't staff or sit at a desk
- Announcements for sacking staff
=> Move staff advice/announcements to player hospital

CorsixTH/Lua/humanoid_actions/seek_reception.lua
*Fixes #372*
- Walk is truncated to a distance of 6 tiles away from the reception desk use tile.
- Updates walk actions destination tile to that of the truncated walk (incase of vomit)
=> [RDY] Add to reception queue only when near reception #372

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
*Fixes #2032*
- Adds a helper function to make sure we represent awards with whole numbers only.
Only question is should it be in utility? If it is meant to be utility, it would need more documenting for use cases.
Edit: I don't think this calls for an afterload really. It would fix itself in the next annual report anyway.
=> Remove .0 from negatives in Annual Report

CorsixTH/Lua/app.lua
*Fixes #2040*
- github.io is causing a 301 permanent redirect.
- Bear in mind this does mean trying to update 0.65 to 0.66 through the application won't work.
=> Update URL for checking updates

CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/dialogs/machine_dialog.lua, CorsixTH/Lua/entities/machine.lua, CorsixTH/Lua/languages/english.lua
*Fixes #2049*
- Adds extra information to the replace machine dialog (current machine strength and new machine strength)
- Made into a config setting. But later down the line should likely form part of a QoL settings menu.
- Also moves the hospital spend money line into the `replaceMachine()` function in Machine (renamed from `machineReplaced()`.
- Game pauses on the confirmation dialog -- so a machine can't explode while replacing it.
=> Extra info on replacing machines

CorsixTH/Lua/app.lua
*Fixes #1810 #2048*
- Adds the savegame dir to the to quickload
- Adds a file extension `.qs` -- though that's more personal preference not liking an extensionless file.
=> Fix Quick Save/Load

README.md
Has now been 4/5 months since the migration. No issues reported about this and seems that almost everyone has moved to Discord or Matrix. Suggest to remove notice.
=> Remove IRC Notice

AnimView/CMakeLists.txt, CMakeLists.txt, CorsixTH/CMakeLists.txt
Minor convenience for Visual Studio users.
If CorsixTH is built, set it as the startup project for the top level
sln
Set CorsixTH as the startup project for the CorsixTH.sln
Set AnimView as the startup project for the AnimView.sln
=> Set startup project for Visual Studio

CorsixTH/Lua/dialogs/adviser.lua
*Fixes #2067*
- Messages sent to the adviser are now checked for duplicates already queued. Unfortunately if the same message is already up we skim over that one.
- Obeys the override request as it clears the queue anyway (out of scope here but that sounds like bad behaviour)
=> Add duplication checker for Adviser

CorsixTH/Lua/config_finder.lua
**Fixes**
- uses the user's own settings instead of the default ones
=> Reading config_values instead of default_values - Issue 1993

CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua, CorsixTH/Lua/objects/door.lua, CorsixTH/Lua/objects/reception_desk.lua, CorsixTH/Lua/queue.lua, CorsixTH/Lua/room.lua
At a few points, actions were created as tables with properties rather than by instantiating the required class.
This patch fixes that.
Note that 41b3d1dee77a9393713589ca9c9fd50389e255e2 makes a mess in patient.lua due to whitespace changes.
=> Use proper actions (hopefully) everywhere

CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua, CorsixTH/Lua/staff_profile.lua, CorsixTH/Lua/world.lua
Remove duplicates of translating staff type-names to human-readable names.
=> Deduplicate staff-type name translations.

CorsixTH/Lua/app.lua, CorsixTH/Lua/humanoid_actions/knock_door.lua, CorsixTH/Lua/humanoid_actions/walk.lua, CorsixTH/Lua/world.lua
Moving code into the KnockDoor class instead of having it in a number of functions.
As such, this also functions as a sort-of (simple) example for the path I have in mind.
Adding the 'humanoid' parameter to the actions should be doable after #2086 . Obviously it should go into the base class eventually.
While this action works, I currently don't know if all the other actions can be converted.
The 'start' callback can quite easily be removed after merge of #2084 .
The 'tick' callback should be removable too, since the humanoid acts as entry point for the timer of the animation.
=> Knock door rewrite

CorsixTH/Lua/entities/humanoid.lua
Make the `Humanoid_startAction` a normal `Humanoid:startAction` method.
Also, move empty action queue handling to its own method to reduce clutter in starting actions code.
=> Humanoid start action move

CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/languages/czech.lua, CorsixTH/Lua/languages/dutch.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/languages/german.lua
An extension to CorsixTH#2084.
- Moves the raw string for the empty action queue error into the english.lua file, to enable translation.
- Czech (thanks to @jansakos ), Dutch (thanks to @Alberth289346 ), and German (thanks to @NettleSoup partner) translation also added.
=> Make empty_action_queue error translatable

CorsixTH/Lua/dialogs/resizables/cheats_dialog.lua, CorsixTH/Lua/world.lua
*Fixes #2102*
- Allows the player to utilise the cheats menu if it was opened via fax code. For simplicity, allow behaviour if any fax is open.
- Also prevents a blue filter if unpausing on a fax, then pausing again.
One day I'll get this all right
=> [rdy] Allow cheats menu use from fax

CorsixTH/Lua/audio.lua, CorsixTH/Lua/ui.lua
*Fixes #None*
- If you start with a smaller windowed game and increase the size, the sound effects outside the original centered window size won't play. This just recalls the function to calculate the camera size again
=> [RDY] Recalculate sound effect boundary on resolution change

CorsixTH/Lua/rooms/fracture_clinic.lua, CorsixTH/Lua/rooms/inflation.lua, CorsixTH/Lua/rooms/slack_tongue.lua, CorsixTH/Lua/rooms/ultrascan.lua
*Fixes #1926*
- As discussed in the issue, puts the workaround dealing with the action queue changed when multi use object ends
=> [RDY] Fired staff handling for multi_use objects

CorsixTH/Src/th_movie.cpp, CorsixTH/Src/th_movie.h
AVCodec* was made const in lavc 59.0.100 and lavf 59.0.100
*Fixes #2109*
=> Support ffmpeg 5

CorsixTH/CorsixTH.lua, CorsixTH/Lua/app.lua, CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua, scripts/generate_windows_config.lua
*Fixes #2082*
Currently, the `app:fixConfig` and `app:fixHotkeys` functions were using the config.txt values as default.
This patch now points them to actually use the default values in our lua files.
This touches some files outside my usual scope. Let me know if I need to add anything else for those changes.
=> Make app:fixConfig and app:fixHotkeys use defaults

CorsixTH/Src/th_lua_sound.cpp
*Fixes #* 
- Fix buffer overflow 
- Potentially addresses #1380, was also some older bugs (still bugs?) where lava hole spawns but not accessible by Grim, which would also accelerate the overflow as the lava hole stays spawned.
=> [RDY] Fix buffer overflow of played_sound_callbacks_ids

CorsixTH/Lua/entities/humanoids/patient.lua
*Fixes a bug from #2094 *
- Can pee or puke check dropped the name effectively disabling it and also moved the table outside the function
=> [RDY] Fix broken canPeeOrPuke

CorsixTH/Lua/entities/humanoids/patient.lua
*Fixes #1173*
- During epidemics patient info don't update correctly as per #1173
- Prevent patients becoming fed up and leaving when in a room, also mentioned in the same issue
=> [WIP] Fix dynamic info updates during epidemics

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/entities/humanoids/staff/doctor.lua, CorsixTH/Lua/world.lua
Update to luacheck now includes warnings for negation.
This addresses those, but needs to be checked that none of these changes break anything.
@colinjmatt could you check that OSX behaves correctly with the change to `world.lua` for the `pathsep` check?
=> Fix Negation Errors

CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
*Fixes #2121*
- Changes the tooltip on ZoomKeys to the correct string
=> Fix hotkey tooltip

.github/workflows/Linux.yml, .github/workflows/update-website.yml
Bump GitHub Actions to their latest major versions. Main change is they're now using Node 16 instead of 12, which is EOL at end of month.
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `peter-evans/repository-dispatch` can be [found here](https://github.com/peter-evans/repository-dispatch/releases)
=> ci: bump github actions

CorsixTH/Lua/app.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/world.lua
*Fixes that tile object counts make sense if you have more than one hospital.
- Instead of a world-centric tile object count administration, defer counting to the hospital(s) that own the object(s).
- Hospital now returns its own reception desks.
- Also fixes an edge problem of warning patients of a (very) nearby hospital on object placement.
=> Hospitals store their tile object counts.

CorsixTH/Lua/epidemic.lua
Infection outside the hospital could cause a player to unfairly lose an epidemic by infecting a kicked/fed up/too pricey patient outside the hospital grounds.
For sake of fairness as discussed, they should remain able to be infected while in the grounds.
*May fix #2129*
- Adds a check on the infected patient and the target patient to make sure both are inside hospital grounds to pass the infection.
=> Prevent epidemic infection outside hospital

CorsixTH/Lua/app.lua, CorsixTH/Lua/humanoid_action.lua
*Fixes #2142 
- When the Knockdoor Action is being animated at the time of save, the state variable is never created and the callback at the end of the animation cannot find the next step to perform.
- Fixed by initializing the state to point to that next step. If the action was not running, the `start` calll will initialize state variable, overwriting the fix value.
=> Fix knockdoor action in flight.

.luacheckrc, CorsixTH/Lua/objects/door.lua, CorsixTH/Lua/rooms/research.lua
- Move two helper functions to the one place they're used. 
- Add the staff initials cache to globals list
- Add the two call parent afterloads that are missing, I haven't seen this as a problem in game but the change makes it consistent with the others - https://grep.app/search?q=afterload&filter[repo][0]=CorsixTH/CorsixTH&filter[lang][0]=Lua&filter[path][0]=CorsixTH/Lua/
Each of these could be instead left as is with luacheck ignores
=> Minor fixes related to luacheck

CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/entities/humanoids/vip.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/ui.lua
- Correct some spelling.
- Remove duplicate call to deactivate room (the removed comment is correct)
- Correct two incorrect strings in English. I think Italian is correct and Brazilian PR is wrong, so we should ask translators. This is before the fix.
=> Fix spelling, duplicate call, incorrect original strings

LICENSE.txt, scripts/macos_luarocks
- Update the url and dates of luasocket in licence.txt
- Use the latest release, rather than dev, of luasocket in macos_luarocks
A connected todo: Update vcpkg. Should both happen at the same time? The windows and macos setups already result in using different commits of luasocket
=> Update references to luasocket for their v3 release

CorsixTH/Lua/app.lua
- Current check for update was comparing vx.xx to x.xx, which always resolved that CorsixTH was up to date.
- Bonus points: 0.66 > 0.65.1 (even though our web site only reports 0.65?)
=> Fix version compare on update

CorsixTH/Lua/game_ui.lua
* Fixes #2164
All zoomed draw operations must draw to enclosing rectangles to ensure that there are no unpainted pixels. The lua code was passing in a width and height rounded down which occasionally resulted in not covering the entire screen while zooming.
=> Draw map to enclosing scaled rect when zoomed - fixes #2164

CorsixTH/Lua/dialogs/message.lua, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h, CorsixTH/Src/th_lua_gfx.cpp, CorsixTH/Src/th_map.cpp
**Adds a clip stack on render_target which allows for temporarily adding and removing clips.**
- Since we never need to get the clip anymore, imprecision resulting from the scale factor no longer accumulates.
- Simplifies calling code as it doesn't need to explicitly remember the old clip and restore it.
- Adds a convenience class which automatically restores old clip when it goes out of scope.
=> Refactor clipping on render_target to keep a stack of clips.

CorsixTH/Lua/languages/english.lua
*Fixes #2171*
- Reinstates VIP results fax strings from 0.64 and 0.65 for compatibility.
=> Reinstate legacy strings for VIP

CorsixTH/Src/th_lua_gfx.cpp
When depersisting the constructor isn't called so the vector didn't
work.
Use placement constructor to ensure the vector is constructed.
Fixes #2182
=> Use raw pointer for line_elements

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua, CorsixTH/Lua/dialogs/fullscreen/bank_manager.lua, CorsixTH/Lua/dialogs/fullscreen/graphs.lua, CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
Suggest #2183 is merged before this one.
*Fixes #2038* except for `progress_report.lua`
- Fixes integer values on some windows where saving with the open would cause a .0 to appear when loading the game.
- Progress Report can't be fixed using this PR. A fixme was added instead with reasons.
=> Remove .0 from numbers in saved fullscreen windows

CorsixTH/Lua/calls_dispatcher.lua
*Fixes #2188*
`git grep 'giveAdvice(_'` now returns nothing, every use of giveAdvice is a table.
=> Fix adviser call 2

CorsixTH/Lua/research_department.lua
*Fixes #*
- Switches the random bonus to awarding research points to `t_random` instead of `n_random` for the same reasons as #2194 (rare cases of a negative output)
=> Use t_random for randomness in research points

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/world.lua
Fixes #2204
- Move the wall types back to world, as edit_room isn't always available.
- Adds another savegame version
- Makes me sooo very tired of this stuff
=> Re-moving walls as edit_room doesn't work.

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua, CorsixTH/Lua/world.lua
*Fixes #*
- Replaces a use of `hospitals[1]` in World and Annual Report with `getLocalPlayerHospital`
- With the upcoming changes to spawns in #1986 I haven't touched the `hospitals[1]` in spawn.
- Also didn't touch the `hospitals[1]` for `initStaff` -- as changes need to be made to the called function to work on all hospitals.
- Added a note that the Fame Screen isn't currently accessible from Annual Report (though looks like someone started coding it years ago).
=> Replace hospitals[1] in code

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/object.lua, CorsixTH/Lua/objects/couch.lua
*Fixes #2211*
- Sets both tiles adjacent to couch as passable.
- Previously, the non-passable tile could have a small object put on it. If this is the case, pathfinding will still work as intended after this PR (doctor sees blocked path). However, the player will not be able to place an object on the tile again if they edit the room.
=> Make couches fully passable

CorsixTH/Lua/dialogs/bottom_panel.lua
*Fixes #2220*
(I purposefully separated the two scenarios again, but can merge into one if should be desired)
- Restores "Pause" text when game is paused when "Build while paused" is enabled
- Pause text will be temporarily overridden if the cursor triggers dynamic text. Resets after a second or so once dynamic text no longer relevant.
Ping @Tigertye
=> Modify pause text behaviour

CorsixTH/Src/th_map.cpp
*Fixes #2223
Taking modulo doesn't work for counts.
=> Properly cap number of players while loading a map file.

CorsixTH/Lua/dialogs/resizables/file_browsers/choose_font.lua
- Back button went too far in reverse.
- Now properly exits to Folder Settings menu when pressing back
Also fixes the other part of #2118
=> Fix Font Picker's back button

CorsixTH/Lua/entities/machine.lua
*Fixes #70 *
- Handymen waiting to repair a machine will now meander in the room if a patient is in the same room. This fixes the bug where the machine is repaired while it is in use.
This is the same behaviour that the original game has.
=> Ensure handymen wait for patients to leave

CorsixTH/Lua/app.lua, CorsixTH/Lua/world.lua
*Fixes #2248*
- Corrects `app.wall_types` to `app.walls` in 172 afterLoad and bumps that afterLoad to 174 as a safety net (No damage is done reloading walls anyway).
=> Fix walls afterLoad 172

CorsixTH/Lua/dialogs/edit_room.lua
*Fixes #2242*
- Saves confirm_button state to restore when editing room
=> [RDY] Save confirm_button state when editing room

CorsixTH/Lua/dialogs/patient.lua, CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/make_debug_patient.lua, CorsixTH/Lua/languages/english.lua
*Fixes #*
- Now makes up the debug patient options using all diseases available to the level. This prevents crashing of the game where a debug patient's disease is not known to the level.
- Hides the casebook icon in patient dialog, if a debug patient with a disease not yet discovered exists
- Tidying up in `UIPatient:updateInformation()`
- Fixes the tooltip for the debug patient window.
=> Improve debug patient handling

CorsixTH/Lua/dialogs/resizables/file_browser.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_game.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_map.lua, CorsixTH/Lua/dialogs/tree_ctrl.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Src/th_map.cpp
*Fixes #1913*
*Fixes #568*
*Fixes #2118*
- Adds OK button to file browsers, allowing single click of item, then pressing OK to perform the same as a double-click action
- Saving a game will also add the selected save to the textbox when an item is single clicked. OK works same as above
Removed all the `origin` stuff now from this. Just got to work on making the code better before ready.
=> Add OK to Filebrowser

CorsixTH/Lua/app.lua, CorsixTH/Lua/base_config.lua, CorsixTH/Lua/dialogs/fullscreen/staff_management.lua, CorsixTH/Lua/dialogs/staff_rise.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/map.lua
*Fixes #*
- Maximum salary converted to configuration item (debate over if the max value should be changed is a separate thing imo)
- Staff will not request a raise if already at maximum salary (i.e. never, previously we just hoped and prayed)
- Salary raise now uses the correct sound
- Bonus and salary raise buttons in Staff Management no longer play "selectx" and dedicated sound together.
- Staff Management now shows the maximum salary, if a salary raise would hit that limit
- Clicking on salary raise button when at maximum salary now results in the "wrong2" sound
- Happiness is now fixed at 1 when at maximum salary
- Some rewording of inline comments
- Bugfix: Now properly deactivates salary rise and resets happiness if staff member hit max …
=> Changes to max_salary behaviour

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/main_menu.lua, CorsixTH/Lua/movie_player.lua, README.md
- Adds `ATTRACT.SMK` video to game when idling in main menu
- Idle currently ~30s
- A slightly placeholder too for when we're able to replace with our own movies (e.g. wolter's one as discussed on Discord/Matrix)
=> Add demo gameplay movie

CorsixTH/Lua/epidemic.lua
*Fixes #2256*
- Removes patients from the infected list of epidemics if they are despawned. Prevents future_epidemics from being triggered with no active contagious patients and makes result fair.
=> Remove destroyed patients from epidemics

CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
*Fixes #*
- Prevents 'handyman to water plants' message triggering on every placement of plant
- Now runs a monthly advice check for plants without a handyman
- Reorganised and documented the `dailyAdviceChecks` function to be in chronological order.
- Prevents no radiator check from constantly spamming the player.
=>  Handyman and plant Monthly advice checks

CorsixTH/Lua/game_ui.lua, LICENSE.txt
*Fixes #2016*
When hovering the door to a room (assuming the door is on the north or west edge), show the queue icon above patients that are queueing for that room.
(First time submitting a PR to this repo, so hopefully I'm doing it right)
=> Show queueing patients when hovering the door

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/annual_report.lua, CorsixTH/Lua/dialogs/fullscreen/bank_manager.lua, CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/dialogs/fullscreen/graphs.lua, CorsixTH/Lua/dialogs/fullscreen/hospital_policy.lua, CorsixTH/Lua/dialogs/fullscreen/progress_report.lua, CorsixTH/Lua/dialogs/fullscreen/research_policy.lua, CorsixTH/Lua/dialogs/fullscreen/staff_management.lua, CorsixTH/Lua/dialogs/fullscreen/town_map.lua, CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua, CorsixTH/Lua/graphics.lua, CorsixTH/Lua/ui.lua
Use a flag to mark if the 255 entry in a palette is transparent. Store that flag so it will be applied again on load.
This removes the bug that required sprite sheets to be all fetched on load as well.
RFC because I'm not confident in the afterLoad change made in ui.lua - I suspect I'll have to move those into the individual dialogs that use them instead.
=> Fix #2181 Store palette 255 transparency

CorsixTH/Lua/date.lua
*Fixes #2290 
- We should check the arguments of the compare functions for being `Date` instances, but that crashes with infinite recursion in Lua 5.3.
- Instead we check for the same `__eq` functions which works too under the assumption that at least one of the parameters is a `Date` instance.
=> Date __eq function may get called with values other than Date.

CorsixTH/Lua/languages/developer.lua
Allows the language choice now to show in the language selection menu when you comment out line 25.
Have made sure "dev" does not conflict with any ISO standards for existing languages.
=> Fix developer language

CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/room.lua
*Fixes #1173/#1606*
- During epidemics patient info don't update correctly as per #1173
- Prevent patients becoming fed up and leaving when in a room, also mentioned in the same issue
- Added a helper method for setting staff_wait, and wrapped it to prevent some invalid scenarios #1606 - method refers to staff_member and staff_member_set also to only operate on staff, seems a handy shortcut for the class.is Staff and not handyman check.
=> [RDY] Fix dynamic info updates during epidemics

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/humanoids/patient.lua
*Fixes #2278, #2305*
- Restores settings interrupted walk must_happen from saved_must_happen
- Adds afterLoad to fix instances
=> [RDY]Fix regression in #2086

CorsixTH/Src/th_gfx_sdl.cpp
When a draw scale is set, the caller is not supposed to need to account for the draw scale. This scales the width and height returned accordingly.
*Fixes #2304*
=> Account for draw scale in canvas size.

CorsixTH/Lua/entities/humanoid.lua
- Using curly braces in #2088 caused the "empty action queue!" dialogue message to never show up in 0.66 due to us sending `sizeOf` a table rather than a string to graphics.lua - `font_proxy_mt`
- PR addresses this and removes the curly braces.
- Potential future improvement is allowing `sizeOf` to accept a table of strings.
=> Fix empty action queue dialogue crash

.github/workflows/Windows.yml, CMake/CopyVcpkgLua.cmake, CMake/CopyVcpkgSdlMixerBackends.cmake, CMake/VcpkgDeps.cmake, CorsixTH/CMakeLists.txt, CorsixTH/Lua/api_version.lua, CorsixTH/Lua/app.lua, CorsixTH/Lua/audio.lua, CorsixTH/Src/sdl_audio.cpp, LICENSE.txt, appveyor.yml, scripts/build_vcpkg_deps.ps1
vcpkg dependencies are bumped. The new set is listed below.
SDL2_Mixer has some vcpkg changes. native_midi is no longer an option when installing through vcpkg. This is a packaging change, not a code change upstream. Manually adding the dependency dlls for sdl2_mixer is also no longer required, they are pulled in properly on build now.
Since fluidsynth is now the preferred midi engine for CorsixTH and it only works if a soundfont is loaded, some initialization code to find soundfonts has been added. It is expected that we will be able to ship one with the installer for the next release version.
To give us more options in case of problems with appveyor a windows github action pipeline was added.
vcpkg packages:
brotli 1.0.9#5
bzip2 1.0.8#4
catch2 3.3.2
dirent 1.23.2#2
ffmpeg 5.1.2#6 …
=> Bump vcpkg and favour fluidsynth

CorsixTH/Lua/dialogs/edit_room.lua
*Fixes #*
- Stops crash from 171 afterload by removing it
- Adds a comment on 172 afterload to explain context
=> Clean edit_room afterload

README.md
Re-uploads imgur hosted files into CorsixTH assets (given imgur's uncertainty). It does look like Github tries to hold its own copy of an image even before this PR but I'm not sure what happens if the imgur dies.
Not sure if we need permission from @SimplyRyan for this change as I think he originally uploaded them (but can't find any entry in our license.txt file for Ryan: #702
=> Move imgur images to github

CorsixTH/Src/th_gfx_font.cpp
https://discord.com/channels/731272375949328486/854282144101040179/1086963524338712576
how to reproduce the bug:
-  use some font and select some game language(maybe other than English) which uses freetypefont.
my case - mingliu.ttc, Traditional Chinese.
- display a long word "a wwwwwwwwwwwwwwwwwwwwww..." in tips window of home screen.
("xxxx..." does not trigger the bug. Need to be "x xxxx...".)
- infinite loop; freeze;
thanks.
=> try to fix infinite loop when word wider than box Width

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua, CorsixTH/Lua/graphics.lua, CorsixTH/Lua/map.lua, CorsixTH/Lua/strings.lua, CorsixTH/Lua/ui.lua
- Uses a new function for making full paths. Not used in config_finder so that it can be used by the windows_config script.
=> Replace debug.getinfo with App:getFullPath

CorsixTH/Lua/entities/humanoids/staff.lua
*Fixes #2319*
*Fixes #*
- Quick fix to resolve no dynamic info updates to staff during nosleep cheat for 0.67. Need to later on look at points raised in https://github.com/CorsixTH/CorsixTH/issues/2319#issuecomment-1513297717
=> Fix dynamic info on wakecheat

CorsixTH/Lua/app.lua, CorsixTH/Lua/config_finder.lua, WindowsInstaller/config_template.txt
- As some people may find the demo movie playback annoying a config option has been added to disable just that element.
=> Add option to disable demo movie

CMake/VcpkgDeps.cmake
Uses a patched version of sdl2-mixer that adds proper seek and start/stop to fluidsynth
=> Bump vcpkg for fluidsynth seek fix

CorsixTH/Lua/room.lua, CorsixTH/Lua/world.lua
*Fixes #2325 again*
- Prevent crash where no staff member is in the room (due to staff member leaving; or a staff member is at `queue:front()`)
#2135 replaced the call of checking all humanoids for a wait toggle and applying the mood update as necessary. This meant that if no staff were present nothing needed to be done. The wait toggle change now expects a staff member present as its target and would fail if nobody was there. Unfortunately, `Room:tryAdvanceQueue` is used for a broad scope of things to get the queue moving -- this includes Handymen trying to enter when the door is reserved.
It is possible that the new patch needs to go in `Room:_checkWaitToggleValidTarget()` instead with its explanatory scope change.
It is also advisable to check …
=> repatch 2135/2333

CorsixTH/Lua/staff_profile.lua
On a level with Alien DNA, eg L12, this lets the drug casebook tell the player they need a researcher.
=> Fix casebook label for alien dna

README.md
Addition for #2338
- Update the download source of the original game in the readme file (Replace Origin by EA)
=> Replace original game download link Origin with EA

README.md, README.txt
Add all of our Matrix channels and space link to README.md ; add just the space to the .txt
As spaces were introduced in 2021 it looks like some more clients now support this feature.
I've used Github's spoiler code to hide the individual matrix links so they don't bloat the readme page:
Announcements channel may be droppable from list.
=> Add Matrix Space to readmes

CorsixTH/Lua/app.lua
- If there's the false appearance of an internet connection (eg the phone cable is unplugged from the router), the app will hang for several seconds until it times out. This cuts that down to two seconds.
=> Add a timeout to the update checker

CorsixTH/Lua/audio.lua
- Use midi.txt as a playlist, music is played in that order
- If that file isn't present, then order alphabetically
I think the first is expected, the original did it (#2386). The second is slightly more surprising, but if the files aren't numbered, then it's no worse than the current random order.
=> Sort background music by midi.txt or alphabetical order

CorsixTH/Lua/world.lua
*Fixes #2027*
Fix issue #2027 by ensuring loans are payed before winning is possible
- If the players has loans and the state is "win", force it to "nothing"
Disclaimer:
I cannot compile yet on my computer, so I couldn't test
PS: I remember when the project was started, and it's great to see it's still moving on :-)
=> FIX Level advance is possible while owing a loan #2027

LDocGen/c_tokenise.lua, LDocGen/helpers.lua, LDocGen/lua_tokenise.lua
*Fixes #2412*
- Remove the lpeg version check. Lpeg 0.9 is at least 14 years old.
=> Remove lpeg version check in docs build

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/main_menu.lua
*Fixes #2408*
- Previously, any file with \*sav in it could be loaded
- Now, only files ending in .sav will be loaded. The filename must match - wildcard, literal period, "sav" at the end.
=> The continue button/switch only loads filenames ending with .sav

CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/objects/helicopter.lua
*Fixes #2419*
- Move the announcement and advisor message from when the fax is accepted to when the first patient spawns. I looked at a few videos on youtube and this is about the right time, sometimes it appears to be around when the second or third patient spawns.
=> Move the emergency announcement and advice to the first patient spawn

CorsixTH/Lua/dialogs/menu.lua, CorsixTH/Lua/map.lua
*Fixes #2226*
- Add the group and condition to the map editor's player count menu.
=> Fix map editor player count menu

CorsixTH/Lua/humanoid_actions/seek_reception.lua
*Fixes #1232*
Refactor a bit the method `action_seek_reception_start` in `seek_reception.lua` :
- Add a guard to call of `getPathDistance` for boolean return value
- Remove one call to `getPathDistance` and reuse the already computed distance
I've also checked that the rest of the codebase is handling this case.
=> FIX Crash seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')

CorsixTH/Lua/entities/humanoids/patient.lua
*Fixes #1563 *
- Check the patient is in the players hospital before they litter.
=> Patients may only litter indoors

CorsixTH/Lua/dialogs/machine_dialog.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/strings.lua
*Fixes #2318*
- Tell the player the cost of replacing their machine via the adviser if they can't afford it.
- Also adds ability for adviser to be given multiple arguments for string.format
Using the more flexible `%[1-9]%` argument format so translators can rephrase the string if needed.
=> Advice player of new machine cost

CorsixTH/Lua/app.lua, CorsixTH/Lua/objects/doors/swing_door_right.lua
*Fixes #2389*
- Ward and Operating Theatre doors are paired within the same tick, when built or loaded from an old save.
=> Pair swing doors instantly

.luacheckrc, CorsixTH/Lua/utility.lua
I use this function for my own debugging purposes but may be helpful for others. It provides a simplified interface to use `serialize` rather than needing to juggle options every time.
I can close this PR if we don't want this functionality in utility.
=> [RFC] Add simple interface for serialize

CorsixTH/Lua/dialogs/menu.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/world.lua
Partially addresses #1378
- Checks the map has a valid path from the hospital to the first spawn point.
Should the spawn points be niled after this?
=> Add a warning to mapeditor when a map has no spawn path

CorsixTH/Lua/dialogs/resizables/dropdown.lua, CorsixTH/Lua/dialogs/resizables/options.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/strings.lua
*Addresses #1915*
- If the user can't switch to the unicode languages, show them in the language select list with their English name in a disabled button. The tooltip tells them to set a font.
=> Show languages as disabled when they aren't available

CorsixTH/Lua/audio.lua
- Concatenate the error message for unplayable music correctly. I had the error when playing formats not supported by my sdl2_mixer build.
=> Fix background music error message

CorsixTH/Bitmap/example.spec, CorsixTH/Bitmap/lib_bmp.lua, CorsixTH/Bitmap/lib_spritesheet.lua, CorsixTH/Bitmap/mkfont.lua, CorsixTH/Bitmap/mkraw.lua, CorsixTH/Bitmap/mksheet.lua
Work should bring these scripts up to Lua 5.4 compatibility while retaining Lua 5.1/JIT compatibility (not tested)
-- Removes `setfenv` call and rewrites spec file to work without it
-- Removes `module`, replaced with `require`
-- Fixes bug in `makeRaw` where bitmap files were not closed after execution
I've not attempted to completely untangle the methods Corsix used for these files so likely a lot of odd design choices still exist (and ones that fail our coding conventions) but I can confirm these mkfiles are running from CorsixTH.exe via debug script.
[**mkboostrap.lua**](https://github.com/CorsixTH/CorsixTH/blob/835bb9aad6d751749ff88e9449797547bf6424da/CorsixTH/Bitmap/mkbootstrap.lua) in Bitmap folder may need addressing with these changes, but I don't want to look at that one myself …
=> Patch Lua Bitmap Makefiles

CorsixTH/Lua/languages/brazilian_portuguese.lua, CorsixTH/Lua/languages/danish.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/languages/finnish.lua, CorsixTH/Lua/languages/hungarian.lua, CorsixTH/Lua/languages/iberic_portuguese.lua, CorsixTH/Lua/languages/italian.lua, CorsixTH/Lua/languages/polish.lua, CorsixTH/Lua/languages/russian.lua, CorsixTH/Lua/languages/simplified_chinese.lua, CorsixTH/Lua/languages/spanish.lua, CorsixTH/Lua/languages/traditional_chinese.lua
- The folder options dialog uses the data_location string, not original_path. Remove original_path from all languages.
=> Remove unused original_path string

CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/world.lua
*Fixes #2001*
- Always show the level briefing on day 1
- Don't show the final message of the tutorial when playing level 1, as it is the level briefing already shown
=> Show level briefing before the tutorial instead of after

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/information.lua
- Makes UIInformation more uniform to the original game as our implementation has excessive width padding. Works without any impact on non-standard fonts/cjk. Note Chinese still has an oddity where it adds additional blank space to the right.
- Makes close button have a reserved zone on bottom to allow for better utilisation of the box width
- Reformats some of the code spacing (there's too many magic numbers going on currently for me to focus on improving that here)
- Before 
- After 
A future improvement would be to also utilise the empty space adjacent to the button with awareness for that button existing on wrap. Or, move the button outside the box to look like a little tab on the top right.
=> Resize UIInformation

CorsixTH/Lua/game_ui.lua
This fixes [bug #2498](https://github.com/CorsixTH/CorsixTH/issues/2498)
The problems shown in [bug #2498](https://github.com/CorsixTH/CorsixTH/issues/2498) of are due to these codes:
* In `GameUI:onMouseMove` the following code is run when panning with the mouse:
https://github.com/CorsixTH/CorsixTH/blob/3899df33db2917ad6b336c0027d111ff76b183fe/CorsixTH/Lua/game_ui.lua#L555-L563
* The previous code calls the function `GameUI:scrollMap`:
https://github.com/CorsixTH/CorsixTH/blob/3899df33db2917ad6b336c0027d111ff76b183fe/CorsixTH/Lua/game_ui.lua#L934-L943
The problems are caused by the floor operation in `GameUI:scrollMap`:
```lua
self.screen_offset_x = floor(dx + 0.5) 
self.screen_offset_y = floor(dy + 0.5)
```
Since it seens that `screen_offset_x` and `screen_offset_y` have to be …
=> Fix some problems with mouse panning

CorsixTH/Lua/dialogs/watch.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
This aims to partially address the issue of #649 by forcing a patient to be given on open https://github.com/CorsixTH/CorsixTH/issues/649#issuecomment-1279949701 . It doesn't address the difference in wait of that issue but should at least make the first patient a little more consistent.
- Moves hospital modification out of `UIWatch`
- Spawns a patient on open of hospital (providing you built a reception desk, of course!)
- Gives the `AIHospital` a function path to open for future use.
RFC needed because one oversight here is that some players will open their hospital as soon as they start, evading this change. Should another consideration be made for this instance (e.g. if open without desk, spawn patient once a desk gets made the first time).
=> Spawn a patient on open

CorsixTH/Src/sdl_core.cpp, CorsixTH/SrcUnshared/main.cpp
Also show error message if SDL_WaitEvent fails.
If SDL_Mixer is used by any destructor owned by lua, e.g. the movie player then it needs to still be available when lua is closed.
=> Fix shutdown order

README.md
- Added a link to Snapcraft as an option for installing in the README
=> Add a link to the Snap in the install instructions in the README

CMakePresets.json
An opinionated linux dev preset for CMake
Enables unit tests and all optional components. Uses ninja as the make too.
=> Linux dev preset for cmake

CMakePresets.json
Debug symbols are important to development
I merged just a moment too early
=> Add debug to linux-dev

CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h
This is a possible fix for #2301. It may be that destroying the intermediate texture as soon as we issue a draw call for it is unsafe. This delays the destruction of the texture until the next frame is started.
*Maybe fixes #2301*
- Collects textures that we are finished with on the render target into a vector.
- Destroys those textures when we begin the next frame, i.e. they should be done with at this point.
=> Delay destruction of intermediate textures.

CorsixTH/Lua/hospital.lua, CorsixTH/Lua/world.lua
Another PR to partially address the contents of #649 
- Runs a path comparison calculation to get the closest path between all spawn points and reception desks, then chooses the closest spawn point for the first player's patient.
- In level 1, this brings the time for the first patient to reach the hospital entrance ~19 days.
Small potential hole here is `_findClosestSpawnToDesk` can return false/nil here if it fails to find any paths. Should that be safeguarded?
=> Choose Closest Spawn for First Patient

CorsixTH/Lua/app.lua, CorsixTH/Lua/utility.lua
- A config value with brackets will be saved, but can't be loaded. This looks for [] and uses [=[ ]=] to contain the whole value. eg A music folder ending [2023], or player name with [].
=> Permit brackets in config values

CorsixTH/Lua/hospitals/player_hospital.lua
- Prevents refresh of the cheats system from wiping out active toggle cheats.
=> Transfer active cheats on refresh

CorsixTH/Lua/dialogs/bottom_panel.lua, CorsixTH/Lua/dialogs/fullscreen/town_map.lua, CorsixTH/Lua/graphics.lua
*Fixes #1193*
- Draw each digit of the balance in the boxes in the bottom panel and town map. Add a temporary offset for unicode languages for #2459 
The text is very faint, and I prefer the existing solution of using the builtin font in all languages, but this change is consistent with the rest of the UI.
=> Draw the hospital balance one number at a time

.github/workflows/Windows.yml
- Add on demand builds, with options for 32bit, Animview builds, of a specific pr. Here's a 32bit build with Animview of 2489 (a recent PR with cpp changes) https://github.com/tobylane/CorsixTH/actions/runs/7934724743/job/21666299492
- Name the output
- Update old steps
=> Add Animview, 32bit, pr checkout on demand to Windows Actions

CorsixTH/Src/th_gfx.cpp
*Fixes #2534*
- Fix broken sound pointer for these two machines when in use. It used `234 NULL` instead of `35 SCNBEEP1` (may be our error?).
This isn't really a perfect fix by any means. As discussed with @Alberth289346 it may be better to identify the specific frames or animations (`4878 and 2098`) and specifically target those. However, sound `234` is only used for these animations. I don't know any C++ really to even taken on such a thing -- so I'm just pushing what I have now to get something down to consider.
No idea if this needs an API bump, advise or feel free to add a commit if it does. Built fine on `win-dev`
=> Add Computer & Atom Analyser Entity Sounds

CorsixTH/Lua/app.lua, CorsixTH/Lua/objects/doors/swing_door_right.lua
*Fixes #2476*
- Re-uses Edvin's entrance door function to pair doors in Swing Door to allow both doors to be built in either order.
~~This removes Toby's assertion from #2436 currently and it needs to be put back in in a good place.~~ now put back
=> Dynamically Pair Swing Doors

CorsixTH/Campaigns/example.campaign, CorsixTH/Levels/example.level, CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua, CorsixTH/Lua/languages/korean.lua, CorsixTH/Lua/strings.lua
- Collect language codes for languages, two letters long for all but Chinese.
- Use localised strings in the level files for the briefing and debriefing (single scenario description and end of level winning text), and in campaign files for description and winning text.
- Add French translations to the example level and campaign in differing ways.
=> Add localised text to level and campaign descriptions and winning text

CorsixTH/Lua/audio.lua
Expand the list of music file extensions that will be accepted for the jukebox. Sourced from the list https://github.com/libsdl-org/SDL_mixer/blob/release-2.8.x/src/music.c#L680 and https://github.com/libsdl-org/SDL_mixer/blob/release-2.8.x/src/music.c#L561 which ends with the comment that everything else gets given to modplug/xmp. GME is excluded as debian and vcpkg don't include it.
Sample music files
https://getsamplefiles.com/sample-audio-files
https://www.stanislavs.org/OldPages/mody_collection/
https://www.mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/Samples.html only uncompressed
=> Add more music file extensions

CorsixTH/Lua/dialogs/resizables/tip_of_the_day.lua
*Fixes #2200*
- The width of the tips window is narrower in small resolutions, with stacked previous/next buttons. As it doesn't overlap with the main menu, is this an acceptable place to close and reopen windows without caring about window order?
=> Make the tips window adapt to the space beside the main menu

CorsixTH/Src/th_gfx_sdl.cpp
Increasing the overdraw amount seems to help eliminate those single pixel gaps between adjacent tiles. In local testing with the new value maintains sharp rendering while seemingly eliminating gaps between tiles.
*Fixes #2403*
=> Increase overdraw amount used by SDL_RenderCopyF

CorsixTH/Lua/app.lua, CorsixTH/Lua/staff_profile.lua, CorsixTH/Lua/world.lua
*Fixes #2554*
- When the number used to pick a staff initial is 0, make it 1. Apply this to existing staff.
=> Fix missing initial in staff names

CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua
Add support for long custom campaign descriptions, requiring a scrollbar. I think this was intended in the PR that makes the custom campaign dialog, which added this function in the single scenario dialog I copied. https://github.com/CorsixTH/CorsixTH/pull/676/files#diff-7cb59940abdd2a76ef1e4a7ef1a43bed82b0381d550c30229453f02e6230bb04R99
I tested this by repeating a line in the ChrizmanTV campaign description.
=> Fix custom campaign scrollbar

CorsixTH/Lua/audio.lua
*Fixes #2544*
- Pushes XMI files to use our xmi2mid converter for supported playback
I've tested this with copying an XMI from the TH folder into a custom folder; and also tested a XMI from SimCity 2000.
=> Support external XMI again

CorsixTH/Campaigns/example.campaign, CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua
- Add the option 'movie' to custom campaigns. This plays the board game advance level movie, with the correct level number for that campaign (the movie doesn't play if there are more than 12 levels).
- Add this option to the example campaign.
=> Add an option to use the advance level movie in custom campaigns

CorsixTH/Lua/entities/humanoids/staff.lua
*Fixes #1642*
- Now correctly removes a sacked staff member's queued raise request if the message icon is not shown on the bottom panel
- Also for death
=> Remove queued StaffRise messages on sack/die

CorsixTH/Lua/app.lua, CorsixTH/Lua/base_config.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/entities/humanoids/staff/doctor.lua, CorsixTH/Lua/entities/humanoids/vip.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/map.lua
*Fixes #2564*
- Use Tired, VeryTired and CrackUpTired from level_config.gbv to judge staff tiredness. The defaults are the current magic numbers, from TH level config.
=> Use tired values from level config for staff tiredness

CorsixTH/Lua/app.lua, CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/ui.lua
- Adds some groundwork functionality to tackle #2370 
- Being idle on main menu when game window is no longer is in focus will no longer trigger the demo movie
=> Add foundation code for using window active status

CorsixTH/Lua/audio.lua, CorsixTH/Lua/languages/english.lua
*Fixes #2520*
- Change some SDL Mixer error messages to more helpful text, "Required soundfont is not found, please download one. A suitable soundfont is linked from the CorsixTH wiki." and the below message for known errors, and a catch all for anything else.
- Skip the playlist item and uncheck its box.
=> Add descriptive audio error messages

.luacheckrc, CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/progress_report.lua, CorsixTH/Lua/endconditions.lua, CorsixTH/Lua/world.lua
- Collect level goals into their groups
- Check each group for win and lose game endings
- Make the progress report dialog show the most relevant group
Fixes #232
=> Add groups to win/lose criteria

README.md
Amendments for better operation
- Release status badge now in the `for-the-badge` format to vertically align with the text. It now also links out to the latest release page
- Moves CI badges to their own line
- CI badges now properly reflect the status of the `master` branch on push events only (only an issue with `windows.yml` currently).
- Appveyor badge reworded
- Images no longer link out
- Good first issue link added to the contributors section
- Fixed broken emoji
=> Tidy README file

CorsixTH/Lua/dialogs/menu.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_map.lua, CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/languages/english.lua
- Add confirm window to the restart map editor menu option
- Add mapeditor specific message to quit confirm window
- Move map editor save function to GameUI (used in a future PR).
=> Add confirmation window to map editor restart

.luacheckrc, CorsixTH/Lua/app.lua, CorsixTH/Lua/cheats.lua, CorsixTH/Lua/earthquake.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua, CorsixTH/Lua/world.lua
- Earthquakes are now ~~a sub class of~~ an instance that belongs to World, with ongoing/next quakes transferred. No additional features. The old recount for current_map_earthquake was faulty so it wasn't copied over (World:afterLoad).
=> Refactor earthquakes to its own class

CorsixTH/Lua/dialogs/resizables/file_browser.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/load_game.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_game.lua, CorsixTH/Lua/dialogs/resizables/file_browsers/save_map.lua, CorsixTH/Lua/languages/english.lua
*Fixes #2576*
- Adds an optional parameter to `UIFileBrowser` to set custom text for the ok/submit button
- Introduces this to Save/Load Game/Map
- Optional additional commit to add a message when attempting to save without selecting/setting a filename.
I added some doc to the `UIFileBrowser` main function but level blank 2 parameters not 100% sure what they do.
=> Add Load/save buttons & save warning message

CorsixTH/Lua/config_finder.lua, CorsixTH/Lua/dialogs/resizables/options.lua, CorsixTH/Lua/game_ui.lua, WindowsInstaller/config_template.txt
*See #2469*
-  Adds to the config.txt that the setting is experimental
- Removes the setting from the Options menu (preserves the code in blockquote)
@tobylane let me know if a button should be moved after this, the LHS column has a gap at the bottom, RHS does not.
=> Mark Right Mouse Scrolling Experimental

CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/languages/russian.lua
* Fixes #2585 *
- load_map.lua uses now `load_map_window` set of strings instead of `load_game_window`
=> Use new strings for load map window

.github/workflows/Windows.yml, .github/workflows/WindowsInstaller.yml, CorsixTH/CMakeLists.txt, WindowsInstaller/Win32Script.nsi
- Builds a Windows installer from successful x64 and x86 Windows Actions runs, chosen by their run id from the url.
example https://github.com/tobylane/CorsixTH/actions/runs/9158967469 is made of two runs from March.
=> Add Actions for Windows Installer

CorsixTH/Lua/world.lua
*Fixes #*
- Bump the very old save cutoff for next release while #2518 is to be finished for 2025's release; otherwise saves from 0.66 will complain as being unsupported.
=> Temporarily Bump Very Old Save

changelog.txt
Adds changelog ready for next release.
NB: As we're now planning to use the revision number more strictly, we should probably also start adding the .0
The following text below is intended to go on the release post at the top of the changelog:
**This version comes with two experimental features you can help us with by giving feedback on! These will be off by default.**
=> Changelog 0.68.0

CorsixTH/Lua/hospitals/player_hospital.lua
- hosp_cheats may not exist in an old save. Make sure if we don't crash by safeguarding the check for transferring active cheats first.
Found by @Alberth289346 -- chances are this case could potentially affect newer saves than the one it was found in.
=> Safeguard cheat transfer

CorsixTH/Lua/humanoid_actions/seek_room.lua
*Fixes #2496*
- Removes the mood deactivate on interrupt of seek_room. The wait now clears once the seek_room wait is properly resolved or by acting on the fax. This line up with the mood's behaviour in TH.
=> Don't clear patient_wait mood on seek_room interrupt

CorsixTH/Lua/app.lua, CorsixTH/com.corsixth.corsixth.metainfo.xml, CorsixTH/corsix-th.6, WindowsInstaller/Win32Script.nsi, changelog.txt
For next RC.
Note the bugfix change `Added a safeguard to prevent a crash of games previously using the old cheat system` isn't in the main changelog because on release it will be fall under the bugfix `Active cheats will now persist across saves` instead.
=> Update for 0.68.0 RC2

CorsixTH/Lua/app.lua, CorsixTH/com.corsixth.corsixth.metainfo.xml, CorsixTH/corsix-th.6, WindowsInstaller/Win32Script.nsi, changelog.txt
Prereleases squashed at request.
Hopefully the XML changelog is mirrored correctly. Date set to the 1st if the version plans to be tagged early.
=> 0.68.0 Release

CorsixTH/Lua/app.lua
A partial step for #2639 to let hotfixes take reserved savegame version numbers (195 - 203)
=> Allocate hotfix savegame versions

.github/ISSUE_TEMPLATE/bug_report.yml
For issue templates we put the gamelog text in `bash`. However, the way we render gamelog data is more legible in yaml.
Bash:
```bash
Warning: Trying to remove nonexistent staff callback (function: 0000015E54720E90) from humanoid (table: 0000015E52626FE0).
Warning: Trying to resolve door deadlock at (29, 50)
Error in timer handler: 
Lua\entities\humanoid.lua:472: assertion failed!
stack traceback:
[C]: in function 'assert'
Lua\entities\humanoid.lua:472: in method 'startAction'
Lua\entities\humanoid.lua:577: in method 'finishAction'
Lua\humanoid_actions\use_screen.lua:48: in local 'timer_function'
Lua\entity.lua:216: in method 'tick'
Lua\world.lua:1074: in method 'onTick'
Lua\app.lua:1202: in function <Lua\app.lua:1199>
(...tail calls...)
Lua\app.lua:1102: in function <Lua\app.lua:1097> …
```
=> Change gamelog render to yaml in issue template

CorsixTH/Lua/entities/machine.lua
Reduce machine strength chance on repair tuned to more match TH
*Fixes #*
I have discovered, that CTH reduce machine strength chance is not matches the TH reduce machine strength chance.
I have checked CTH code and discovered that, 
`if (machine.times_used / machine.strength > 0.55) then`
reduce strength must happen.
So no any reducing will happen in cases like 
`strength = 8 and times_used = 4`.
But it is typical condition when handyman comes to fix automatically.
But in TH you can get reduce even if `strength = 12 and times_used = 1`, which gives `times_used / strength = 0.08`
At the same time, in TH you can get no reduce for case
'`strength = 8 and times_used = 6`'. For which CTH will give 100% reduce.
So CTH formula does not mimic the …
=> Reduce machine strength chance on repair tuned to match TH

CorsixTH/Lua/languages/english.lua
*Fixes #2294*
This pull request replaces the current `save_to_tmp` string with a more general message. I have reproduced the error by setting my configuration file to read-only and can confirm that the updated string will appear.
=> improved save_to_tmp string

CorsixTH/Lua/languages/english.lua
*Fixes #2619*
This pull request improves the tooltips that appear when hovering the cursor over the increase and decrease buttons on the Research screen. I've tested my changes and can confirm that the original strings will be overridden.
=> Improved tooltips in research screen

CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/hospital.lua
* Fixes #2631 
- Creates new variable `pay_amount` which stores the amount of treatment cost
- hospital:receiveMoneyForTreatment() now checks pay_amount variable instead of price in casebook
=> Freeze patient's treatment cost when agreeing to pay

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/main_menu.lua
*Fixes #2690*
- The idle tick counter for the demo movie used draw events. With `track_fps` these can happen very quickly
- Changed it so increment counter at `onTick()` events instead
WIP because I need to test cyco's tick changes again against the count. 0.67 loads the demo movie after 30s; 0.68.0 it's 37s. I'm expecting the tick changes again to affect the time.
=> Move idle ticks to follow app ticks

CorsixTH/Lua/dialogs/fullscreen/staff_management.lua, CorsixTH/Lua/dialogs/staff_rise.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/staff_profile.lua
*Fixes #2625*
-
- Fixes the issue: Automatically satisfying salary request does not close the salary request window.
- Also fixed that on Automatically satisfying salary request there was no 'increaseWage' sound.
-
=> #2625 Fix: Auto satisfying salary request don't close window

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/humanoids/vip.lua, CorsixTH/Lua/humanoid_actions/walk.lua
- VIPs walk slowly, like in TH
- Inspectors walk at normal speed, so unaffected by this
I also found that the `self.speed` variable on `humanoid` is pretty useless to have the value as `slow`. But not planning to look at that.
This PR should be followed by a future one to suggest changing walk speed where patients and vips are off map from the spawn point.
=> Make VIP walk slow

.gitignore, CorsixTH/Lua/api_version.lua, CorsixTH/Lua/app.lua, CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/world.lua, CorsixTH/Src/lua_sdl.h
Double the number of tick events so that we can do one movement per tick instead of two at normal speed.
Fixes #2679 but may have side effects. Please play test.
=> Smooth out gameplay at normal speed

CorsixTH/Lua/app.lua
*Fixes #2711* only
- Stop mouse capture if we need to choose the TH install directory, since TH cursor graphics isn't available.
=> Stop mouse capture on initial TH Selection screen

CorsixTH/Lua/app.lua, CorsixTH/Lua/world.lua
*Fixes #2665*
- The gamelog is written to a file, in a new logs subfolder, named for the current date, time. At this point, older logs are deleted.
Flaws
- No UI yet
=> Use date and time in log filenames

CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua, CorsixTH/Lua/languages/english.lua
*Fixes #2721*
- Adds missing tooltips to Hotkey Assignment screen (the keys are consistent with each corresponding button's label)
- Adjusted wording of existing tooltips on Hotkey Assignment screen
- Feel free to suggest any improvements to the values provided
=> added tooltips to Hotkey Assignment screen

CorsixTH/Levels/example.level, CorsixTH/Lua/app.lua, CorsixTH/Lua/base_config.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/map.lua
Allows soda price to be configurable in the level file in order to expand level creation capabilities.
=> soda price can now configurable in the level file

CorsixTH/Lua/endconditions.lua, CorsixTH/Lua/languages/english.lua
- Adds the end game criteria of average happiness for staff and patients. 
See it with this in example.level, or change the 30 to 60 for a quick lose.
```
7 Average staff happiness (0-100)
8 Average patient happiness (0-100)
#win_criteria[0].Criteria.MaxMin.Value.Group.Bound 7 1 70 1 50
#lose_criteria[0].Criteria.MaxMin.Value.Group.Bound 8 0 30 2 50
```
I'm writing a wiki page for this process of adding criteria.
=> Add new criteria - staff and patient happiness

CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/hospital.lua
*Fixes #2699*
- Debug patients at autopsy are now properly removed from debug list on death (as well as room explosion)
- Intended to do more refactor, but debug patients must be deregistered out the debug list much earlier than from the hospital patient list
- A little doc
=> Debug patients properly deregister on autopsy

CorsixTH/Lua/entities/machine.lua
-
- ... as a result of Discord discussion...
- We noticed that in the vanilla TH machines have a minimum possible value for the strength, which we did not follow in CTX. This value 2. This PR fixes that for CTX.
-
=> Set minimum possible machine strength after repair to 2

CorsixTH/Lua/hospital.lua
- If there is no helipad (eg level 2), the patient created by the 'Soawn Contagious Patient' cheat is spawned on a random regular spawn tile.
=> Fix spawn contagious patient cheat

CorsixTH/Lua/room.lua
* Fixes #2617
- Adds long windows (120, 121) to the `window_tile` array in `room.lua`
=> Count long windows as window of room

CorsixTH/Lua/app.lua
*Fixes issue from Argamx's comment in #2706*
- Use local, not UTC, time in game log filenames.
=> Use local time in gamelog filenames

CorsixTH/Lua/game_ui.lua
* Fixes #2613 
- Disables cheats menu bind in the map editor
=> Do not show cheats in map editor

CorsixTH/Lua/humanoid_actions/walk.lua
- Code has a `duration` variable with some hard-coded values. Also, it is changed a few times, making it hard to understand what actually happens.
- Analysis showed it simply uses the door animation length in all cases.
- Simplified the code without changing functionality.
----
As the function is long, and there are 2 door types, 4 compass directions, leaving/entering case distinction and many humanoid types, some analysis was done first.
Added code to dump the available animations and their length on first creation of a humanoid:
``` diff
diff --git a/CorsixTH/Lua/entities/humanoid.lua b/CorsixTH/Lua/entities/humanoid.lua
index cf88ac8e..857ea297 100644
--- a/CorsixTH/Lua/entities/humanoid.lua
+++ b/CorsixTH/Lua/entities/humanoid.lua
@@ -283,6 …
```
=> Cleanup door-handling in walk action

CorsixTH/Lua/epidemic.lua
*Fixes #2738, #1454*
- Fixes bug when epidemic Timer doesn't stop when an epidemic is successfully eradicated.
-
=> #2738 stop epidemic timer on epidemic successfully eradicated

CorsixTH/Lua/config_finder.lua, WindowsInstaller/config_template.txt
*Fixes #2747*
- SoundFont is now an addressable configuration option with specified caveats. Wiki update to follow.
I'm pretty sure this change won't apply to existing config files because the setting is nil, however. It could be false but that would break how we format folder settings.
=> Add soundfont setting to config

CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
*Fixes #1675*
https://github.com/search?q=repo%3ACorsixTH%2FCorsixTH+bottom_panel%3Aopenlastmessage&type=code
There are two calls to open the same win fax, this removes one of them.
=> Remove duplicate call to open the win fax

WindowsInstaller/Win32Script.nsi
- Fix the uninstall (it fails as it leaves the Campaigns folder behind)
- Fix the intended shortcut to the appdata folder
- Remove the svn and opengl/directx parts from a long time ago
- Add nonfatal to the copy executable lines. This permits an installer to only have one architecture in it. The flag -WX will keep this a fatal error, eg https://github.com/CorsixTH/CorsixTH/blob/08872a33426fc6e9ef201631ade721a565b18ad7/.github/workflows/WindowsInstaller.yml#L41
- Adjust ifs and comments, no change in content.
A recent create installer run https://github.com/tobylane/CorsixTH/actions/runs/12446620429
=> Windows installer improvements

CorsixTH/Lua/dialogs/resizables/file_browser.lua, CorsixTH/Lua/entity.lua
- The file browser comment was moved to other functions in that commit. https://github.com/CorsixTH/CorsixTH/blame/a45512ba654066520da123999fbdc382e0e248cc/CorsixTH/Lua/dialogs/resizables/file_browser.lua#L65
- The entity comment uses newproxy, which was deprecated in 5.1, removed in 5.2. https://github.com/CorsixTH/CorsixTH/blame/a45512ba654066520da123999fbdc382e0e248cc/CorsixTH/Lua/entity.lua#L280
=> Remove old commented out code

CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua, CorsixTH/Lua/humanoid_actions/seek_room.lua, CorsixTH/Lua/languages/english.lua
*Fixes #1877*
- Add advice telling the player to build a GPs office for a hired doctor, or build the room and hire the doc. The advice is only given once per month. The third case of an unstaffed room already has a message.
This is for the regular path, when the hospital has a reception but not rooms. It doesn't apply to patients who queued at a room since deleted.
=> Add adviser messages for patients waiting for a staffed gps office

CorsixTH/Lua/humanoid_actions/seek_reception.lua, CorsixTH/Lua/humanoid_actions/walk.lua
*Fixes #2501*
- Adds a new parameter to the `Walk` action where a trimmed path issued
- Instead of attempting a reroute inside the Walk, the action is finished instead
- In the case of `SeekReception`, that action calls a new `Walk` with an updated path.
@Alberth289346 and I discussed this one, and both agree currently there may not be a very nice way to do this, but as it's a regression of #1852 introduced in 0.67 it may be worth considering a fix for now. A better long term solution is recoding how walk is handled as a whole.
=> Change reroute behaviour on trimmed paths

CorsixTH/Src/th_gfx_sdl.cpp
*Fixes #2779*
*Reopens #2744*
- A typo in the lightness calculation caused some fonts to be offset. However, it brings back the Pause text issue.
(I think there might just be something wrong with how we're colouring Pause elsewhere)
=> Fix typo in lightness calculation

CorsixTH/Lua/announcer.lua
*Fixes #*
- Tick changes in 0.68.0 didn't adjust the random announcement target value; so recalculated here
- Hopefully I can still eventually get around to improving this better WRT #2421
=> Adjust random announcement target

CorsixTH/Lua/dialogs/resizable.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/epidemic.lua, CorsixTH/Lua/objects/doors/swing_door_right.lua, CorsixTH/Lua/room.lua, CorsixTH/Lua/window.lua, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/com.corsixth.corsixth.metainfo.xml, changelog.txt
*Fixes #2784*
**This Pull Request is to fix the typos mentioned in Issue 2784:**
- CorsixTH/com.corsixth.corsixth.metainfo.xml:133: Cyrllic ==> Cyrillic
- CorsixTH/com.corsixth.corsixth.metainfo.xml:145: Ukranian ==> Ukrainian
- CorsixTH/com.corsixth.corsixth.metainfo.xml:166: Ukranian ==> Ukrainian
- CorsixTH/com.corsixth.corsixth.metainfo.xml:269: Cyrllic ==> Cyrillic
- CorsixTH/Lua/epidemic.lua:554: alredy ==> already
- CorsixTH/Lua/room.lua:40: co-ordinate ==> coordinate
- CorsixTH/Lua/room.lua:41: co-ordinate ==> coordinate
- CorsixTH/Lua/objects/doors/swing_door_right.lua:50: Co-ordinate ==> Coordinate
- CorsixTH/Lua/objects/doors/swing_door_right.lua:51: Co-ordinate ==> Coordinate
- CorsixTH/Lua/objects/doors/swing_door_right.lua:53: accomodate ==> accommodate
- …
=> Fixed the typos mentioned in Issue 2784

CorsixTH/Lua/app.lua, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/patient.lua
*Fixes #2770*
- Renames `sad7` to `sad2`
- Renames `sad2 - sad6` to `dying1 - dying5`
- Adjusts priority of  new `sad2` to be before `dying` moods
- Adjusts patient wait mood priority to coincide
- Restructures comments
- Updates affected humanoids with old `sad2` and `sad7`. The other sad ones won't matter, as the mood priority order will trump them anyway as they die more / cure / die.
@ARGAMX -- I have a suspicion this PR currently might have changed behaviour of the patient wait icon. However, sad2 is still trumping patient_wait as before so I think I've just imagined it.
If possible, I can adjust it if the original has a specified behaviour so wait has priority over regular sadness.
=> Adjust mood icons

CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h, CorsixTH/Src/th_lua_gfx.cpp, CorsixTH/Src/th_lua_ui.cpp
Create separate method for testing if a sprite is visible at all.
Addresses #2779
=> Add method for sprite visibility test

CorsixTH/Lua/entities/machine.lua, CorsixTH/Lua/humanoid_actions/use_object.lua
- Adds comment, some lua docs, and a few empty lines for better readability.
- Replaces some `DrawFlags` magic constants.
- Fixes the logic for required minimal use (does not affect the only case that uses it, since the dna fixer has 1 frame (ie any number of frames is correct), and `20 % 10 == 0` so nothing is actually added).
To understand how it's broken, the old code was:
``` diff
- local length = anim_length * humanoid.world:getAnimLength(anim)
- if action.min_length and phase == 0 and action.min_length > length then
-   -- A certain length is desired.
-   -- Even it out so that an integer number of animation sequences are done.
-   length = action.min_length + action.min_length % length
- end
```
- `anim_length` is the number of animations …
=> Cleanup/"fix" the UseObjectAction

.luacheckrc, CorsixTH/Lua/app.lua, CorsixTH/Lua/world.lua
Add pseudo-random Poission distribution function.
=> Add Poisson distribution function.

CorsixTH/Lua/app.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/hospitals/player_hospital.lua
*Fixes #2760*
- Checks the active epidemic and future epidemic pool for any Serious Radiation epidemics and removes them
While writing this I realise borrowing and revising the `cancelEpidemics` code may have been overkill; and possible that a simple copy of code into the afterload may have been wiser and cleaner...
=> Remove Serious Radiation epidemics

CorsixTH/Lua/world.lua
*Fixes #2788*
- Attempting to update speed normally from a change in the tick rate table causes `self.prev_speed` to be set to `nil`
- Instead, tick rates are directly assigned for this afterload only
- Failsafe also altered, so the game is briefly set to pause rates, then normal speed is reapplied.
- the `Speed up` tick rate is also now entered for the original `old_tick_rates` table.
In both cases these changes will retain the `self.prev_speed` value.
Only downside is if the game was paused; in the failsafe method it will unpause. But that should be addressed separately e.g. as part of #2254 patches.
=> Fix tick_rate remapping

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/fullscreen/fax.lua, CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua, CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/map.lua, CorsixTH/Lua/world.lua
*Fixes #2742*
- Adds a new function to look for a campaign file in the users campaign folder, as well as the Corsixth folder, copied from the getAbsolutePathToLevelFile function above it. 
- Add the users campaign folder to the search in the custom campaigns dialog.
=> Include the users campaign dir in looking for campaigns

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/watch.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/epidemic.lua, CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/hospital.lua, CorsixTH/Lua/humanoid_actions/vaccinate.lua
- `coverup_in_progress` renamed to `coverup_selected` as this flag indicates the fact that the coverup was ever started for this epidemic
- `patient:setMood` calls moved from `epidemic.lua` and `vaccinate.lua` to `patient.lua`
- due to `hospital.lua` improper `afterLoad` call, afterLoad was always crash for savegames with `SAVEGAME_VERSION` less than `106`
- `SAVEGAME_VERSION` bump
=> Epidemic refactoring. `coverup_in_progress` rename.

CorsixTH/Src/main.cpp
*Fixes #*
- Add standard interpreter path when setting a custom install directory and standard `/usr` prefix for Linux
This is needed while working on building for AppImage.
=> Add interpeter path for portable linux installs

CorsixTH/Lua/audio.lua
*Fixes #1978*
- Sets the volume after starting playing the track - SDL2_mixers midi volume function on windows uses a handle to the stream to set the volume which requires that Mix_PlayMusic is called to open that handle initially.
=> Set volume straight after music is set playing

CorsixTH/Lua/world.lua
*Fixes #2796*
-
- Made proper `self.app = self.ui.app` in `afterLoad` which was missed.
=> Afteload minor fix in world.lua

CMakeLists.txt, CMakePresets.json, CorsixTH/CMakeLists.txt
VLD is no longer maintained so it's removed.
Added a convenience option for enabling AddressSanitizer: https://github.com/google/sanitizers/wiki/AddressSanitizer
The options provided here work in gcc and llvm. Address sanitizer is available in MSVC but may use a slightly different flag.
I have not enabled it in the windows dev preset because I cannot test it.
=> Add support for AddressSanitizer, drop VLD

CorsixTH/Lua/api_version.lua, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_lua.h, CorsixTH/Src/th_map.cpp
- Replaced the 'drawable' base class function pointers by abstract virtual methods.
- Implemented them in 'animation' and 'sprite_render_list'.
- Added an enumeration to 'animation' to track the kind of animation that is stored.
- Deleted all the functions of the removed function pointers.
- Simplify extending to secondary marker support.
=> Refactor drawable draw / hit_test / is_multiple_frame_animation methods

CorsixTH/Lua/room.lua
Fixes a bug introduced in #2333 
- If a queue was empty after a patient entered the room the wait toggle did not clear.
- Now clears the wait mood when a patient enters the room without checks. The original safeguard was for setting mood, rather than removing it.
- Tidied some doc.
=> Fix stuck wait moods

CorsixTH/Lua/api_version.lua, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_lua_anims.cpp
*Fixes animations with both a staff member and a patient, with different moods.
- Rename the first marker.
- Add a child animation that follows the second marker.
- Add a way to follow the second marker position of the parent animation.
Can be read by commit if so desired.
=> Allow using the secondary marker

CorsixTH/Lua/api_version.lua, CorsixTH/Lua/dialogs/fullscreen/staff_management.lua, CorsixTH/Lua/dialogs/patient.lua, CorsixTH/Lua/dialogs/resizables/calls_dispatcher.lua, CorsixTH/Lua/dialogs/staff_dialog.lua, CorsixTH/Lua/dialogs/staff_rise.lua, CorsixTH/Lua/graphics.lua, CorsixTH/Src/th_lua_anims.cpp
Remove the old `getMarker` and `setFrameMarker` CPP functions for Lua, as they are now named `getPrimaryMarker` respectively `setFramePrimaryMarker`.
Also updates the API version since some functions "vanished" :)
=> Remove obsolete getMarker/setFrameMarker

CorsixTH/Lua/rooms/operating_theatre.lua
*Fixes #866*
Part of the Operating Theatre META #2809 (task **x103**)
-
- Preventing sticking Surgeons if patient fed up
=> Operation Theatre. Surgeons should not stuck 

CMakeLists.txt, CorsixTH/CMakeLists.txt, CorsixTH/Lua/api_version.lua, CorsixTH/Lua/graphics.lua, CorsixTH/Src/config.h.in, CorsixTH/Src/th_lua.cpp
- Look for a bundled Noto CJK font, or a packager chosen bundled font path or a system font path. The official Noto project doesn't release a suitable single file, but there are some third party builds that do. [satbyy](https://github.com/satbyy/go-noto-universal/releases/tag/v7.0) has [GoNotoKurrent-Bold.ttf](https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoKurrent-Bold.ttf), I chose this because the licence on this project is clearer.
Other font options include [KlokanTechNotoSansCJK-Regular.otf from klokantech](https://github.com/klokantech/klokantech-gl-fonts) or [GoNotoKurrent-Regular.ttf from satbyy](https://github.com/satbyy/go-noto-universal).
- The new priority is user setting > bundled font > system font. Linux …
=> Look for a bundled Noto CJK font

CorsixTH/Lua/queue.lua
- Added some comments for better understanding.
- `#self` calls replaced by `self:size()` calls, as more readable and understandable.
`afterLoad` is not required as changed priority values had never stored.
check #1763 for more context.
=> Queue minor refactoring

CorsixTH/Lua/dialogs/bottom_panel.lua, CorsixTH/Lua/dialogs/fullscreen/town_map.lua, CorsixTH/Lua/graphics.lua, CorsixTH/Lua/languages/czech.lua, CorsixTH/Lua/languages/greek.lua, CorsixTH/Lua/languages/hungarian.lua, CorsixTH/Lua/languages/japanese.lua, CorsixTH/Lua/languages/korean.lua, CorsixTH/Lua/languages/polish.lua, CorsixTH/Lua/languages/russian.lua, CorsixTH/Lua/languages/simplified_chinese.lua, CorsixTH/Lua/languages/traditional_chinese.lua, CorsixTH/Lua/languages/ukrainian.lua, CorsixTH/Lua/strings.lua
*Fixes #2650*
- This algorithm has been implemented (link to comment):
https://github.com/CorsixTH/CorsixTH/issues/2650#issuecomment-2386443272
Feature is working fine.
~~Problem that is no longer relevant:~~
<details>
<summary>problem details</summary>
But during the work on PR I encountered a problem that I unable to solve gracefully.
I had to place `IsArabicNumerals(true)` in the language files in a specific way for this parameter to work - before `Language()` parameter.
If I place `IsArabicNumerals(true)` under `Language()` then the things works like there is no any `IsArabicNumerals(true)` in language file.
If I move `Language()` lower, so that it is under `IsArabicNumerals(true)`, then all works fine. 
Can anyone explain why this is …
=> [RDY] Money Bar non-CJK unicode fix

CorsixTH/Lua/calls_dispatcher.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/hospitals/player_hospital.lua, CorsixTH/Lua/room.lua, CorsixTH/Lua/rooms/gp.lua
This is a proposal to address these issues. The fix has had some funky behaviour in scenarios where a Dr calls to the room, patient leaves for toilet, before call is completed, then the staff member leaves the room and heads to the next room, where the same thing occurs and ended up returning to the same first room.
There is also a change to prefer wandering staff but not sure how effective that is at the moment to get them, due to the weighting of fatigue beforehand. For when excess staff are employed and they leave staff room after rest and there is no call, they start wandering, but they'll have near 0 fatigue and all else being equal is a distance difference of 10 tiles to have the staff leave the room instead.
*Fixes #1582 
Fixes #2060*
- …
=> Change how staff find work

CMakeLists.txt, CorsixTH/CppTest/CMakeLists.txt
Trying to build CorsixTH on Debian 12, Catch2 was one dependency I couldn't satisfy. This option allows CMake to fetch the files it needs for unit tests.
=> Option for CMake to fetch Catch2

CorsixTH/Src/persist_lua.cpp, CorsixTH/Src/th.h, CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_map.cpp
luaT_testuserdata only works correctly if it is passed the correct
metatable reference, and the implementation we had assumed that was the
current environment table, but in the case of map loading it wasn't.
I wrote a replacement method for determining the class of the
animation_base userdata that depends on the __class_name stored in the
metatable.
There was an additional problem with persistence breaking any new saves:
it was using the void* of link_list rather than the class itself.
link_list was not polymorphic so I added the virtual destructor to fix
that and give it a vtable, then dynamic_cast to ensure the proper
pointer type was persisted.
*Fixes #2826*
=> Fix animation refactor regression

CorsixTH/Lua/earthquake.lua
*Fixes error on load some old saved games. Example save game attached to issue 1249.*
- Made proper check `if old_quake then` before accessing `old_quake.active` in `afterLoad` which was missed.
=> Afterload minor fix in earthquake.lua

CorsixTH/Lua/objects/loo.lua, CorsixTH/Lua/objects/sink.lua
*Addresses #2794*
- Fixes female `begin_use` animation markers, as the `begin_use_2` animation for female aliens was incorrectly set
- Fixes sink markers, as they accidentally were told to use staff markers
=> Fix markers in toilets

CorsixTH/Lua/app.lua, CorsixTH/Lua/hospitals/player_hospital.lua, CorsixTH/Lua/humanoid_actions/check_watch.lua, CorsixTH/Lua/humanoid_actions/die.lua, CorsixTH/Lua/humanoid_actions/falling.lua, CorsixTH/Lua/humanoid_actions/get_up.lua, CorsixTH/Lua/humanoid_actions/idle_spawn.lua, CorsixTH/Lua/humanoid_actions/knock_door.lua, CorsixTH/Lua/humanoid_actions/multi_use_object.lua, CorsixTH/Lua/humanoid_actions/on_ground.lua, CorsixTH/Lua/humanoid_actions/pee.lua, CorsixTH/Lua/humanoid_actions/shake_fist.lua, CorsixTH/Lua/humanoid_actions/sweep_floor.lua, CorsixTH/Lua/humanoid_actions/tap_foot.lua, CorsixTH/Lua/humanoid_actions/use_object.lua, CorsixTH/Lua/humanoid_actions/use_screen.lua, CorsixTH/Lua/humanoid_actions/vomit.lua, CorsixTH/Lua/humanoid_actions/walk.lua, CorsixTH/Lua/humanoid_actions/yawn.lua, CorsixTH/Lua/objects/doors/swing_door_right.lua, CorsixTH/Lua/world.lua
World supplies the length of an animation for some reason while the better way to do that is through `TheApp.animation_manager`.
- It goes there eventually anyway.
- World is about world and not about animations.
- No other uses of `world.animation_manager` exist.
=> Eliminate world.animation_manager

AnimView/frmMain.cpp, AnimView/frmMain.h
Adds the bottom row:
- You can enter a mood position, and press "This frame" to set the position.
Both pixel and tile positions work, except the latter may be less accurate.
- You can click the arrow buttons to move the mood 1 pixel in the indicated position.
Each time you set a mood, a text line is printed to `stdout` of the form `frame, {x, y, "px"},` and a comment what animation it is from.
```
2, {5, 20, "px"}, -- Anim 0
3, {15, 20, "px"}, -- Anim 0
```
=> Extend animview

CorsixTH/Lua/objects/crash_trolley.lua
Addresses #2794 
- Add mood markers to crash trolley animations.
It looks like they are not working though. Staff mood is turned off when the patient starts being examined, and turns on again afterwards.
=> Add moods for crash trolley animations.

CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/room.lua, CorsixTH/Lua/rooms/general_diag.lua
*Fixes #1328*
- Fix. In `general_diag.lua`. Reworked `GeneralDiagRoom:commandEnteringPatient`. The sequence of events in the room has been made more sustainable to attempts to grab the doctor at inappropriate moments or to kick the patient out at inappropriate moments. Added comment to actions.
- Fix. In `humanoid.lua`. Improvements for `uninterruptible` actions logic. (was necessary to this General Diagnosis fix)
- Fix. In `room.lua`. Previously In `onHumanoidEnter` new staff was only able to replace old one only if `not old_staff_in_room.dealing_with_patient`. But `dealing_with_patient` was not really indicating dealing with patient, in fact only indicating that patient in the room. So I changed it to `not old_staff_in_room.dealing_with_patient …
=> General Diagnosis. Crash fixes on doctor change

.clang-tidy, .github/workflows/Linux.yml, AnimView/frmMain.cpp, CorsixTH/Src/persist_lua.cpp, CorsixTH/Src/th_gfx_sdl.cpp, CorsixTH/Src/th_gfx_sdl.h, CorsixTH/Src/th_lua_sound.cpp, CorsixTH/Src/th_lua_ui.cpp, CorsixTH/Src/th_movie.cpp, CorsixTH/Src/xmi2mid.cpp, libs/rnc/rnc.cpp
Switched to 20 of the clang-tools, the current latest.
It is fairly easy to acquire any version of these tools, either for debian based distros packaged by llvm, https://apt.llvm.org/ or static compiled 3rd party binaries at https://github.com/muttleyxd/clang-tools-static-binaries/releases - I will add these links to the wiki after this is merged.
For now I suppressed all rules that resulted in new warnings and only addressed the new errors. Future work should review the suppressed rules and fix any that we do want to enforce.
=> Bump clang-format and clang-tidy for linux pipeline

CorsixTH/Lua/entities/humanoid.lua
*Fixes swingdoor mood position.
The old positions were not entirely correct (animations don't start and/or end center-tile). Also, it used hard-coded frame offsets but the various animations differ in the number of frames, so the end-position was often outside the frame range.
I ran a test in a somewhat flaky version, but the nurse worked:
=> Fix swingdoor mood

AnimView/frmMain.cpp
Found by lewri, `printf` of a `size_t` value needs `%zd` rather than `%ld`.
=> Use %zd for printing a size_t value.

CorsixTH/Lua/objects/machines/cast_remover.lua
Fix mood positions of cast remover animations.
Test saves also tried, and no problems.
=> Add mood position of the cast remover animations

CorsixTH/Src/th_gfx_sdl.cpp
NOLINT comment also works for clang-tidy and doesn't trigger a warning in other compilers. Hopefully in the future compilers adopt the attribute or make it easier to suppress, but for now the comment is a better experience.
=> Replace clang::suppress attribute

CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
*Fixes #2660*
- `UIStaffManagement.close()` when pressing staff window moved from `onMouseDown` to `onMouseUp` (Why it ever was on `onMouseDown`?..)
=> Staff Management. Press on staff window interferes world.

.gitignore, vcpkg-configuration.json
+ catch2 3.8.1
+ curl[core,openssl,ssl] 8.13.0#1
~ ffmpeg[avcodec,avformat,core,swresample,swscale] 7.1.1#2
+ fluidsynth[buildtools,core,sndfile] 2.4.6#1
freetype[brotli,bzip2,core,png,zlib] 2.13.3
lpeg 1.1.0#1
lua[core,tools] 5.4.7
~ luafilesystem 1.8.0#7
+ sdl2[core,dbus,ibus,wayland,x11] 2.32.6
~ sdl2-mixer[core,fluidsynth,libflac,libmodplug,mpg123,opusfile,wavpack] 2.8.1#1
+ wxwidgets[core,debug-support,sound] 3.2.7
+ version bumped by this PR
~ port updated by this PR but same version
=> Bump vcpkg for May 2025

CorsixTH/Lua/app.lua
*Fixes #2831
Allow optional files to be missing without reporting them as corrupt.
=> Allow missing video files.

CorsixTH/Lua/humanoid_actions/use_screen.lua, CorsixTH/Lua/objects/machines/operating_table.lua, CorsixTH/Lua/objects/machines/operating_table_b.lua, CorsixTH/Lua/objects/screen.lua, CorsixTH/Lua/objects/surgeon_screen.lua
*Addresses #2794*
- Adds staff markers for operating theatre [Done]
- Moves animation marker set out of use_screen action back to their object files [Done]
- Adds markers for screens and surgeon screens [Done]
=> Fix operating theatre and screen markers

CorsixTH/Lua/dialogs/place_staff.lua, CorsixTH/Lua/humanoid_actions/pickup.lua
*Fixes #2696*
- If a staff member is picked up from a room that then explodes, they can't be returned to the room by closing the pickup 'window', they instead die.
=> Kill staff returned to crashed rooms

CorsixTH/Lua/entities/humanoid.lua
We had these warnings since 2013. Let's just eliminate them, as apparently are not saying something very important.
=> Drop log warnings about trying to remove nonexistent room callbacks.

LICENSE.txt
We ship these files at least with our Windows installer so they should be part of the license information.
=> Add license information for Fluid (R3) Soundfont

CorsixTH/Lua/entity.lua
Fixes a regression from #2824 where some entities had no marker for a current action.
Argument is that the save system could be investigated not to try and cache this data, so it pulls the new mood marker information.
Untested, but I think this change may have some additional knock on effects to #2177
=> Handle in-flight actions without mood marker

CorsixTH/Lua/graphics.lua
Fixes #2903
I had renamed loadFontAndSpriteTable from loadFontAndSpriteSheet but missed a spot.
=> Fix misnamed function call loading font for hotkeys

CorsixTH/Lua/hospitals/player_hospital.lua
*Fixes #2913*
- Changes in #2133 targeted handymen unnecessarily.
- Excludes handymen from daily find work task; which will stop so many orphaned tasks happening.
=> Restore handyman cleaning abilities

CorsixTH/Lua/app.lua, CorsixTH/Lua/dialogs/resizables/main_menu.lua, CorsixTH/Lua/languages/czech.lua, CorsixTH/Lua/languages/dutch.lua, CorsixTH/Lua/languages/english.lua, CorsixTH/Lua/languages/french.lua, CorsixTH/Lua/languages/spanish.lua, CorsixTH/Lua/world.lua
Proposal to give the option to the user to restart their level for very old saves compared to just information.
This method might be too assertive on the player so it can be dropped if it's going to be too far.
- Changes this UIInformation to a UIConfirmDIalog for old saves.
- Adapts `App:restart()` to take an optional message for the box
=> Encourage level restarts on very_old_saves

.github/workflows/WindowsInstaller.yml
- Puts the Noto regular font in the installer as CorsixTHUnicode.ttf, in the folder where it is found on first run (checked on x64, not x86).
https://github.com/tobylane/CorsixTH/actions/runs/16096606383/job/45420234113#step:7:525
=> Download Noto font and include in Windows installer

CorsixTH/Lua/dialogs/fullscreen/hospital_policy.lua, CorsixTH/Lua/dialogs/patient.lua
*Fixes #2948*
- Forces uppercasing of all text in the patient history and hospital policy where it is used (the font `FONT74V` already had uppercase letters in lowercase spots, but also in its uppercase spots). Previously, Unicode fonts did not show history in uppercase.
- Accents that had uppercase inclusions had no lowercase entry.
Potential further enhancement is to see if we can pull missing uppercase letters from another font.
@ARGAMX if possible, can you check this change is compatible with Cyrillic languages in unicode?
=> Fix font74v compat

.luacheckrc, CorsixTH/Lua/entities/humanoid.lua, CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/entities/humanoids/staff/receptionist.lua, CorsixTH/Lua/entities/object.lua, CorsixTH/Lua/entity.lua, CorsixTH/Lua/objects/analyser.lua, CorsixTH/Lua/objects/bin.lua, CorsixTH/Lua/objects/door.lua, CorsixTH/Lua/objects/litter.lua, CorsixTH/Lua/objects/rathole.lua, CorsixTH/Lua/utility.lua, CorsixTH/Luatest/spec/entities/machine_spec.lua, CorsixTH/Luatest/spec/entities/object_spec.lua
*Fixes Rat hole layer
- Introduce constants for the various drawing layers.
- Apply constants instead of magic numbers.
- Drop layers of objects, humanoids, and staff, as they are derived entities.
- Draw a rathole before a side object (instead of after it).
=> Add drawing layers constants

CorsixTH/Lua/ui.lua
*Fixes #*
- Updates Screenshots to be more date/time relationship rather than random numbers. This is more in line with *nix/Android behaviour. It also helps with our goal for better approachability to bug reports. Format `Screenshot_YYYYMMDD-HHMMSS.png`
- Removes the deprecated repeat loop as no longer needed
- Adds a blocker for > 1 screenshot per second.
=> Update screenshot function

CorsixTH/Src/th_gfx.cpp
In particular, do not crop relative to pixel offsets of an animation. 
In the current code, pixel offset of an animation is added to the tile position before installing a crop rectangle of 64 pixels wide. (Lines 1152 to 1166 in the patched file.)
This means that the crop rectangle moves along with the pixel offset of the animation, and thus doesn't crop at tiles edges.
This patch fixes that.
Pixel offsets in tiles are used for humanoids walking, spawning (also a walk), and dying (didn't look closely, perhaps flying?).
Cropping is used for objects.
=> Always crop at tile edges.

CorsixTH/Src/th_sound.cpp, CorsixTH/Src/th_sound.h
Use std containers for memory.
Avoid non-portable packed structure casting.
Fix rule of 3 violations.
I'd expect a further refactor to load the sound data on construction, but that's further than I have time to take this before I leave.
=> Eliminate pragma pack casts and raw memory in sound

CorsixTH/Lua/app.lua, CorsixTH/Lua/strings.lua
*Fixes #2978*
- Adds helper function to check player's specified language exists
- Returns language to English and shows error message on main menu (fixes crash at end of movie and elsewhere). 
- Tell the player the language value they originally set and where to go to fix (as there are now two error types).
- Also includes some refactor to accommodate new handling
- Doc, as usual.
One quirk is that as part of `App:fixConfig()` we force lowercase the language on launch. However, we still try to convert back to lowercase in other places (mostly) unnecessarily. My use of capitalised `[[English]]` on App.lua line 516 probably needs changing if there's a future PR to clean things up.
=> Better error handling for non-existent languages

CorsixTH/Lua/languages/french.lua
*Fixes #2811*
- Add the `%s` and `%d` parameters we pass when replacing machines for other languages.
=> Include machine and cost parameters for replacement dialog

CorsixTH/Src/th_gfx.cpp, CorsixTH/Src/th_gfx.h, CorsixTH/Src/th_lua_anims.cpp, CorsixTH/Src/th_lua_map.cpp
Instead of afterwards re-constructing the animation position from the map, store it in the animation itself.
Commits:
- First commit does renaming of the existing pixel position offset.
- Second commit introduces storage of the animation tile.
- Update api.
- Reformat cpp.
With respect to the pixel position offset, the docs claim that it is updated in the `tick`, but that could have been written afterwards (possibly even by me).
- The `animation` actually does that.
- The `render_sprite_list` however does it both in `tick` and in `draw`.
That looks wrong, since if a sprite is ever active (didn't check but I am guessing we currently don't have that at all), then movement is twice as fast as it should be.
- Morph target updating also looks fishy at first sight, but didn't check either.
=> Store the tile position of an animation in the animation.

CorsixTH/Lua/app.lua
*Fixes #2926*
- Uses the config and environment to find a suitable player name on launch. On first launch, the computer user name will be in the campaign dialog. Would that be a bad surprise for anyone?
- Tidy up the repeated ifs in App:fixConfig. Were they intentional?
=> Improve finding player name

vcpkg-configuration.json
catch2:x64-linux@3.10.0 -- /home/stephen/.cache/vcpkg/registries/git-trees/c36d69b5c0effa33673a22897857f42d264eb1b5
curl[core,openssl,ssl]:x64-linux@8.15.0#1 -- /home/stephen/.cache/vcpkg/registries/git-trees/c5d9f2f0044ff09a375a67bd48932a2c020f5bee
ffmpeg[avcodec,avformat,core,swresample,swscale]:x64-linux@7.1.1#3 -- /home/stephen/.cache/vcpkg/registries/git-trees/eea6888a7ce005aa5813c769e0e179dd0b05f067
fluidsynth[buildtools,core,sndfile]:x64-linux@2.4.6#1 -- /home/stephen/.cache/vcpkg/registries/git-trees/62a2092769a82d7302564639bca90f3ac03b17aa
freetype[brotli,bzip2,core,png,zlib]:x64-linux@2.13.3 -- /home/stephen/.cache/vcpkg/registries/git-trees/8a2c633dcc14eaabdb31cf4637242f4e3c2f3fa2
lpeg:x64-linux@1.1.0#1 -- /home/stephen/.cache/vcpkg/registries/git-trees/933131ff56540fca7bbfb7a4c …
=> Bump vcpkg version

CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/rooms/gp.lua
*Fixes #2974*
- Added earlier check for a GP that there are not enough diagnostic rooms for over-diagnosis. So if minimum diagnostic threshold has been reached the diagnosis should be set in such a case.
=> Late diagnosis termination bug fix.

CorsixTH/Lua/languages/english.lua
*Fixes #3004*
This pull request improves the tooltips that appear when hovering over certain rooms in the Build Rooms menu, as well as the Reception Desk in the Furnish Corridor menu. I've tested my changes locally and can confirm that the original strings will be overridden.
=> Improved tooltips in Build Rooms/Furnish Corridor menus

CorsixTH/Lua/app.lua
* Fixes #3010 
- Make readLevelInfo load maps from Theme Hospital ONLY when map name look like "LEVEL.L(int)". Before this change, CTH would try to load any map from Theme Hospital, if map name started from "LEVEL".
=> Fix regular expressions in readLevelInfo

CorsixTH/Lua/dialogs/bottom_panel.lua, CorsixTH/Lua/entities/humanoids/patient.lua, CorsixTH/Lua/epidemic.lua, CorsixTH/Lua/graphics.lua, CorsixTH/Lua/humanoid_action.lua, CorsixTH/Lua/rooms/general_diag.lua, CorsixTH/Lua/rooms/operating_theatre.lua, CorsixTH/Src/th_gfx.h
- Fixes various typos in comments (identified by [Linux apt-get Lua 5.1](https://github.com/CorsixTH/CorsixTH/actions/runs/17744976406/job/50427959171#logs))
- Refactored `setUninterruptable()` to `setUninterruptible()`
=> fixed various typos in comments, renamed setUninterruptable() to setUninterruptible()

CorsixTH/Lua/entities/humanoids/staff.lua, CorsixTH/Lua/entities/humanoids/staff/doctor.lua, CorsixTH/Lua/rooms/training.lua
*Fixes #2964*
- Reworked staff idle check to properly handle returning doctors to research/training.
@ARGAMX please extensively test I've not broken other call states e.g. dropping answers to rooms.
=> Let staff return to training/research

CorsixTH/Src/th_lua_map.cpp
*Fixes #3000
- I made a mistake in PR #2987, in assigning the incorrect coordinates to map tiles at the east wall while changing (and I guess also building) a room.
- Lewri found the bug 🥳
=> Fix the tile coordinates of the animations at the east wall.

AnimView/frmMain.cpp
*Fixes Compile problem with AnimView
- Does not include "wx/strimpl.h" in AnimView/frmMain.cpp anymore, as it doesn't seem to exist in newer wx versions.
=> Drop WX stringimpl.h header include

CorsixTH/Lua/entities/humanoids/patient.lua
*Fixes #2736*
- Restores the functionality of the Epidemiology Cursor to the same UX as in the original game.
Test cases:
```
Clicking with vaccination mode off:
Epidemic not marked patient - mark.
Epidemic marked patient - open window.
Regular patient - open window.
Clicking with vaccination mode on:
Epidemic not marked patient - mark. 
Epidemic marked patient - do nothing.
Regular patient - do nothing.
```
=> Epidemic. Vaccination cursor does not work fix

CorsixTH/Lua/dialogs/build_room.lua, CorsixTH/Lua/dialogs/edit_room.lua, CorsixTH/Lua/dialogs/fullscreen/hospital_policy.lua, CorsixTH/Lua/dialogs/fullscreen/staff_management.lua, CorsixTH/Lua/dialogs/furnish_corridor.lua, CorsixTH/Lua/dialogs/information.lua, CorsixTH/Lua/dialogs/menu.lua, CorsixTH/Lua/dialogs/patient.lua, CorsixTH/Lua/dialogs/place_objects.lua, CorsixTH/Lua/dialogs/staff_dialog.lua, CorsixTH/Lua/dialogs/watch.lua, CorsixTH/Lua/game_ui.lua, CorsixTH/Lua/window.lua
Fixes 
* #3025 
* #3018 
- Lots "ding!" sounds (HLight5.wav and HLightP2.wav) are implemented, in these situations:
- Build room (switched from HLightP2.wav to HLight5.wav which TH uses in this dialog)
- Furnish corridor / Furnish room
- Top menu
- Timer buttons
- UIInformation close button
- Hovering over humanoid with cold/hot mood
- Hovering over room/door with queue
- Hovering over object list in place objects dialog
- Lots select sounds (Selectx.wav) are implemented, in these situations:
- Switch between treatment history / graph in patient dialog
- Fire staff button
- Handymen priorities change
- Handymen plot change
- Selecting staff in staff management panel
- Toggle buttons in policy dialog
- Furnish room and move items buttons
- Buy …
=> Add missing hover and click sound effects in various places

CorsixTH/Lua/dialogs/fullscreen/fax.lua
Closer match the left margin and give a little bit more room for the level 12 win message.
Fixes #3058
Let me know what you think.
All 4 messages:
=> Shrink the right margin of the fax
